"""
Constant canonicals for the `brain` family.

3 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

import math
import os

# --- assign: BOARD_URL ---
# composed_from=27
# witness=staging\by-family\interrogation\partsfactory\interrogation.py
BOARD_URL = os.getenv("BOARD_URL", "http://tmn2-board:8000")

# --- assign: COUPLING ---
# composed_from=66
# witness=staging\by-family\cqe\partsfactory\CQE_GVS_MONOLITH.py
COUPLING = float(
    os.getenv("CMPLX_BRAIN_COUPLING", os.getenv("COUPLING", "0.030076"))
)

# --- assign: PIPELINE_URL ---
# composed_from=23
# witness=staging\by-family\morphon\morphonic\morphon.py
PIPELINE_URL = os.getenv("PIPELINE_URL", "http://tmn2-pipeline:8000")

PHI = (1.0 + math.sqrt(5.0)) / 2.0

TMN_INIT_DIMS = 24
TMN_MAX_DIMS = 96
TOP_K = 3
FREEZE_EPOCH = 300

ALPHA_BY_TIER = {
    "nascent": 0.30,
    "apprentice": 0.40,
    "journeyman": 0.50,
    "master": 0.60,
    "architect": 0.70,
}

TIER_THRESHOLDS = {
    "nascent": 0,
    "apprentice": 10,
    "journeyman": 50,
    "master": 200,
    "architect": 1000,
}

LATTICE_ROLES = ("SELF", "MEMORY", "BODY", "ATTENTION")

DEFAULT_DOMAINS = (
    "architecture",
    "conservation",
    "code",
    "interaction",
    "data",
    "operations",
    "labeling",
    "synthesis",
)

CONTROL_EXPERTS = ("sentinel", "arbiter", "porter")
