"""
Composed canonical: LeechLattice

Family: leech
Decision: batch=11 id=947
Composition: method-union of 11 variants → 44 methods (33 conflicts resolved), 4 attrs

Auto-generated by place_canonicals.py from the atomic decision queue.
Do not edit by hand — re-run the merger to refresh.
"""
from __future__ import annotations

class LeechLattice:
    """
    Leech lattice - unique 24D lattice with no roots.

    Construction via 3×E8:
    - Take 3 copies of E8 (8D each = 24D total)
    - Apply Golay code structure
    - Result is Leech lattice

    This demonstrates morphonic emergence: Leech is not constructed
    algorithmically, but emerges from E8 + Golay structure.
    """
    DIMENSION = 24
    MIN_NORM = 4
    DIM = 24
    MINIMAL_VECTORS = 196560

    def __init__(self):
        """Initialize Leech lattice"""
        self.dimension = 24
        self.kissing_number = 196560
        self.minimal_norm = 4.0
        self.e8 = E8Full()
        self.golay = GolayCode()
        print('Leech lattice initialized')
        print(f'  Dimension: {self.dimension}')
        print(f'  Kissing number: {self.kissing_number}')
        print(f'  Minimal norm²: {self.minimal_norm}')

    def __repr__(self) -> str:
        return f'LeechLattice(dim={self.dimension}, minimal_vectors={self.num_minimal})'

    def distance(self, x: np.ndarray, y: np.ndarray) -> float:
        """Compute distance in Leech lattice."""
        return np.linalg.norm(x - y)

    def distance_sq(self, a: np.ndarray, b: np.ndarray) -> float:
        va = np.asarray(a, dtype=np.float64)[:LEECH_DIM]
        vb = np.asarray(b, dtype=np.float64)[:LEECH_DIM]
        d = va - vb
        return float(np.dot(d, d))

    def distance_to_lattice(self, vector: np.ndarray) -> float:
        """
        Compute distance from vector to nearest Leech lattice point.

        Args:
            vector: 24D input vector

        Returns:
            Euclidean distance to nearest lattice point
        """
        projected = self.project(vector)
        return np.linalg.norm(vector - projected)

    def embed_e8(self, e8_vec: np.ndarray, block: int=0) -> np.ndarray:
        """
        Embed an 8D E8 vector into 24D Leech space.

        Args:
            e8_vec: 8D vector (should be E8 lattice point)
            block: which E8 block (0, 1, or 2)

        Returns:
            24D vector with e8_vec placed in the specified block,
            zeros elsewhere.
        """
        v = np.zeros(LEECH_DIM, dtype=np.float64)
        start = block * E8_DIM
        v[start:start + E8_DIM] = np.asarray(e8_vec, dtype=np.float64)[:E8_DIM]
        return v

    def embed_triple(self, e8_a: np.ndarray, e8_b: np.ndarray, e8_c: np.ndarray) -> np.ndarray:
        """
        Embed three E8 vectors as a 3×E8 point in Leech space.
        This is the direct sum; for full Leech points, glue vectors
        may need to be added.
        """
        v = np.zeros(LEECH_DIM, dtype=np.float64)
        v[0:8] = np.asarray(e8_a, dtype=np.float64)[:8]
        v[8:16] = np.asarray(e8_b, dtype=np.float64)[:8]
        v[16:24] = np.asarray(e8_c, dtype=np.float64)[:8]
        return v

    def extract_e8(self, leech_vec: np.ndarray, block: int=0) -> np.ndarray:
        """Extract the E8 component from a Leech vector."""
        v = np.asarray(leech_vec, dtype=np.float64)[:LEECH_DIM]
        start = block * E8_DIM
        return v[start:start + E8_DIM].copy()

    def from_e8_triple(self, e8_1: np.ndarray, e8_2: np.ndarray, e8_3: np.ndarray) -> np.ndarray:
        """
        Lift three E8 vectors to Leech lattice.

        Construction:
        1. Concatenate three 8D E8 vectors → 24D vector
        2. Apply Golay code structure for correction
        3. Result is Leech vector

        Args:
            e8_1, e8_2, e8_3: Three 8D E8 vectors

        Returns:
            24D Leech vector
        """
        assert len(e8_1) == 8 and len(e8_2) == 8 and (len(e8_3) == 8)
        leech_vector = np.concatenate([e8_1, e8_2, e8_3])
        leech_vector = np.round(leech_vector)
        if np.sum(leech_vector) % 2 != 0:
            leech_vector[0] += 1
        return leech_vector

    def generate_minimal_vectors(self, count: int=100) -> List[LeechVector]:
        """
        Generate sample minimal vectors (norm² = 4).

        Full Leech has 196,560 minimal vectors. We generate a sample.

        Args:
            count: Number of vectors to generate

        Returns:
            List of minimal LeechVectors
        """
        minimal_vectors = []
        for _ in range(count):
            e8_1 = self.e8.all_roots[np.random.randint(0, 240)].vector
            e8_2 = self.e8.all_roots[np.random.randint(0, 240)].vector
            e8_3 = self.e8.all_roots[np.random.randint(0, 240)].vector
            leech_vec = self.from_e8_triple(e8_1, e8_2, e8_3)
            if np.dot(leech_vec, leech_vec) <= 4.1:
                minimal_vectors.append(LeechVector(leech_vec, 0, True))
        return minimal_vectors

    def generate_receipt(self, operation: str, **kwargs) -> dict:
        """Generate receipt for Leech operation"""
        receipt = {'operation': operation, 'lattice': 'Leech', 'dimension': self.dimension, 'timestamp': np.datetime64('now').astype(str), **kwargs}
        receipt_str = json.dumps(receipt, sort_keys=True)
        receipt['hash'] = hashlib.sha256(receipt_str.encode()).hexdigest()[:16]
        return receipt

    def generate_vectors(self, max_count: int=1000) -> List[np.ndarray]:
        """
        Generate Leech lattice vectors.

        Uses the "short vector" construction from the Golay code.
        """
        if self._vectors is not None:
            return self._vectors[:max_count]
        vectors = []
        octads = self._generate_octads()
        for octad in octads[:max_count // 3]:
            for signs in self._even_sign_combinations(8):
                vec = np.zeros(24)
                for i, pos in enumerate(octad):
                    vec[pos] = 2 * signs[i]
                vectors.append(vec)
        for _ in range(min(max_count // 3, 100)):
            vec = np.zeros(24)
            pos_3 = np.random.randint(0, 24)
            vec[pos_3] = 3 if np.random.random() < 0.5 else -3
            for i in range(24):
                if i != pos_3:
                    vec[i] = 1 if np.random.random() < 0.5 else -1
            if np.dot(vec, vec) == 4 * 24:
                vectors.append(vec)
        for i in range(min(24, max_count // 3)):
            vec = np.zeros(24)
            vec[i] = 4
            vectors.append(vec)
            vec = np.zeros(24)
            vec[i] = -4
            vectors.append(vec)
        self._vectors = vectors
        return vectors[:max_count]

    def get_automorphism_order(self) -> int:
        """
        Return order of Conway group Co₀.

        The full automorphism group of the Leech lattice.
        """
        return 8315553613086720000

    def get_cartan_matrix(self) -> np.ndarray:
        """
        Get Cartan matrix.

        The Leech lattice has no roots, so this returns identity.
        """
        return np.eye(24, dtype=int)

    def info(self) -> Dict:
        """Return lattice information."""
        return {'dimension': self.dimension, 'minimal_norm_squared': self.minimal_norm_squared, 'kissing_number': self.kissing_number, 'golay_codewords': len(self.golay_codewords), 'minimal_vectors_sampled': len(self.minimal_vectors)}

    def inner_product(self, a: np.ndarray, b: np.ndarray) -> float:
        va = np.asarray(a, dtype=np.float64)[:LEECH_DIM]
        vb = np.asarray(b, dtype=np.float64)[:LEECH_DIM]
        return float(np.dot(va, vb))

    def is_lattice_point(self, vec: np.ndarray) -> bool:
        """
        Check if a 24D vector is a valid Leech lattice point.
        Simplified check: each 8D block must be E8, and the
        direct sum must have norm ≥ 4 (Leech has no roots).
        """
        v = np.asarray(vec, dtype=np.float64)[:LEECH_DIM]
        for block in range(3):
            s = block * E8_DIM
            if not self.e8.is_lattice_point(v[s:s + E8_DIM]):
                return False
        nsq = float(np.dot(v, v))
        if nsq > 0 and nsq < LEECH_MINIMAL_NORM_SQ - 0.01:
            return False
        return True

    def is_leech_vector(self, vector: np.ndarray) -> bool:
        """Check if vector is in Leech lattice"""
        if len(vector) != 24:
            return False
        if not np.allclose(vector, np.round(vector)):
            return False
        if np.sum(vector) % 2 != 0:
            return False
        binary = (vector.astype(int) % 2).astype(int)
        syndrome = self.golay.H @ binary % 2
        return np.all(syndrome == 0)

    def is_minimal(self, vector: np.ndarray, tolerance: float=1e-06) -> bool:
        """
        Check if vector is a minimal vector (norm 4).

        Args:
            vector: 24D vector to check
            tolerance: Numerical tolerance

        Returns:
            True if vector has norm 4 (within tolerance)
        """
        return abs(self.norm(vector) - self.minimal_norm) < tolerance

    def is_on_lattice(self, vector: np.ndarray, tolerance: float=1e-06) -> bool:
        """
        Check if vector is on the Leech lattice.

        Args:
            vector: 24D vector to check
            tolerance: Numerical tolerance

        Returns:
            True if vector is on lattice (within tolerance)
        """
        return self.distance_to_lattice(vector) < tolerance

    def is_valid_coordinate(self, coord: np.ndarray) -> bool:
        """Check if coordinate is in Leech lattice"""
        if len(coord) != self.DIMENSION:
            return False
        if not np.allclose(coord, coord.round()):
            return False
        coord_sum = np.sum(coord)
        if coord_sum % 4 != 0:
            return False
        return True

    def kissing_number(self) -> int:
        """Number of spheres touching central sphere"""
        return 196560

    def minimal_vectors(self) -> List[np.ndarray]:
        """
        Return minimal norm vectors (norm 4).

        The Leech lattice has 196560 minimal vectors.
        """
        vectors = []
        for i in range(self.DIMENSION):
            vec = np.zeros(self.DIMENSION)
            vec[i] = 2
            vectors.append(vec)
        return vectors

    def nearest_lattice_point(self, vec: np.ndarray) -> np.ndarray:
        """
        Quantize vector to nearest Leech lattice point.

        Uses nearest neighbor algorithm in 24D.
        """
        rounded = np.round(vec).astype(int)
        coord_sum = np.sum(rounded)
        remainder = coord_sum % 4
        if remainder != 0:
            rounded[0] += 4 - remainder
        return rounded

    def nearest_minimal_vector(self, vector: np.ndarray) -> Tuple[LeechVector, float]:
        """
        Find nearest minimal Leech vector to input.

        Returns:
            (vector, distance): Nearest minimal vector and distance
        """
        if not self.minimal_vectors:
            raise ValueError('No minimal vectors generated')
        min_dist = float('inf')
        nearest = None
        for mv in self.minimal_vectors:
            dist = np.linalg.norm(vector - mv.vector)
            if dist < min_dist:
                min_dist = dist
                nearest = mv
        return (nearest, min_dist)

    def norm(self, vector: np.ndarray) -> float:
        """
        Compute the norm of a Leech lattice vector.

        Args:
            vector: 24D vector

        Returns:
            Squared Euclidean norm
        """
        return np.dot(vector, vector)

    def project(self, vector: np.ndarray) -> LeechVector:
        """
        Project arbitrary 24D vector to nearest Leech lattice point.

        Uses Golay code for correction.

        Args:
            vector: 24D vector

        Returns:
            LeechVector (nearest lattice point)
        """
        assert len(vector) == 24
        rounded = np.round(vector)
        binary = (rounded.astype(int) % 2).astype(int)
        corrected_binary = self.golay.correct_errors(binary)
        lattice_point = rounded.copy()
        lattice_point += corrected_binary - binary
        if np.sum(lattice_point) % 2 != 0:
            lattice_point[0] += 1
        return LeechVector(lattice_point, 0, False)

    def project_to_lattice(self, vector: np.ndarray) -> np.ndarray:
        """
        Project 24D vector to nearest Leech lattice point.

        Uses coordinate-wise rounding with Golay code correction.
        """
        rounded = np.round(vector)
        parity = rounded.astype(np.int32) % 2
        distances = np.sum(np.abs(self.golay_codewords - parity), axis=1)
        nearest_idx = np.argmin(distances)
        nearest_codeword = self.golay_codewords[nearest_idx]
        correction = (nearest_codeword - parity) % 2
        corrected = rounded + correction
        return corrected

    def quantize(self, vector: np.ndarray) -> np.ndarray:
        """Quantize a vector to nearest Leech lattice point."""
        rounded = np.round(vector / 2) * 2
        total = np.sum(rounded)
        if total % 8 != 0:
            adjustment = 8 - total % 8
            rounded[0] += adjustment
        return rounded

    def shell_count(self, shell: int) -> int:
        """
        Return number of vectors in shell n.

        Shell n contains vectors with norm² = 2n.
        For Leech: shell 2 has 196,560 vectors (minimal).
        """
        shell_counts = {0: 1, 2: 196560, 4: 16773120, 6: 398034000}
        return shell_counts.get(shell, 0)

    def snap(self, x: np.ndarray) -> np.ndarray:
        """
        Snap a 24D point to Leech lattice using holy construction.

        Input: 24D vector
        Output: Nearest Leech lattice point

        Method:
        1. Split into 3 E8 components (8D each)
        2. Snap each to nearest E8 root
        3. Apply glue correction using Niemeier lattices
        4. Enforce parity constraint
        """
        if len(x) != 24:
            raise ValueError('Vector must be 24-dimensional')
        x1, x2, x3 = (x[:8], x[8:16], x[16:24])
        _, root1, _ = self.e8_1.nearest_root(x1)
        _, root2, _ = self.e8_2.nearest_root(x2)
        _, root3, _ = self.e8_3.nearest_root(x3)
        snapped = np.concatenate([root1, root2, root3])
        glue_correction = np.zeros(24)
        glue_correction[7] = self.glue_code_1 / 10
        glue_correction[15] = self.glue_code_2 / 10
        snapped += glue_correction
        total_sum = np.sum(snapped)
        if int(total_sum) % self.parity_code != 0:
            idx = np.argmin(np.abs(snapped))
            snapped[idx] += self.parity_code - int(total_sum) % self.parity_code
        return snapped

    def theta_series(self, q: complex, terms: int=10) -> complex:
        """
        Theta series: Λ(q) = Σ_{x∈Λ} q^{||x||²}

        Generating function for lattice vector norms.
        """
        result = 0
        for k in range(terms):
            if k == 0:
                count = 1
            elif k == 1:
                count = self.kissing_number()
            else:
                count = 0
            result += count * q ** (4 * k)
        return result

    def theta_series_coefficient(self, n: int) -> int:
        """Approximate theta-series coefficient for shell n."""
        if n == 0:
            return 1
        if n == 1:
            return 0
        if n == 2:
            return self.MINIMAL_VECTORS
        return 0

    def to_dict(self) -> dict:
        """Export Leech structure"""
        return {'lattice': 'Leech', 'dimension': self.dimension, 'kissing_number': self.kissing_number, 'minimal_norm': self.minimal_norm, 'golay_code': {'n': self.golay.n, 'k': self.golay.k, 'd': self.golay.d}}

    def to_e8_triple(self, leech_vector: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Project Leech vector to three E8 vectors.

        This is the inverse of from_e8_triple.

        Args:
            leech_vector: 24D Leech vector

        Returns:
            (e8_1, e8_2, e8_3): Three 8D E8 vectors
        """
        assert len(leech_vector) == 24
        e8_1 = leech_vector[:8]
        e8_2 = leech_vector[8:16]
        e8_3 = leech_vector[16:24]
        e8_1_root, _ = self.e8.project(e8_1)
        e8_2_root, _ = self.e8.project(e8_2)
        e8_3_root, _ = self.e8.project(e8_3)
        return (e8_1_root.vector, e8_2_root.vector, e8_3_root.vector)

    def _build_golay_generator(self) -> np.ndarray:
        """
        Build a simplified Golay-based glue matrix for 3×E8 → Leech.

        The extended binary Golay code [24,12,8] provides the glue.
        Each codeword c ∈ {0,1}^24 with weight ≡ 0 mod 4 gives a glue
        vector g = c/2 that, added to D8^3, produces a Leech lattice point.

        For operational use we store the 12×24 generator matrix.
        """
        P = np.array([[1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1], [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1], [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1], [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1], [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1], [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1], [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1], [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1], [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1], [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1], [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]], dtype=np.float64)
        G = np.hstack([np.eye(12, dtype=np.float64), P])
        return G

    def _construct_e8_basis(self) -> np.ndarray:
        """E8 simple root basis."""
        B = np.array([[1, -1, 0, 0, 0, 0, 0, 0], [0, 1, -1, 0, 0, 0, 0, 0], [0, 0, 1, -1, 0, 0, 0, 0], [0, 0, 0, 1, -1, 0, 0, 0], [0, 0, 0, 0, 1, -1, 0, 0], [0, 0, 0, 0, 0, 1, -1, 0], [0, 0, 0, 0, 0, 0, 1, -1], [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]], dtype=np.float64)
        return B

    def _construct_leech_basis(self) -> np.ndarray:
        """
        Construct Leech lattice basis matrix.

        Uses the MOG (Miracle Octad Generator) construction which
        embeds the Leech lattice as a sublattice of Z^24.

        Returns:
            24x24 basis matrix
        """
        B = np.eye(24, dtype=np.float64)
        return B

    def _even_sign_combinations(self, n: int) -> List[List[int]]:
        """Generate sign combinations with even number of minus signs."""
        import itertools
        combinations = []
        for signs in itertools.product([1, -1], repeat=n):
            if sum((1 for s in signs if s == -1)) % 2 == 0:
                combinations.append(list(signs))
        return combinations

    def _generate_golay_codewords(self) -> np.ndarray:
        """Generate all 4096 Golay codewords."""
        codewords = []
        for i in range(4096):
            info = np.array([i >> j & 1 for j in range(12)], dtype=np.int32)
            codeword = info @ self.golay_generator % 2
            codewords.append(codeword)
        return np.array(codewords)

    def _generate_minimal_vectors_sample(self, sample_size: int=1000):
        """
        Generate a sample of minimal Leech vectors.

        Full generation of 196,560 vectors is expensive;
        this generates a representative sample.
        """
        idx = 0
        for _ in range(min(sample_size, 500)):
            e8_1 = self._random_e8_root()
            e8_2 = self._random_e8_root()
            e8_3 = self._random_e8_root()
            v = np.concatenate([e8_1, e8_2, e8_3])
            v = v / np.linalg.norm(v) * 2
            self.minimal_vectors.append(LeechVector(index=idx, vector=v, norm_squared=4, e8_components=(e8_1, e8_2, e8_3)))
            idx += 1
        for _ in range(min(sample_size - len(self.minimal_vectors), 500)):
            v = np.zeros(24)
            pos = np.random.randint(24)
            v[pos] = 2 * (2 * np.random.randint(2) - 1)
            self.minimal_vectors.append(LeechVector(index=idx, vector=v, norm_squared=4, e8_components=(v[:8], v[8:16], v[16:24])))
            idx += 1

    def _generate_octads(self) -> List[List[int]]:
        """Generate octads (8-element subsets with special properties)."""
        octads = []
        for _ in range(100):
            octad = sorted(np.random.choice(24, 8, replace=False))
            octads.append(octad)
        return octads

    def _golay_basis(self) -> np.ndarray:
        basis = np.zeros((24, 24))
        for i in range(24):
            basis[i, i] = 2.0
            if i > 0:
                basis[i, 0] = 1.0
        return basis

    def _random_e8_root(self) -> np.ndarray:
        """Generate a random E8 root vector."""
        if np.random.random() < 0.5:
            v = np.zeros(8)
            positions = np.random.choice(8, 2, replace=False)
            v[positions[0]] = 2 * np.random.randint(2) - 1
            v[positions[1]] = 2 * np.random.randint(2) - 1
        else:
            signs = np.random.choice([-1, 1], 8)
            if sum(signs == -1) % 2 == 1:
                signs[0] *= -1
            v = 0.5 * signs
        return v
