"""
Constant canonicals for the `cmplx` family.

2 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- assign: ROOT ---
# composed_from=19 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\unclassified\partsfactory\benchmark_contract.py
ROOT = Path(__file__).resolve().parents[1]

# --- assign: E8_NORM ---
# composed_from=44 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\5eb9a193b215__cqe_core__cqe_complete_system.py
E8_NORM = np.sqrt(2)
