"""
Function canonicals for the `cmplx` family.

2 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- function: _sha256_hex ---
# composed_from=18 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\cqe_spine.py
def _sha256_hex(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()

# --- function: digital_root ---
# composed_from=45 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\leech\partsfactory\leech_climate_embedder.py
def digital_root(n):
    n = abs(int(round(n)))
    return 0 if n == 0 else 1 + (n - 1) % 9
