"""
Constant canonicals for the `tarpit` family.

4 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- assign: ETP_OPS ---
# composed_from=33 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
ETP_OPS: List[str] = ["}", "<", ">", "+", "[", "]", "0", "1"]

# --- assign: ETP_CANDIDATES ---
# composed_from=30 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
ETP_CANDIDATES = [
    THIS_DIR / "evolving_tarpit",
    Path("/mnt/data/evolving_tarpit"),
]

# --- assign: ETP_OP_TO_OCT ---
# composed_from=30 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
ETP_OP_TO_OCT: Dict[str, int] = {c: i for i, c in enumerate(ETP_OPS)}

# --- assign: THIS_DIR ---
# composed_from=30 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
THIS_DIR = Path(__file__).resolve().parent
