"""
Function canonicals for the `tarpit` family.

43 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

import hashlib
import json
import math
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from .bond import Dust, Triad
from .ecology import TarpitEcology
from .walls import MirrorOperator


@dataclass
class RelativityEnvelope:
    """Bounded toroidal-drift constraint for ETP runs.

    Per-step `delta_max = max_i |comp_i(t) - comp_i(t-1)|` must stay below
    `max_delta_component`. If `require_mass_lt_1` is true, the mean grain
    mass must also stay strictly below 1.0 (the "closure at 1" convention).

    When `enabled=False`, all checks pass trivially — useful as a no-op
    default for runs that don't require envelope constraints.
    """
    enabled: bool = True
    max_delta_component: float = 0.85
    require_mass_lt_1: bool = True


# --- function: bits6_str ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def bits6_str(bits6: int) -> str:
    if not (0 <= bits6 <= 63):
        raise ValueError("bits6 must be in [0,63]")
    return format(bits6, "06b")

# --- function: _demo ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def _demo() -> None:
    codec = E6Codec()

    # Demo token stream: choose a few opcodes explicitly (op,rep) pairs.
    toks = [
        E6Token(t=0, bits6=merge_from_bf(0, 2), meta={"note": "}}}"}),
        E6Token(t=1, bits6=merge_from_bf(3, 0), meta={"note": "+"}),
        E6Token(t=2, bits6=merge_from_bf(2, 0), meta={"note": ">"}),
        E6Token(t=3, bits6=merge_from_bf(6, 0), meta={"note": "0"}),
        E6Token(t=4, bits6=merge_from_bf(7, 0), meta={"note": "1"}),
        E6Token(t=5, bits6=merge_from_bf(4, 0), meta={"note": "["}),
        E6Token(t=6, bits6=merge_from_bf(5, 0), meta={"note": "]"}),
    ]

    program = codec.tokens_to_etp_program(toks)
    out = run_etp_with_ledger(program, max_steps=200, envelope=RelativityEnvelope(enabled=True, max_delta_component=0.95))
    print("ETP program:", program)
    print("Summary:", json.dumps(out["summary"], indent=2))
    print("Ledger rows:", len(out["ledger"]))
    print("First 2 rows:\n", json.dumps(out["ledger"][:2], indent=2))

# --- function: check_envelope ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def check_envelope(prev_comps: Optional[List[float]], comps: List[float], mean_mass: float,
                   env: RelativityEnvelope) -> Tuple[bool, float, str]:
    if not env.enabled:
        return True, 0.0, "disabled"
    if prev_comps is None:
        ok = (mean_mass < 1.0) if env.require_mass_lt_1 else True
        return ok, 0.0, "init"
    delta = max(abs(a - b) for a, b in zip(prev_comps, comps))
    if env.require_mass_lt_1 and mean_mass >= 1.0:
        return False, delta, "mass>=1 (illegal closure overflow)"
    if delta > env.max_delta_component:
        return False, delta, f"delta>{env.max_delta_component:.3f}"
    return True, delta, "ok"

# --- function: collect_grains ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def collect_grains(eco: TarpitEcology) -> List[Any]:
    # eco.field.grains maps pos->List[Grain]
    out: List[Any] = []
    for gs in eco.field.grains.values():
        out.extend(gs)
    return out

# --- function: count_dusts_and_triads ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def count_dusts_and_triads(eco: TarpitEcology) -> Tuple[int, int]:
    dusts = 0
    triads = 0
    for c in eco.field.composites:
        if isinstance(c, Dust):
            dusts += 1
        elif isinstance(c, Triad):
            triads += 1
    return dusts, triads

# --- function: gram_effective_dim ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def gram_effective_dim(grain_vectors: List[np.ndarray], take: int = 10) -> Tuple[int, List[float]]:
    vectors = [v for v in grain_vectors if v is not None]
    if len(vectors) < 2:
        return len(vectors), [0.0]
    V = np.array(vectors[:take], dtype=float)
    G = V @ V.T
    ev = sorted(np.linalg.eigvalsh(G).tolist(), reverse=True)
    eff = sum(1 for x in ev if x > 1e-6)
    return eff, ev[:5]

# --- function: merge_from_bf ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def merge_from_bf(bf0: int, bf1: int) -> int:
    for d in (bf0, bf1):
        if not (0 <= d <= 7):
            raise ValueError("BF oct digits must be in [0,7]")
    return (bf0 << 3) | bf1

# --- function: orthonormal_basis_from_seed ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def orthonormal_basis_from_seed(seed: int, d: int = 8) -> np.ndarray:
    rng = np.random.default_rng(seed)
    A = rng.normal(size=(d, d))
    Q, _ = np.linalg.qr(A)
    return Q

# --- function: proto_wall10 ---
# composed_from=24 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def proto_wall10(grains: List[Any], dust_count: int) -> str:
    """
    Mirror WallEmitter.emit_output's digit logic without mutating the wall emitter:
      digit_i = int(residual_i * 10) % 10
    """
    residuals = [float(getattr(g, "mass", 0.0)) for g in grains]
    digits: List[int] = []
    for r in residuals[:5]:
        digits.append(int(r * 10) % 10)
    while len(digits) < 3:
        digits.append(0)
    return f"{dust_count}.{''.join(str(d) for d in digits)}"

# --- function: run_etp_with_ledger ---
# composed_from=26 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v7.py
def run_etp_with_ledger(program: str,
                        *,
                        dimension: int = 8,
                        max_steps: int = 10_000,
                        gauge_seed: Optional[int] = None,
                        envelope: Optional[RelativityEnvelope] = None,
                        mirror_policy: str = "pole",
                        force_mirror_on_error: bool = False,
                        stop_after_steps: Optional[int] = None) -> Dict[str, Any]:
    """
    Execute ETP program stepwise, emitting a per-step ledger.

    Returns a dict with:
      - summary (final wall, halted, steps, lattice, etc.)
      - ledger (list of per-step rows)
    """
    if envelope is None:
        envelope = RelativityEnvelope(enabled=False)

    if gauge_seed is None:
        gauge_seed = seed_from_program(program, dimension)
    B = orthonormal_basis_from_seed(gauge_seed, 8)

    # Pin the ecology RNG to gauge_seed so the entire run is deterministic
    # per program (otherwise eco._rng draws from system entropy and consecutive
    # runs of the same program produce different wall10 / torus8 digests).
    eco = TarpitEcology(dimension=dimension, max_steps=max_steps, seed=gauge_seed)
    eco.load_program(program)

    ledger: List[Dict[str, Any]] = []
    prev_comps: Optional[List[float]] = None

    steps = 0
    while True:
        if stop_after_steps is not None and steps >= stop_after_steps:
            break

        ip_before = eco.instruction_pointer
        instr = eco.program[ip_before] if ip_before < len(eco.program) else "<EOF>"
        cont = eco.step()
        ip_after = eco.instruction_pointer
        steps += 1

        grains = collect_grains(eco)
        dusts, triads = count_dusts_and_triads(eco)

        # torus chart
        v = state_vector_for_torus(eco)
        comps, torus8 = torus_components_and_digits(v, B)
        mirror_v, mirror_meta = mirror_vector_for_torus(
            eco,
            v,
            policy=mirror_policy,
            force_on_error=bool(force_mirror_on_error),
        )
        mcomps, torus8_mirror = torus_components_and_digits(mirror_v, B)


        # basic observables
        entropy = eco.get_statistics().get("field_entropy", 0.0)
        mean_mass = float(np.mean([getattr(g, "mass", 0.0) for g in grains])) if grains else 0.0
        dr = eco.field.compute_digital_root()

        # gram fingerprint (effective dim + spectrum)
        vecs = [g.extent.vector for g in grains if getattr(g, "extent", None) is not None and g.extent.vector is not None]
        eff_dim, gram5 = gram_effective_dim(vecs)

        # proto-wall base10
        wall10 = proto_wall10(grains, dusts)

        ok, delta, env_reason = check_envelope(prev_comps, comps, mean_mass, envelope)
        prev_comps = comps

        ledger.append({
            "step": steps,
            "ip_before": ip_before,
            "ip_after": ip_after,
            "instr": instr,
            "ptr": eco.field.pointer,
            "halted_now": (not cont),
            "n_grains": len(grains),
            "dusts": dusts,
            "triads": triads,
            "entropy": float(entropy),
            "mean_mass": mean_mass,
            "digital_root": dr,
            "effective_dim": eff_dim,
            "gram5": gram5,
            "wall10": wall10,
            "torus8": torus8,
            "torus8_mirror": torus8_mirror,
            "n_error_walls": len(getattr(eco.result, "error_walls", []) or []),
            "last_error_class": mirror_meta.get("last_error_class"),
            "last_error_mirror_candidate": mirror_meta.get("last_error_mirror_candidate"),
            "mirror_used": mirror_meta.get("mirror_used"),
            "mirror_source": mirror_meta.get("mirror_source"),
            "envelope_ok": bool(ok),
            "envelope_delta": float(delta),
            "envelope_reason": env_reason,
        })

        if not cont:
            break

    # finalize (stepwise mode doesn't auto-finalize in this ETP build)
    eco._finalize()

    res = eco.result
    lattice = eco.infer_emergent_lattice()
    wall_serial = res.output_walls[0].serialize() if res.output_walls else "0.000"
    wall_score = res.output_walls[0].compute_mass_score() if res.output_walls else 0.0

    summary = {
        "dimension": dimension,
        "max_steps": max_steps,
        "gauge_seed": gauge_seed,
        "program_len": len(program),
        "halted": bool(res.success),
        "steps_executed": int(res.steps_executed),
        "bonds_formed": int(res.bonds_formed),
        "mirrors_applied": int(res.mirrors_applied),
        "final_mass": float(res.final_mass),
        "final_digital_root": int(res.final_digital_root),
        "lattice": lattice.get("inferred_lattice"),
        "wall_serial": wall_serial,
        "wall_score": float(wall_score),
        "n_output_walls": len(res.output_walls),
        "n_error_walls": len(res.error_walls),
    }
    return {"summary": summary, "ledger": ledger}

# --- function: seed_from_program ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def seed_from_program(program: str, dimension: int) -> int:
    h = hashlib.sha256(f"{dimension}|{program}".encode("utf-8")).hexdigest()
    return int(h[:8], 16)

# --- function: split_bc_quads ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def split_bc_quads(bits6: int) -> Tuple[int, int, int]:
    """3 base-4 digits (2 bits each)."""
    return ((bits6 >> 4) & 0b11, (bits6 >> 2) & 0b11, bits6 & 0b11)

# --- function: split_bf_octs ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def split_bf_octs(bits6: int) -> Tuple[int, int]:
    """2 base-8 digits (3 bits each)."""
    return ((bits6 >> 3) & 0b111, bits6 & 0b111)

# --- function: state_vector_for_torus ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def state_vector_for_torus(eco: TarpitEcology) -> np.ndarray:
    # Prefer grains at current pointer position; fall back to all grains.
    gs = eco.field.grains.get(eco.field.pointer, [])
    if gs:
        vecs = [g.extent.vector for g in gs if getattr(g, "extent", None) is not None and g.extent.vector is not None]
    else:
        allg = collect_grains(eco)
        vecs = [g.extent.vector for g in allg if getattr(g, "extent", None) is not None and g.extent.vector is not None]
    if not vecs:
        return np.zeros(8, dtype=float)
    M = np.array(vecs, dtype=float)
    return M.mean(axis=0)

# --- function: torus_components_and_digits ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def torus_components_and_digits(v: np.ndarray, B: np.ndarray) -> Tuple[List[float], List[int]]:
    """
    Map v ∈ R^8 to torus components [cosθ0,sinθ0,...,cosθ3,sinθ3] and quantize each
    component into an oct digit (0..7).

    θi derived from paired coordinates after a seeded orthonormal change-of-basis:
      u = v B
      θi = atan2(u[2i+1], u[2i])
    """
    if v.shape != (8,):
        v = v.reshape(8,)
    u = v @ B
    comps: List[float] = []
    for i in range(0, 8, 2):
        theta = math.atan2(float(u[i + 1]), float(u[i]))
        comps.extend([math.cos(theta), math.sin(theta)])
    digits: List[int] = []
    for c in comps:
        # map [-1,1] -> [0,1] -> [0..7]
        q = int(math.floor(((c + 1.0) / 2.0) * 8.0))
        if q < 0:
            q = 0
        if q > 7:
            q = 7
        digits.append(q)
    return comps, digits

# --- function: write_jsonl ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def write_jsonl(rows: List[Dict[str, Any]], path: str) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

# --- function: _parse_wall10_digits ---
# composed_from=34 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v3.py
def _parse_wall10_digits(wall10: str) -> List[int]:
    """
    Parse 'X.ddd...' into a list of base-10 digits after the dot.
    Returns [] if not parseable.
    """
    if not wall10 or "." not in wall10:
        return []
    try:
        _, tail = wall10.split(".", 1)
        return [int(ch) for ch in tail.strip() if ch.isdigit()]
    except Exception:
        return []

# --- function: derive_return_tokens ---
# composed_from=32 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v3.py
def derive_return_tokens(final_row: Dict[str, Any],
                         *,
                         mode: str = "torus-mirror",
                         length: int = 8) -> List[E6Token]:
    """
    Deterministically derive a *return* action stream (E6 tokens) from the final
    observed state of a run.

    This is the minimal implementation of:
      - "return actions can be encoded in a second 8D block"
      - "walls can bounce multiple times"

    Inputs
    ------
    final_row: last ledger row from run_etp_with_ledger()

    Modes
    -----
    - torus-mirror:
        op  = torus8_mirror[i]
        rep = torus8[i]
    - wall10:
        op  = wall_digits[i] mod 8
        rep = torus8_mirror[i]
    - hybrid:
        op  = (torus8_mirror[i] XOR wall_digits[i]) mod 8
        rep = (torus8[i] + wall_digits[i]) mod 8

    Output
    ------
    List[E6Token] of length `length`, with t=0..length-1.
    """
    mode = (mode or "torus-mirror").lower().strip()
    torus = list(final_row.get("torus8", [])) or [0] * 8
    mirror = list(final_row.get("torus8_mirror", [])) or [0] * 8
    wall_digits = _parse_wall10_digits(str(final_row.get("wall10", ""))) or [0, 0, 0]

    toks: List[E6Token] = []
    n = max(1, int(length))
    for i in range(n):
        a = torus[i % len(torus)]
        b = mirror[i % len(mirror)]
        w = wall_digits[i % len(wall_digits)]

        if mode == "torus-mirror":
            op = int(b) & 7
            rep = int(a) & 7
        elif mode == "wall10":
            op = int(w) % 8
            rep = int(b) & 7
        elif mode == "hybrid":
            op = (int(b) ^ int(w)) % 8
            rep = (int(a) + int(w)) % 8
        else:
            raise ValueError(f"Unknown bounce mode: {mode!r}")

        toks.append(E6Token(t=i, bits6=merge_from_bf(op, rep), meta={
            "derived_from": "final_row",
            "mode": mode,
            "i": i,
            "op": op,
            "rep": rep + 1,  # repeats in ETP program
        }))
    return toks

# --- function: run_bounce_series ---
# composed_from=26 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v7.py
def run_bounce_series(program: str,
                      *,
                      bounces: int = 1,
                      bounce_mode: str = "torus-mirror",
                      bounce_len: int = 8,
                      bounce_from: str = "final",
                      keep_gauge: bool = True,
                      dimension: int = 8,
                      max_steps: int = 10_000,
                      mirror_policy: str = "pole",
                      force_mirror_on_error: bool = False,
                      envelope: Optional[RelativityEnvelope] = None) -> Dict[str, Any]:
    """
    Run an initial program, then repeatedly derive a return-program from the
    previous run's final state, for `bounces` reflections.

    Interpretation:
      - bounces=0 -> just run the initial program
      - bounces=1 -> initial run, then 1 derived return run
      - bounces=k -> initial run + k derived return runs

    keep_gauge=True keeps the torus basis seed fixed to the initial program,
    so torus digits are comparable across bounces ("same space").
    """
    codec = E6Codec()
    bounces = max(0, int(bounces))

    if envelope is None:
        envelope = RelativityEnvelope(enabled=False)

    gauge_seed = seed_from_program(program, dimension) if keep_gauge else None

    runs: List[Dict[str, Any]] = []
    cur_program = program

    for r in range(bounces + 1):
        out = run_etp_with_ledger(
            cur_program,
            dimension=dimension,
            max_steps=max_steps,
            gauge_seed=gauge_seed,
            envelope=envelope,
            mirror_policy=mirror_policy,
            force_mirror_on_error=force_mirror_on_error,
        )

        final_row = select_bounce_source_row(out["ledger"], bounce_from=bounce_from) if out["ledger"] else {}
        run_entry: Dict[str, Any] = {
            "run_index": r,
            "input_program": cur_program,
            "summary": out["summary"],
            "final_row": {
                "wall10": final_row.get("wall10"),
                "torus8": final_row.get("torus8"),
                "torus8_mirror": final_row.get("torus8_mirror"),
                "effective_dim": final_row.get("effective_dim"),
                "gram5": final_row.get("gram5"),
                "envelope_ok": final_row.get("envelope_ok"),
                "envelope_delta": final_row.get("envelope_delta"),
            },
            "ledger": out["ledger"],
        }

        if r < bounces and out["ledger"]:
            toks = derive_return_tokens(final_row, mode=bounce_mode, length=bounce_len)
            next_program = codec.tokens_to_etp_program(toks, use_repeats=True)
            run_entry["derived_return_program"] = next_program
            run_entry["derived_return_tokens"] = [t.to_dict() for t in toks]
            cur_program = next_program

        runs.append(run_entry)

    return {
        "initial_program": program,
        "bounces": bounces,
        "bounce_mode": bounce_mode,
        "bounce_len": bounce_len,
        "bounce_from": bounce_from,
        "keep_gauge": keep_gauge,
        "mirror_policy": mirror_policy,
        "force_mirror_on_error": bool(force_mirror_on_error),
        "dimension": dimension,
        "max_steps": max_steps,
        "runs": runs,
    }

# --- function: select_bounce_source_row ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v8.py
def select_bounce_source_row(ledger: List[Dict[str, Any]], *, bounce_from: str = "final") -> Dict[str, Any]:
    """
    Select which ledger row to use as the "bounce surface".

    bounce_from formats:
      - "final"                 -> last row
      - "frac:0.50"             -> row at fraction of ledger length
      - "step:123"              -> row whose 'step' equals 123 (or nearest)
      - "events"                -> best detected event row (or final if none)
      - "events:first|last|k"   -> choose among detected events (k = 0-based index)

    This supports bounces off intermediate "wall events" without manual step selection.
    """
    if not ledger:
        return {}

    s = (bounce_from or "final").strip().lower()

    if s == "final":
        return ledger[-1]

    if s.startswith("frac:"):
        try:
            frac = float(s.split(":", 1)[1])
            frac = max(0.0, min(1.0, frac))
            idx = int(round(frac * (len(ledger) - 1)))
            return ledger[idx]
        except Exception:
            return ledger[-1]

    if s.startswith("step:"):
        try:
            target = int(s.split(":", 1)[1])
            best = min(ledger, key=lambda r: abs(int(r.get("step", 0)) - target))
            return best
        except Exception:
            return ledger[-1]

    if s.startswith("events"):
        ev = detect_bounce_events(ledger)
        if not ev:
            return ledger[-1]
        if s == "events":
            return ev[0]
        if ":" in s:
            tail = s.split(":", 1)[1].strip()
            if tail == "first":
                return ev[0]
            if tail == "last":
                return ev[-1]
            try:
                k = int(tail)
                if 0 <= k < len(ev):
                    return ev[k]
            except Exception:
                pass
        return ev[0]

    return ledger[-1]

# --- function: write_bounce_jsonl ---
# composed_from=32 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v3.py
def write_bounce_jsonl(bounce_out: Dict[str, Any], path: str) -> None:
    """
    Flatten a bounce-series output into JSONL rows with run_index and step.
    """
    rows: List[Dict[str, Any]] = []
    for run in bounce_out.get("runs", []):
        r = int(run.get("run_index", 0))
        for row in run.get("ledger", []):
            rr = dict(row)
            rr["run_index"] = r
            rows.append(rr)
    write_jsonl(rows, path)

# --- function: popcount ---
# composed_from=30 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge.py
def popcount(x: int) -> int:
    return int(bin(x).count("1"))

# --- function: mirror_vector_for_torus ---
# composed_from=14 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v81.py
def mirror_vector_for_torus(eco: TarpitEcology,
                            base_v: np.ndarray,
                            *,
                            policy: str = "pole",
                            force_on_error: bool = False) -> Tuple[np.ndarray, Dict[str, Any]]:
    """
    Produce the "mirror lane" state vector used for torus8_mirror.

    Policies:
      - "pole":           mirror_v = -base_v
      - "mirroroperator": if any error wall exists, apply MirrorOperator to obtain a mediator vector;
                            else fall back to pole inversion.
      - "auto":           apply MirrorOperator only when the last error wall is mirror_candidate,
                            unless force_on_error=True.

    KNOWN LIMITATION (v8):
      MirrorOperator activation is gated exclusively on ErrorWall presence.
      Programs that halt cleanly (no errors) always receive pole inversion
      regardless of policy. To enable output-wall reflection, implement
      SurrogateErrorWall (derive ErrorWall from OutputWall signature) or
      OutputMirrorOperator (acts on OutputWall directly). See spec v8 §"next gap".

    Returns:
      (mirror_v, meta) where meta includes:
        - mirror_used: bool
        - mirror_source: "pole" | "mirroroperator"
        - last_error_class: str|None
        - last_error_mirror_candidate: bool
    """
    p = (policy or "pole").strip().lower()
    errors = list(getattr(eco.result, "error_walls", []) or [])
    last = errors[-1] if errors else None

    meta = {
        "mirror_used": False,
        "mirror_source": "pole",
        "last_error_class": getattr(getattr(last, "error_class", None), "value", None) if last else None,
        "last_error_mirror_candidate": bool(getattr(last, "mirror_candidate", False)) if last else False,
    }

    if p == "pole":
        return -base_v, meta

    if p not in ("mirroroperator", "auto"):
        raise ValueError(f"Unknown mirror policy: {policy!r}")

    if not last:
        return -base_v, meta

    should_apply = (p == "mirroroperator") or meta["last_error_mirror_candidate"] or bool(force_on_error)
    if not should_apply:
        return -base_v, meta

    grains = list(getattr(last, "reproducer_grains", []) or [])
    if not grains:
        gs = eco.field.grains.get(eco.field.pointer, [])
        grains = list(gs) if gs else collect_grains(eco)

    mo = MirrorOperator()
    mirrored = mo.apply_mirror(last, grains, time=int(getattr(eco, "step_count", 0) or 0))

    if mirrored and getattr(mirrored, "new_mediator", None) is not None:
        mv = mirrored.new_mediator.extent.vector
        meta["mirror_used"] = True
        meta["mirror_source"] = "mirroroperator"
        return np.array(mv, dtype=float), meta

    if mirrored and getattr(mirrored, "counter_grains", None):
        vecs = [g.extent.vector for g in mirrored.counter_grains
                if getattr(g, "extent", None) is not None and g.extent.vector is not None]
        if vecs:
            avg = np.mean(np.array(vecs, dtype=float), axis=0)
            # Guard: if counter-grain mean collapses to near-zero, fall back to pole
            if np.linalg.norm(avg) > 1e-10:
                meta["mirror_used"] = True
                meta["mirror_source"] = "mirroroperator"
                return avg, meta

    return -base_v, meta

# --- function: _edge_priority ---
# composed_from=14 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v8.py
def _edge_priority(surface_row: Dict[str, Any]) -> Tuple[int, int, int]:
    """
    Lower tuple is higher priority (stable ordering).
    We want:
      - higher event score first
      - earlier steps first (tie-break)
      - mirror-used True first (tie-break)
    """
    ev = int(surface_row.get("_event_score", 0))
    step = int(surface_row.get("step", 0))
    mirror_used = 0 if bool(surface_row.get("mirror_used", False)) else 1
    return (-ev, step, mirror_used)

# --- function: _run_score ---
# composed_from=22 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v8.py
def _run_score(summary: Dict[str, Any]) -> float:
    """
    Deterministic heuristic score for selecting "best" nodes.

    Higher is better.
    """
    s = 0.0
    if summary.get("halted"):
        s += 1.0
    if int(summary.get("n_error_walls", 0)) == 0:
        s += 1.0
    # Prefer "cleaner" walls (lower score indicates less residual)
    try:
        ws = float(summary.get("wall_score", 0.0))
        s += max(0.0, 1.0 - ws)
    except Exception:
        pass
    # Slight preference for more structured lattice, if present
    if str(summary.get("lattice")) == "2D_Grid":
        s += 0.25
    return float(s)

# --- function: detect_bounce_events ---
# composed_from=12 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v8.py
def detect_bounce_events(ledger: List[Dict[str, Any]],
                         *,
                         max_events: int = 8,
                         min_step_gap: int = 3) -> List[Dict[str, Any]]:
    """
    Detect "bounce surfaces" from a single run's ledger.

    Events are deterministic, derived from deltas in observables:
      - wall10 changed (proto-wall digits changed)
      - error wall count increased
      - envelope_ok became False
      - effective_dim changed

    Returns a *subset of ledger rows* (the surface rows), ordered by:
      (event_score desc, step asc), with a min step gap to avoid clustering.
    """
    if not ledger:
        return []

    events: List[Tuple[int, int, Dict[str, Any]]] = []  # (score, step, row)

    prev = ledger[0]
    for row in ledger[1:]:
        score = 0
        if str(row.get("wall10")) != str(prev.get("wall10")):
            score += 1
        if int(row.get("n_error_walls", 0)) > int(prev.get("n_error_walls", 0)):
            score += 2
        if (prev.get("envelope_ok", True) is True) and (row.get("envelope_ok", True) is False):
            score += 2
        if int(row.get("effective_dim", 0)) != int(prev.get("effective_dim", 0)):
            score += 1

        if score > 0:
            step = int(row.get("step", 0))
            r2 = dict(row)
            r2["_event_score"] = score
            events.append((score, step, r2))
        prev = row

    # Sort: strongest first, stable by step
    events.sort(key=lambda t: (-t[0], t[1]))

    picked: List[Dict[str, Any]] = []
    last_step = -10**9
    for score, step, row in events:
        if len(picked) >= int(max_events):
            break
        if step - last_step < int(min_step_gap):
            continue
        picked.append(row)
        last_step = step

    # If nothing triggered, return []
    return picked

# --- function: run_bounce_graph ---
# composed_from=14 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v81.py
def run_bounce_graph(program: str,
                     *,
                     depth: int = 3,
                     branch: int = 3,
                     max_nodes: int = 25,
                     surfaces: Optional[List[str]] = None,
                     bounce_mode: str = "torus-mirror",
                     bounce_len: int = 8,
                     keep_gauge: bool = True,
                     dimension: int = 8,
                     max_steps: int = 10_000,
                     mirror_policy: str = "pole",
                     force_mirror_on_error: bool = False,
                     envelope: Optional[RelativityEnvelope] = None,
                     store_ledgers: bool = True) -> Dict[str, Any]:
    """
    Branching traversal: a node is a program; edges are derived return programs computed
    from one of several surface rows ("final", "events", "frac", etc.).

    Deterministic constraints:
      - stable surface ordering (_edge_priority)
      - visited-set on program strings
      - bounded branch factor and max_nodes
    """
    codec = E6Codec()
    if envelope is None:
        envelope = RelativityEnvelope(enabled=False)

    if surfaces is None:
        surfaces = ["final", "events"]

    depth = max(0, int(depth))
    branch = max(1, int(branch))
    max_nodes = max(1, int(max_nodes))

    gauge_seed = seed_from_program(program, dimension) if keep_gauge else None

    nodes: List[Dict[str, Any]] = []
    edges: List[Dict[str, Any]] = []
    visited = set()

    # Node 0
    queue: List[Tuple[int, int]] = []  # (node_id, depth)
    def add_node(prog: str, parent: Optional[int], via: Optional[Dict[str, Any]], d: int) -> int:
        out = run_etp_with_ledger(
            prog,
            dimension=dimension,
            max_steps=max_steps,
            gauge_seed=gauge_seed,
            envelope=envelope,
            mirror_policy=mirror_policy,
            force_mirror_on_error=force_mirror_on_error,
        )
        node_id = len(nodes)
        node = {
            "node_id": node_id,
            "depth": d,
            "program": prog,
            "summary": out["summary"],
        }
        # Always store ledger during traversal (needed for surface computation);
        # strip from output at the end if store_ledgers=False
        node["ledger"] = out["ledger"]
        # record the best surface row for compact summary
        if out["ledger"]:
            best_row = select_bounce_source_row(out["ledger"], bounce_from="events") if "events" in surfaces else out["ledger"][-1]
            node["surface_row"] = {k: best_row.get(k) for k in (
                "step", "wall10", "torus8", "torus8_mirror",
                "n_error_walls", "last_error_class",
                "mirror_used", "mirror_source",
                "envelope_ok", "envelope_delta",
                "effective_dim", "gram5",
            )}
        node["score"] = _run_score(out["summary"])
        nodes.append(node)

        if parent is not None and via is not None:
            edges.append({
                "src": parent,
                "dst": node_id,
                **via,
            })
        queue.append((node_id, d))
        return node_id

    add_node(program, parent=None, via=None, d=0)
    visited.add(program)

    # BFS by depth
    qi = 0
    while qi < len(queue):
        node_id, d = queue[qi]
        qi += 1
        if d >= depth:
            continue
        if len(nodes) >= max_nodes:
            break

        ledger = nodes[node_id].get("ledger", [])
        if not ledger:
            continue

        # candidate surfaces
        surf_rows = select_surface_rows_for_graph(ledger, surfaces=surfaces, max_events=8)
        # stable ordering
        surf_rows.sort(key=_edge_priority)

        # generate edges
        out_edges = 0
        for sr in surf_rows:
            if out_edges >= branch:
                break
            toks = derive_return_tokens(sr, mode=bounce_mode, length=bounce_len)
            next_prog = codec.tokens_to_etp_program(toks, use_repeats=True)
            if next_prog in visited:
                continue
            if len(nodes) >= max_nodes:
                break

            via = {
                "surface_kind": sr.get("_surface_kind", "unknown"),
                "surface_step": int(sr.get("step", 0)),
                "bounce_mode": bounce_mode,
                "bounce_len": int(bounce_len),
                "derived_return_tokens": [t.to_dict() for t in toks],
            }
            add_node(next_prog, parent=node_id, via=via, d=d + 1)
            visited.add(next_prog)
            out_edges += 1

    # choose best node + reconstruct best path via parent edges
    # Secondary key: lower node_id wins ties (earlier = more ancestral)
    best = max(nodes, key=lambda n: (float(n.get("score", 0.0)), -int(n["node_id"])))
    best_id = int(best["node_id"])

    # Build parent map from edges (first edge to a dst is its parent)
    parent_of = {}
    edge_of = {}
    for e in edges:
        dst = int(e["dst"])
        if dst not in parent_of:
            parent_of[dst] = int(e["src"])
            edge_of[dst] = e

    path = [best_id]
    cur = best_id
    while cur in parent_of:
        cur = parent_of[cur]
        path.append(cur)
    path.reverse()

    # Strip ledgers from output if not requested (they were needed for traversal)
    if not store_ledgers:
        for n in nodes:
            n.pop("ledger", None)

    return {
        "meta": {
            "initial_program": program,
            "depth": depth,
            "branch": branch,
            "max_nodes": max_nodes,
            "surfaces": surfaces,
            "bounce_mode": bounce_mode,
            "bounce_len": bounce_len,
            "keep_gauge": keep_gauge,
            "mirror_policy": mirror_policy,
            "force_mirror_on_error": bool(force_mirror_on_error),
            "dimension": dimension,
            "max_steps": max_steps,
        },
        "nodes": nodes,
        "edges": edges,
        "best_node_id": best_id,
        "best_path": path,
    }

# --- function: select_surface_rows_for_graph ---
# composed_from=14 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\e6_tarpit_bridge_v8.py
def select_surface_rows_for_graph(ledger: List[Dict[str, Any]],
                                  *,
                                  surfaces: List[str],
                                  max_events: int = 8) -> List[Dict[str, Any]]:
    """
    Return a list of candidate surface rows for graph branching.

    surfaces can include: "final", "events", "frac"
      - final  -> ledger[-1]
      - events -> detect_bounce_events(...), up to max_events
      - frac   -> rows at 0.25, 0.50, 0.75

    Each returned row has a stable label in row["_surface_kind"].
    """
    if not ledger:
        return []

    out: List[Dict[str, Any]] = []
    want = {s.strip().lower() for s in (surfaces or ["final"])}

    def add_row(row: Dict[str, Any], kind: str):
        r2 = dict(row)
        r2["_surface_kind"] = kind
        out.append(r2)

    if "final" in want:
        add_row(ledger[-1], "final")

    if "frac" in want and len(ledger) >= 4:
        for f in (0.25, 0.50, 0.75):
            idx = int(round(f * (len(ledger) - 1)))
            add_row(ledger[idx], f"frac:{f:.2f}")

    if "events" in want:
        ev = detect_bounce_events(ledger, max_events=max_events)
        for i, r in enumerate(ev):
            add_row(r, f"event:{i}")

    # Deduplicate by (step, kind) while preserving order
    seen = set()
    dedup: List[Dict[str, Any]] = []
    for r in out:
        key = (int(r.get("step", -1)), str(r.get("_surface_kind")))
        if key in seen:
            continue
        seen.add(key)
        dedup.append(r)
    return dedup
    if s.startswith("frac:"):
        try:
            frac = float(s.split(":", 1)[1])
            frac = max(0.0, min(1.0, frac))
            idx = int(round(frac * (len(ledger) - 1)))
            return ledger[idx]
        except Exception:
            return ledger[-1]

    if s.startswith("step:"):
        try:
            target = int(s.split(":", 1)[1])
            # find closest by absolute difference
            best = min(ledger, key=lambda r: abs(int(r.get("step", 0)) - target))
            return best
        except Exception:
            return ledger[-1]

    # Unknown -> fall back
    return ledger[-1]

# --- function: demo_basic_bitchanger ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_basic_bitchanger():
    """Demonstrate basic BitChanger operations."""
    print("=" * 60)
    print("DEMO 1: Basic BitChanger Operations")
    print("=" * 60)
    
    ecology = TarpitEcology(dimension=8, layer=0)
    
    # Simple program: flip and move right twice
    program = "}}"
    
    print(f"Program: {program}")
    print("Instruction: } = flip current bit and move right")
    
    result = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps executed: {result.steps_executed}")
    print(f"  Final digital root: {result.final_digital_root}")
    print(f"  Final mass: {result.final_mass:.4f}")
    print(f"  Success: {result.success}")
    
    if result.output_walls:
        print(f"\n  Output Wall: {result.output_walls[0].serialize()}")
    
    stats = ecology.get_statistics()
    print(f"  Grains created: {stats['grains']}")

# --- function: demo_basic_tokens ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_basic_tokens():
    """Demonstrate basic token operations."""
    print("=" * 70)
    print("SEMANTIC RIBBON ECOLOGY - DEMO 1: Basic Token Operations")
    print("=" * 70)
    
    # Create vocabulary with semantic primitives
    vocab = TokenVocabulary.create_basic_vocabulary(dimension=64)
    print(f"\nVocabulary size: {len(vocab.tokens)}")
    print(f"Tokens: {list(vocab.tokens.keys())}")
    
    # Create ecology
    ecology = SemanticEcology(vocabulary=vocab)
    
    # Program: compose black with bird
    # } = compose with right neighbor
    program = "black } bird"
    
    print(f"\nProgram: {program}")
    print("Operation: } = compose current token with right neighbor")
    
    wall = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps: {ecology.step_count}")
    print(f"  Wall: {wall.serialize()}")
    
    stats = ecology.bond_engine.get_composition_statistics()
    print(f"\n  Compositions: {stats['total_compositions']}")
    print(f"  Novel: {stats['novel_compositions']}")
    print(f"  Avg strength: {stats['average_strength']:.3f}")

# --- function: demo_chained_composition ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_chained_composition():
    """Demonstrate chained compositions."""
    print("\n" + "=" * 70)
    print("DEMO 4: Chained Semantic Compositions")
    print("=" * 70)
    
    vocab = TokenVocabulary.create_basic_vocabulary(dimension=64)
    ecology = SemanticEcology(vocabulary=vocab)
    
    # Chain: black } bird } fly
    # Means: (black + bird) then result + fly
    program = "black } bird } fly"
    
    print(f"\nProgram: {program}")
    print("This chains compositions: (black + bird) + fly")
    
    wall = ecology.run(program)
    
    print(f"\nComposition chain:")
    for i, dust in enumerate(ecology.bond_engine.dust_history):
        print(f"  Step {i+1}: {dust}")
    
    print(f"\nFinal tape state:")
    print(f"  {ecology.tape.to_string()}")

# --- function: demo_emergent_lattice ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_emergent_lattice():
    """Demonstrate emergent lattice inference."""
    print("\n" + "=" * 60)
    print("DEMO 5: Emergent Lattice Inference")
    print("=" * 60)
    
    ecology = TarpitEcology(dimension=8, layer=0)
    
    # Program designed to create 2D structures through orthogonal bonds
    # Alternating 0 and 1 should create dimensional emergence
    program = "01010101" * 4
    
    print(f"Program: {program}")
    print("Pattern: alternating bond/nest should create 2D structures")
    
    result = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps: {result.steps_executed}")
    print(f"  Bonds: {result.bonds_formed}")
    print(f"  Dust structures: {len(result.dusts)}")
    
    # Infer emergent lattice
    lattice_info = ecology.infer_emergent_lattice()
    
    print(f"\n  Emergent Lattice Analysis:")
    print(f"    Inferred lattice: {lattice_info['inferred_lattice']}")
    print(f"    Bond statistics: {lattice_info['bond_stats']}")
    print(f"    Mass distribution: {lattice_info['mass_distribution']}")
    print(f"    Digital root: {lattice_info['digital_root']}")

# --- function: demo_emergent_semantics ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_emergent_semantics():
    """Demonstrate emergent semantic structures."""
    print("\n" + "=" * 70)
    print("DEMO 7: Emergent Semantic Structures")
    print("=" * 70)
    
    vocab = TokenVocabulary.create_basic_vocabulary(dimension=64)
    ecology = SemanticEcology(vocabulary=vocab)
    
    # Complex program generating semantic structure
    program = "black } bird fast } dog red } fish"
    
    print(f"\nProgram: {program}")
    print("Multiple parallel compositions")
    
    wall = ecology.run(program)
    
    stats = ecology.get_statistics()
    print(f"\nEmergent structure:")
    print(f"  Total compositions: {stats['total_compositions']}")
    print(f"  Novel products: {stats['novel_compositions']}")
    print(f"  Semantic coherence: {stats['coherence']:.3f}")
    
    print(f"\nAll compositions:")
    for dust in ecology.bond_engine.dust_history:
        print(f"  {dust.token_a.token} + {dust.token_b.token} "
              f"-> {dust.composite.token}")

# --- function: demo_evolution ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_evolution():
    """Demonstrate program evolution."""
    print("\n" + "=" * 60)
    print("DEMO 6: Program Evolution")
    print("=" * 60)
    
    ecology = TarpitEcology(dimension=8, layer=0, max_steps=100)
    
    # Start with simple program
    seed_program = "0"
    
    print(f"Seed program: {seed_program}")
    print(f"Evolving for 10 iterations...")
    
    results = ecology.evolve(iterations=10, mutation_rate=0.3)
    
    print(f"\nEvolution Results:")
    print(f"{'Gen':<5} {'Program':<20} {'Mass':<10} {'Success':<10}")
    print("-" * 50)
    
    for i, result in enumerate(results):
        prog = result.program[:17] + "..." if len(result.program) > 20 else result.program
        print(f"{i+1:<5} {prog:<20} {result.final_mass:<10.4f} {str(result.success):<10}")
    
    # Show best result
    best = max(results, key=lambda r: r.final_mass if r.success else 0)
    print(f"\nBest program (by mass):")
    print(f"  Program: {best.program}")
    print(f"  Mass: {best.final_mass:.4f}")
    print(f"  Steps: {best.steps_executed}")
    print(f"  Bonds: {best.bonds_formed}")

# --- function: demo_jot_bonding ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_jot_bonding():
    """Demonstrate Jot encoding with bond formation."""
    print("\n" + "=" * 60)
    print("DEMO 2: Jot Encoding and Bond Formation")
    print("=" * 60)
    
    ecology = TarpitEcology(dimension=8, layer=0)
    
    # Jot program: 0 = apply/bond, 1 = nest
    # 010 = bond, nest, bond
    program = "010"
    
    print(f"Program: {program}")
    print("Instruction: 0 = apply(S)(K) = bond with neighbor")
    print("             1 = nest = extend extent vector")
    
    result = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps: {result.steps_executed}")
    print(f"  Bonds formed: {result.bonds_formed}")
    print(f"  Dust structures: {len(result.dusts)}")
    print(f"  Final mass: {result.final_mass:.4f}")
    
    # Show bond statistics
    bond_stats = ecology.bond_engine.get_bond_statistics()
    print(f"\n  Bond Statistics:")
    print(f"    Total bonds: {bond_stats['total_bonds']}")
    print(f"    By type: {bond_stats['by_type']}")
    print(f"    Average mass: {bond_stats['avg_mass']:.4f}")
    print(f"    Avg dimensional demand: {bond_stats['avg_dimensional_demand']:.2f}")

# --- function: demo_jot_semantic ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_jot_semantic():
    """Demonstrate Jot operations on tokens."""
    print("\n" + "=" * 70)
    print("DEMO 6: Jot on Tokens (0=compose, 1=context)")
    print("=" * 70)
    
    vocab = TokenVocabulary.create_basic_vocabulary(dimension=64)
    ecology = SemanticEcology(vocabulary=vocab)
    
    # Jot: 0 = compose, 1 = extend context
    # 010 = compose, context, compose
    program = "black 0 bird 1 0 fly"
    
    print(f"\nProgram: {program}")
    print("0 = compose tokens (APPLY)")
    print("1 = extend context (NEST)")
    
    wall = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps: {ecology.step_count}")
    print(f"  Compositions: {len(ecology.bond_engine.dust_history)}")
    print(f"  Coherence: {wall.coherence_score:.3f}")

# --- function: demo_loops_and_walls ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_loops_and_walls():
    """Demonstrate loops and wall emission."""
    print("\n" + "=" * 60)
    print("DEMO 3: Loops and Wall Emission")
    print("=" * 60)
    
    ecology = TarpitEcology(dimension=8, layer=0)
    
    # Program that creates a grain, then loops while it's 1
    # [}] = while current bit is 1: flip and move right
    program = "}[}]"
    
    print(f"Program: {program}")
    print("Instruction: Create grain, loop while 1: flip & move right")
    
    result = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps: {result.steps_executed}")
    print(f"  Output walls: {len(result.output_walls)}")
    print(f"  Error walls: {len(result.error_walls)}")
    
    if result.output_walls:
        wall = result.output_walls[0]
        print(f"\n  Output Wall Details:")
        print(f"    Serialization: {wall.serialize()}")
        print(f"    Closure count: {wall.closure_count}")
        print(f"    Mass score: {wall.compute_mass_score():.4f}")
        print(f"    Residual digits: {wall.residual_digits}")

# --- function: demo_mirroring ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_mirroring():
    """Demonstrate mirroring for error recovery."""
    print("\n" + "=" * 60)
    print("DEMO 4: Mirroring and Error Recovery")
    print("=" * 60)
    
    ecology = TarpitEcology(dimension=8, layer=0, max_steps=50)
    
    # Complex program that may trigger capacity errors
    # Heavy nesting followed by bonding
    program = "111000" * 5  # Nest 3x, then bond 3x, repeat
    
    print(f"Program: {program[:20]}... (truncated)")
    print("This heavy nesting may trigger capacity constraints")
    
    result = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps: {result.steps_executed}")
    print(f"  Mirrors applied: {result.mirrors_applied}")
    print(f"  Error walls: {len(result.error_walls)}")
    
    if result.error_walls:
        print(f"\n  Error Wall Details:")
        for i, wall in enumerate(result.error_walls[:2]):
            print(f"    Error {i+1}: {wall.error_class.value}")
            print(f"      Suggested actions: {wall.suggested_actions}")
            print(f"      Mirror candidate: {wall.mirror_candidate}")

# --- function: demo_mixed_language ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_mixed_language():
    """Demonstrate mixed BitChanger/Brainfuck/Jot program."""
    print("\n" + "=" * 60)
    print("DEMO 7: Mixed Language Program")
    print("=" * 60)
    
    ecology = TarpitEcology(dimension=8, layer=0)
    
    # Mixed program using all features
    # } = flip & right (BitChanger)
    # > = right (Brainfuck)
    # [ ] = loops
    # 0 1 = Jot apply/nest
    program = "}01}01[}01]"
    
    print(f"Program: {program}")
    print("Mixed: BitChanger (}), Brainfuck (>[]), Jot (01)")
    
    result = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps: {result.steps_executed}")
    print(f"  Digital root: {result.final_digital_root}")
    print(f"  Mass: {result.final_mass:.4f}")
    print(f"  Bonds: {result.bonds_formed}")
    print(f"  Dust: {len(result.dusts)}")
    print(f"  Triads: {len(result.triads)}")
    
    if result.triads:
        print(f"\n  Triad Closures:")
        for triad in result.triads:
            print(f"    {triad}")

# --- function: demo_semantic_composition ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_semantic_composition():
    """Demonstrate semantic composition patterns."""
    print("\n" + "=" * 70)
    print("DEMO 2: Semantic Composition Patterns")
    print("=" * 70)
    
    vocab = TokenVocabulary.create_basic_vocabulary(dimension=64)
    ecology = SemanticEcology(vocabulary=vocab)
    
    # Various composition patterns
    programs = [
        "black } bird",      # Color + animal
        "fast } bird",       # Modifier + animal  
        "bird } fly",        # Animal + action
        "red } fish",        # Color + animal
    ]
    
    print("\nTesting semantic independence (orthogonal compositions):")
    
    for prog in programs:
        ecology.reset()
        wall = ecology.run(prog)
        
        # Get the composition
        if ecology.bond_engine.dust_history:
            dust = ecology.bond_engine.dust_history[-1]
            print(f"\n  {prog:20} -> {dust.composite.token:30} "
                  f"(strength={dust.semantic_strength:.3f}, novel={dust.is_novel})")

# --- function: demo_semantic_loops ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_semantic_loops():
    """Demonstrate semantic loops."""
    print("\n" + "=" * 70)
    print("DEMO 5: Semantic Loops")
    print("=" * 70)
    
    vocab = TokenVocabulary.create_basic_vocabulary(dimension=64)
    ecology = SemanticEcology(vocabulary=vocab, max_steps=50)
    
    # Loop: while token has high mass, keep composing
    # [ } ] means: loop while current token mass >= 0.5
    program = "black [ } ] bird"
    
    print(f"\nProgram: {program}")
    print("Loop: while current token has mass >= 0.5, compose with right")
    
    wall = ecology.run(program)
    
    print(f"\nResult:")
    print(f"  Steps executed: {ecology.step_count}")
    print(f"  Compositions: {len(ecology.bond_engine.dust_history)}")

# --- function: demo_similarity_vs_composition ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_similarity_vs_composition():
    """Show how similarity affects composition."""
    print("\n" + "=" * 70)
    print("DEMO 3: Similarity vs Composition Potential")
    print("=" * 70)
    
    vocab = TokenVocabulary.create_basic_vocabulary(dimension=64)
    
    # Test pairs with different similarities
    pairs = [
        ("black", "white"),  # Similar (both colors)
        ("black", "bird"),   # Different (color vs animal)
        ("bird", "fish"),    # Similar (both animals)
        ("bird", "fly"),     # Related (animal + action)
    ]
    
    print("\nPair analysis:")
    print(f"{'Pair':<20} {'Similarity':<15} {'Can Compose':<15} {'Strength':<10}")
    print("-" * 60)
    
    for t1, t2 in pairs:
        grain1 = vocab.create_grain(t1, 0)
        grain2 = vocab.create_grain(t2, 1)
        
        sim = grain1.similarity(grain2)
        can_comp, strength = grain1.can_form_composite(grain2)
        
        print(f"{t1}+{t2:<13} {sim:>8.3f}        "
              f"{'Yes' if can_comp else 'No':<15} {strength:.3f}")

# --- function: demo_vocabulary_evolution ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\tarpit\cryptography\unified_tarpit.py
def demo_vocabulary_evolution():
    """Show how vocabulary evolves through composition."""
    print("\n" + "=" * 70)
    print("DEMO 8: Vocabulary Evolution")
    print("=" * 70)
    
    vocab = TokenVocabulary.create_basic_vocabulary(dimension=64)
    initial_size = len(vocab.tokens)
    
    print(f"\nInitial vocabulary size: {initial_size}")
    
    # Run multiple composition programs
    programs = [
        "black } bird",
        "fast } bird", 
        "bird } fly",
        "black } dog",
    ]
    
    novel_products = set()
    
    for prog in programs:
        ecology = SemanticEcology(vocabulary=vocab)
        wall = ecology.run(prog)
        
        for dust in ecology.bond_engine.dust_history:
            if dust.is_novel:
                novel_products.add(dust.composite.token)
    
    print(f"\nNovel compositions discovered:")
    for product in sorted(novel_products):
        print(f"  {product}")
    
    print(f"\nVocabulary growth: {initial_size} -> {initial_size + len(novel_products)}")
    print(f"Expansion ratio: {len(novel_products)/initial_size:.2f}x")
