"""
Composed canonical: Receipt

Family: receipt
Decision: batch=3 id=201
Composition: method-union of 15 variants → 41 methods (7 conflicts resolved), 81 attrs

Auto-generated by place_canonicals.py from the atomic decision queue.
Do not edit by hand — re-run the merger to refresh.
"""
from __future__ import annotations

class Receipt:
    """4-bit commit receipt with full provenance"""
    claim: str
    pre: Dict[str, Any]
    post: Dict[str, Any]
    energies: Dict[str, float]
    keys: Dict[str, Any]
    braid: Dict[str, Any]
    validators: Dict[str, bool]
    parity64: str
    pose_salt: str
    merkle: Dict[str, Any]
    operation_id: str
    commit_bits: str
    ope_debt: float
    fce_debt: float
    mirror_votes: int
    view_votes: int
    hash_chain: str
    timestamp: float = field(default_factory=time.time)
    receipt_id: str
    atom_id: str
    system: str
    input_hash: str
    output_hash: str
    delta_phi: float
    merkle_root: str
    prev_receipt_id: Optional[str] = None
    data: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    action: str
    slot: str
    layer: str
    crystal_id: Optional[str]
    metadata: Dict[str, Any]
    signature: str
    phase: str
    payload_hash: str
    receipt_hash: str
    prev_receipt_hash: Optional[str]
    payload: Dict[str, Any]
    controller: str
    inputs_hash: str
    outputs_hash: str
    status: ReceiptStatus = ReceiptStatus.COMPLETE
    index: int = 0
    operation: str
    inputs: Any
    outputs: Any
    _receipts: Dict[str, Receipt] = {}
    _lock = threading.RLock()
    tool_id: str
    role: str
    prev_hash: str
    chain_index: int
    snap_labels: List[str] = field(default_factory=list)
    _hash: Optional[str] = field(default=None, repr=False)
    run_id: str
    step_id: str
    timestamp_utc: str
    artifacts: List[Dict[str, Any]]
    artifacts_merkle_root: str
    signing_key_id: str
    signature_b64: str
    overlays: Optional[Dict[str, Any]] = None
    extra: Optional[Dict[str, Any]] = None
    controller_request_id: str
    turn_number: int
    app: str
    ttl_turns: int = 6
    expires_at: Optional[datetime] = None
    domain: str
    command: str
    atoms_created: int = 0
    atoms_modified: int = 0
    invariants_checked: int = 0
    invariants_passed: int = 0
    violations: tuple = ()
    prev_receipt: str
    sequence: int
    input_hashes: Dict[str, str]
    output_hashes: Dict[str, str]
    env_hash: str

    def __init__(self, metadata: ReceiptMetadata, data: Optional[ReceiptData]=None):
        self._metadata = metadata
        self._data = data or ReceiptData(receipt_id=metadata.receipt_id)
        self._on_state_change: List[callable] = []
        self._on_complete: List[callable] = []

    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.utcnow()
        if self.expires_at is None:
            self.expires_at = self.created_at + timedelta(minutes=self.ttl_turns)
        if self.metadata is None:
            self.metadata = {}

    def cancel(self) -> None:
        """Cancel receipt."""
        if self.is_complete:
            return
        self._metadata.state = ReceiptState.CANCELLED
        self._metadata.completed_at = time.time()
        if self._metadata.started_at:
            self._metadata.duration_ms = (self._metadata.completed_at - self._metadata.started_at) * 1000
        self._notify_state_change()
        self._notify_complete()

    @classmethod
    def cleanup(cls, before_timestamp: float) -> int:
        """Clean up old completed receipts."""
        count = 0
        with cls._lock:
            to_remove = []
            for rid, receipt in cls._receipts.items():
                if receipt.is_complete:
                    completed_at = receipt._metadata.completed_at
                    if completed_at and completed_at < before_timestamp:
                        to_remove.append(rid)
            for rid in to_remove:
                del cls._receipts[rid]
                count += 1
        return count

    def complete(self, output_data: Optional[Dict[str, Any]]=None, metrics: Optional[Dict[str, Any]]=None, exit_code: int=0) -> None:
        """Complete receipt successfully."""
        if self.is_complete:
            return
        if output_data:
            self._data.output_data.update(output_data)
        if metrics:
            self._data.metrics.update(metrics)
        self._metadata.output_hash = self._data.compute_output_hash()
        self._metadata.state = ReceiptState.SUCCESS
        self._metadata.exit_code = exit_code
        self._metadata.completed_at = time.time()
        if self._metadata.started_at:
            self._metadata.duration_ms = (self._metadata.completed_at - self._metadata.started_at) * 1000
        self._notify_state_change()
        self._notify_complete()
        logger.debug(f'Completed receipt: {self._metadata.name}')

    def compute_hash(self) -> str:
        """Compute content hash (receipt ID)."""
        content = json.dumps({'controller': self.controller, 'inputs_hash': self.inputs_hash, 'outputs_hash': self.outputs_hash, 'timestamp': self.timestamp.isoformat()}, sort_keys=True)
        return hashlib.sha256(content.encode()).hexdigest()

    @classmethod
    def create(cls, name: str, receipt_type: ReceiptType=ReceiptType.TASK, version: str='1.0.0', parent_receipt_id: Optional[str]=None, controller_id: Optional[str]=None, context_id: Optional[str]=None, workspace_id: Optional[str]=None, tags: Optional[Set[str]]=None, snap_layers: Optional[List[str]]=None, depends_on: Optional[List[str]]=None, **kwargs) -> Receipt:
        """
        Create a new receipt.

        Args:
            name: Receipt name
            receipt_type: Type of receipt
            version: Version string
            parent_receipt_id: Parent receipt ID
            controller_id: Controller ID
            context_id: Context ID
            workspace_id: Workspace ID
            tags: Receipt tags
            snap_layers: SNAP layers
            depends_on: Dependencies
            **kwargs: Additional metadata

        Returns:
            New Receipt instance
        """
        receipt_id = kwargs.get('receipt_id') or cls._generate_receipt_id()
        root_id = parent_receipt_id
        if parent_receipt_id:
            parent = cls._receipts.get(parent_receipt_id)
            if parent:
                root_id = parent._metadata.root_receipt_id or parent_receipt_id
        metadata = ReceiptMetadata(receipt_id=receipt_id, receipt_type=receipt_type, name=name, version=version, parent_receipt_id=parent_receipt_id, root_receipt_id=root_id, controller_id=controller_id, context_id=context_id, workspace_id=workspace_id, tags=tags or set(), snap_layers=snap_layers or [], depends_on=depends_on or [])
        receipt = cls(metadata)
        with cls._lock:
            cls._receipts[receipt_id] = receipt
        if parent_receipt_id:
            parent = cls._receipts.get(parent_receipt_id)
            if parent:
                parent._metadata.child_receipt_ids.append(receipt_id)
        logger.debug(f'Created receipt: {name} (id={receipt_id})')
        return receipt

    @property
    def data(self) -> ReceiptData:
        return self._data

    def fail(self, error: str, exit_code: int=1, output_data: Optional[Dict[str, Any]]=None) -> None:
        """Fail receipt."""
        if self.is_complete:
            return
        if output_data:
            self._data.output_data.update(output_data)
        self._metadata.state = ReceiptState.FAILURE
        self._metadata.error = error
        self._metadata.exit_code = exit_code
        self._metadata.completed_at = time.time()
        if self._metadata.started_at:
            self._metadata.duration_ms = (self._metadata.completed_at - self._metadata.started_at) * 1000
        self._metadata.output_hash = self._data.compute_output_hash()
        self._notify_state_change()
        self._notify_complete()
        logger.debug(f'Failed receipt: {self._metadata.name} - {error}')

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Receipt:
        """Create from dictionary."""
        return cls(receipt_id=data['receipt_id'], atom_id=data['atom_id'], system=data['system'], input_hash=data['input_hash'], output_hash=data['output_hash'], delta_phi=data['delta_phi'], merkle_root=data['merkle_root'], prev_receipt_id=data.get('prev_receipt_id'), data=data.get('data', {}), created_at=data.get('created_at', datetime.now().isoformat()))

    @classmethod
    def get(cls, receipt_id: str) -> Optional[Receipt]:
        """Get receipt by ID."""
        with cls._lock:
            return cls._receipts.get(receipt_id)

    @classmethod
    def get_all(cls) -> List[Receipt]:
        """Get all receipts."""
        with cls._lock:
            return list(cls._receipts.values())

    @classmethod
    def get_by_controller(cls, controller_id: str) -> List[Receipt]:
        """Get all receipts for a controller."""
        with cls._lock:
            return [r for r in cls._receipts.values() if r._metadata.controller_id == controller_id]

    @classmethod
    def get_by_state(cls, state: ReceiptState) -> List[Receipt]:
        """Get all receipts in a state."""
        with cls._lock:
            return [r for r in cls._receipts.values() if r._metadata.state == state]

    @classmethod
    def get_by_type(cls, receipt_type: ReceiptType) -> List[Receipt]:
        """Get all receipts of a type."""
        with cls._lock:
            return [r for r in cls._receipts.values() if r._metadata.receipt_type == receipt_type]

    @classmethod
    def get_children(cls, receipt_id: str) -> List[Receipt]:
        """Get all children of a receipt."""
        receipt = cls._receipts.get(receipt_id)
        if not receipt:
            return []
        with cls._lock:
            return [cls._receipts[cid] for cid in receipt._metadata.child_receipt_ids if cid in cls._receipts]

    def get_input(self, key: str, default: Any=None) -> Any:
        """Get input data."""
        return self._data.input_data.get(key, default)

    @classmethod
    def get_lineage(cls, receipt_id: str) -> List[Receipt]:
        """Get full lineage of a receipt (parents to root)."""
        lineage = []
        current = cls._receipts.get(receipt_id)
        while current:
            lineage.insert(0, current)
            if current._metadata.parent_receipt_id:
                current = cls._receipts.get(current._metadata.parent_receipt_id)
            else:
                break
        return lineage

    def get_metric(self, key: str, default: Any=None) -> Any:
        """Get metric."""
        return self._data.metrics.get(key, default)

    def get_output(self, key: str, default: Any=None) -> Any:
        """Get output data."""
        return self._data.output_data.get(key, default)

    @classmethod
    def get_root_receipts(cls) -> List[Receipt]:
        """Get all root receipts (no parent)."""
        with cls._lock:
            return [r for r in cls._receipts.values() if r._metadata.parent_receipt_id is None]

    @property
    def hash(self) -> str:
        if self._hash is None:
            self._hash = self._compute_hash()
        return self._hash

    @property
    def is_complete(self) -> bool:
        return self._metadata.state in {ReceiptState.SUCCESS, ReceiptState.FAILURE, ReceiptState.CANCELLED, ReceiptState.TIMEOUT}

    def is_valid(self) -> bool:
        """Check whether this receipt's hash matches its contents."""
        expected = _compute_hash(self)
        return self.receipt_hash == expected

    @property
    def metadata(self) -> ReceiptMetadata:
        return self._metadata

    def on_complete(self, callback: callable) -> None:
        """Register complete callback."""
        self._on_complete.append(callback)

    def on_state_change(self, callback: callable) -> None:
        """Register state change callback."""
        self._on_state_change.append(callback)

    @property
    def parent(self) -> Optional[Receipt]:
        if self._metadata.parent_receipt_id:
            return self._receipts.get(self._metadata.parent_receipt_id)
        return None

    @property
    def receipt_id(self) -> str:
        return self._metadata.receipt_id

    def set_input(self, key: str, value: Any) -> None:
        """Set input data."""
        self._data.input_data[key] = value

    def set_metric(self, key: str, value: Any) -> None:
        """Set metric."""
        self._data.metrics[key] = value

    def set_output(self, key: str, value: Any) -> None:
        """Set output data."""
        self._data.output_data[key] = value

    def start(self) -> None:
        """Start receipt execution."""
        if self._metadata.state != ReceiptState.PENDING:
            return
        self._metadata.state = ReceiptState.RUNNING
        self._metadata.started_at = time.time()
        self._metadata.input_hash = self._data.compute_input_hash()
        self._notify_state_change()
        logger.debug(f'Started receipt: {self._metadata.name}')

    @property
    def state(self) -> ReceiptState:
        return self._metadata.state

    def timeout(self) -> None:
        """Mark receipt as timed out."""
        if self.is_complete:
            return
        self._metadata.state = ReceiptState.TIMEOUT
        self._metadata.error = 'Execution timed out'
        self._metadata.completed_at = time.time()
        if self._metadata.started_at:
            self._metadata.duration_ms = (self._metadata.completed_at - self._metadata.started_at) * 1000
        self._notify_state_change()
        self._notify_complete()

    def to_dict(self) -> Dict:
        """Convert to dictionary."""
        d = asdict(self)
        d['timestamp'] = self.timestamp.isoformat()
        d['status'] = self.status.value
        return d

    def to_record(self) -> ReceiptRecord:
        """Convert to MMDB ReceiptRecord."""
        return ReceiptRecord(run_id=self.run_id, step_id=self.step_id, controller=self.controller, timestamp_utc=self.timestamp_utc, status=self.status, inputs=self.inputs, outputs=self.outputs, artifacts_merkle_root=self.artifacts_merkle_root, prev_receipt_hash=self.prev_receipt_hash, receipt_hash=self.receipt_hash, signing_key_id=self.signing_key_id, signature_b64=self.signature_b64)

    def _compute_hash(self) -> str:
        blob = f'{self.receipt_id}|{self.timestamp}|{self.tool_id}|{self.role}|{self.inputs_hash}|{self.outputs_hash}|{self.delta_phi}|{self.prev_hash}|{self.chain_index}'
        return hashlib.sha256(blob.encode()).hexdigest()

    @classmethod
    def _generate_receipt_id(cls) -> str:
        """Generate unique receipt ID."""
        return f'rcpt-{uuid.uuid4().hex[:12]}'

    def _notify_complete(self) -> None:
        """Notify complete callbacks."""
        for callback in self._on_complete:
            try:
                callback(self._metadata)
            except Exception as e:
                logger.error(f'Complete callback error: {e}')

    def _notify_state_change(self) -> None:
        """Notify state change callbacks."""
        for callback in self._on_state_change:
            try:
                callback(self._metadata.state)
            except Exception as e:
                logger.error(f'State change callback error: {e}')
