"""Formalization primitives (Base-4, Hodge, CRT, BRM, E8 roots, Morphon genus)."""
from __future__ import annotations

from .core import (
    Base4Codec,
    BRMStepFunction,
    BRSChecker,
    COUPLING,
    CRT24Ring,
    GNLCReducer,
    HodgeDecomposer,
    HodgeDecomposition,
    MorphonClassifier,
    MorphonGenus,
    NLAECNFChain,
    ParityCorrection,
    PHI,
    SyndromeChecker,
    digital_root,
    e8_roots,
    e8_snap,
    generate_e8_roots,
    route_by_dr,
)
from .superperm import (
    N4_LENGTH,
    N4_PERM_COUNT,
    N4_SYMBOLS,
    SUPERPERM_N4,
    coverage_check,
    coverage_checksum,
    digit_at,
    is_palindrome_phase,
    iter_digits,
    load_n4_metadata,
    n4_permutation_set,
    phase_at,
    superperm_n,
    walk_phases,
)

__all__ = [
    "Base4Codec",
    "BRMStepFunction",
    "BRSChecker",
    "COUPLING",
    "CRT24Ring",
    "GNLCReducer",
    "HodgeDecomposer",
    "HodgeDecomposition",
    "MorphonClassifier",
    "MorphonGenus",
    "NLAECNFChain",
    "ParityCorrection",
    "PHI",
    "SyndromeChecker",
    "digital_root",
    "e8_roots",
    "e8_snap",
    "generate_e8_roots",
    "route_by_dr",
    "N4_SYMBOLS",
    "N4_PERM_COUNT",
    "N4_LENGTH",
    "SUPERPERM_N4",
    "coverage_check",
    "coverage_checksum",
    "digit_at",
    "phase_at",
    "is_palindrome_phase",
    "load_n4_metadata",
    "iter_digits",
    "n4_permutation_set",
    "superperm_n",
    "walk_phases",
]
