"""
Composed canonical: AletheiaFacade  [PENDING REVIEW]

Family:           aletheia
Original family:  aletheia
Replicas:         3  (below hardening threshold of 10)
Witness:          <composed from 3 variants, 2 methods, 4 conflicts>

⚠️  PENDING REVIEW — set aside in the first hardening pass.

Low-replica items often live here for one of four reasons:

  1. Novel adaptation that had not yet propagated to other files
     (the system was being extended; this is the new edge).
  2. Recently-added upgrade that exists only in one or two places
     (newer than the hardened version, may supersede it).
  3. Specific-purpose fix or adaptation layer — addresses one
     particular need that the broader hardened set does not.
  4. Genuine noise the first-pass noise filter missed (test,
     demo, scratch experiment).

Review criteria for second pass — for each pending file:

  (a) Is its functionality already covered by the hardened set?
      → If YES: is there novel material here worth merging in?
      → If NO:  should this be promoted to hardened?
  (b) Does it superesede something in hardened (it might be the
      newer / better version that has not yet replicated)?
  (c) Is it noise after second look? → drop with rationale.

Composition: method-union of 3 variants → 2 methods (4 conflicts resolved), 1 attrs

Auto-generated by partition_canonicals.py. Do not edit by hand;
re-run the merger if the source pool changes.
"""
from __future__ import annotations

class AletheiaFacade:
    """Wrapper for the Aletheia integrated system.

    It prefers the aletheia_integrated_system module, falling back to
    aletheia_monolith if needed.
    """
    base_dir: str = DEFAULT_BASE_DIR

    def new_system(self, **kwargs: Any) -> Any:
        """Instantiate the canonical Aletheia system class."""
        mod = self._load_module()
        for cls_name in ('AletheiaIntegratedSystem', 'AletheiaAI', 'AletheiaSystem'):
            if hasattr(mod, cls_name):
                cls = getattr(mod, cls_name)
                return cls(**kwargs)
        raise RuntimeError('No canonical Aletheia system class found in module.')

    def _load_module(self) -> Any:
        import sys
        if self.base_dir and self.base_dir not in sys.path:
            sys.path.insert(0, self.base_dir)
        for mod_name in ('aletheia_integrated_system', 'aletheia_monolith'):
            try:
                return importlib.import_module(mod_name)
            except ImportError:
                continue
        raise RuntimeError('No Aletheia module (integrated/monolith) found.')
