"""
AUTO-MERGED canonical from 8 variant(s). Function-union strategy.
Generated by _scripts/merge_variants.py.

Source variants:
  - D:/PartsFactory/Unification Prototypes/tools/agenthub/agent_hub.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/CMPLX-TMN2/repos/CMPLXUNI/src/cmplx/hub/agent_hub.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/CMPLX-TMN2/repos/CMPLX/cmplx_submodules/CMPLX/core/src/cmplx/hub/agent_hub.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/CMPLX-TMN2/repos/CMPLX/core/src/cmplx/hub/agent_hub.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/CMPLX-TMN2/repos/CMPLX/core/src/cmplx/misc/agent_hub.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/CMPLX-TMN2/repos/CMPLXUNI/src/cmplx/misc/agent_hub.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/CMPLX-TMN2/repos/CMPLX/cmplx_submodules/CMPLXUNI/src/cmplx/hub/agent_hub.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/CMPLX-TMN2/repos/CMPLX/cmplx_submodules/CMPLXUNI/src/cmplx/misc/agent_hub.py

Merge stats: {'imports_union': 9, 'definitions_merged': 2, 'names_with_conflicts': 1, 'has_trailing_main': False}
"""

from __future__ import annotations



"""AUTO-MERGED canonical from 2 variant(s). Function-union strategy.
Generated by _scripts/merge_variants.py.

Source variants:
  - D:/PartsFactory/Unification Prototypes/_extracted/agenthub/agenthub-corpus/03-historical-builds/historical builds/CMPLX-TMN2/repos/CMPLXUNI/src/cmplx/hub/agent_hub.py
  - D:/PartsFactory/Unification Prototypes/_extracted/agenthub/agenthub-corpus/03-historical-builds/historical builds/CMPLXUNI-main (1)/CMPLXUNI-main/src/cmplx/hub/agent_hub.py

Merge stats: {'imports_union': 7, 'definitions_merged': 2, 'names_with_conflicts': 0, 'has_trailing_main': False}"""



from core.legacy_stubs import AgentRuntime, AgentSpec  # was: cmplx_hub.agent_runtime
from core.legacy_stubs import MMDBMDHGSpeedLightPipeline  # was: cmplx_toolkit.controllers.memory_pipeline
from core.legacy_stubs import AgentRuntime, AgentSpec
from core.legacy_stubs import MMDBMDHGSpeedLightPipeline
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
import time
import uuid


class AgentManagementHub:
    """Agent/subagent lifecycle hub with MMDB-backed in-session memory."""

    def __init__(
        self,
        *,
        memory_pipeline: MMDBMDHGSpeedLightPipeline,
        gateway: Any = None,
        llm: Any = None,
    ) -> None:
        self.memory_pipeline = memory_pipeline
        self.runtime = AgentRuntime(gateway=gateway, llm=llm)
        self._sessions: Dict[str, HubSession] = {}

    def create_session(self, *, name: str = "", metadata: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        session = HubSession(name=name or "agent-session", metadata=metadata or {})
        self._sessions[session.session_id] = session
        return session.to_dict()

    def list_sessions(self) -> List[Dict[str, Any]]:
        return [session.to_dict() for session in self._sessions.values()]

    def get_session(self, session_id: str) -> Optional[HubSession]:
        return self._sessions.get(session_id)

    def register_agent(
        self,
        *,
        session_id: str,
        spec: AgentSpec,
        parent_agent_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        session = self._sessions.get(session_id)
        if not session:
            return {"error": f"Unknown session_id: {session_id}"}

        if parent_agent_id and parent_agent_id not in session.agents:
            return {"error": f"Unknown parent_agent_id: {parent_agent_id}"}

        instance = self.runtime.create(spec)
        session.agents[instance.agent_id] = {
            "role": spec.role,
            "goal": spec.goal,
            "parent_agent_id": parent_agent_id,
            "state": instance.state.value,
        }
        session.last_active_at = time.time()

        return {
            "session_id": session_id,
            "agent_id": instance.agent_id,
            "parent_agent_id": parent_agent_id,
            "role": spec.role,
            "goal": spec.goal,
        }

    async def append_memory(
        self,
        *,
        session_id: str,
        content: str,
        role: str = "user",
        level: str = "ca",
        metadata: Optional[Dict[str, Any]] = None,
        terms: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        session = self._sessions.get(session_id)
        if not session:
            return {"error": f"Unknown session_id: {session_id}"}

        event_number = session.memory_events + 1
        source_path = f"memory://session/{session_id}/{event_number:06d}_{role}"
        merged_metadata = {
            "session_id": session_id,
            "role": role,
        }
        if metadata:
            merged_metadata.update(metadata)

        result = await self.memory_pipeline.ingest(
            {
                "level": level,
                "corpus_label": f"session:{session_id}",
                "source_path": source_path,
                "content": content,
                "metadata": merged_metadata,
                "terms": terms,
            }
        )

        session.memory_events += 1
        session.last_active_at = time.time()

        return {
            "session_id": session_id,
            "event_number": event_number,
            "level": level,
            "source_path": source_path,
            "result": result,
        }

    async def recall(
        self,
        *,
        session_id: str,
        query: str,
        top_k: int = 5,
        level: Optional[str] = None,
        snap_required: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        session = self._sessions.get(session_id)
        if not session:
            return {"error": f"Unknown session_id: {session_id}"}

        result = await self.memory_pipeline.query(
            {
                "term": query,
                "top_k": top_k,
                "level": level,
                "snap_required": snap_required or [],
            }
        )

        prefix = f"memory://session/{session_id}/"
        scoped = []
        for item in result.get("results", []):
            mdhg_payload = item.get("mdhg", {}) if isinstance(item, dict) else {}
            source_path = mdhg_payload.get("source_path", "")
            if source_path.startswith(prefix):
                scoped.append(item)

        session.last_active_at = time.time()
        return {
            "session_id": session_id,
            "query": query,
            "count": len(scoped),
            "results": scoped[:top_k],
            "level": level or "all",
        }

    async def run_agent_task(
        self,
        *,
        session_id: str,
        agent_id: str,
        task_description: str,
        inputs: Optional[Dict[str, Any]] = None,
        remember: bool = True,
        level: str = "ca",
    ) -> Dict[str, Any]:
        session = self._sessions.get(session_id)
        if not session:
            return {"error": f"Unknown session_id: {session_id}"}

        if agent_id not in session.agents:
            return {"error": f"Agent {agent_id} is not registered in session {session_id}"}

        if remember:
            await self.append_memory(
                session_id=session_id,
                content=task_description,
                role="user",
                level=level,
                metadata={"agent_id": agent_id, "kind": "task"},
            )

        result = await self.runtime.run_task(
            agent_id,
            task_description,
            inputs=inputs,
        )

        session_state = self.runtime.get(agent_id)
        if session_state:
            session.agents[agent_id]["state"] = session_state.state.value

        if remember and result.get("output"):
            await self.append_memory(
                session_id=session_id,
                content=result.get("output", ""),
                role="assistant",
                level=level,
                metadata={"agent_id": agent_id, "kind": "response"},
            )

        session.last_active_at = time.time()
        return {
            "session_id": session_id,
            "agent_id": agent_id,
            "task_result": result,
        }

    def session_status(self, session_id: str) -> Dict[str, Any]:
        session = self._sessions.get(session_id)
        if not session:
            return {"error": f"Unknown session_id: {session_id}"}

        live_agents = []
        for agent_id, info in session.agents.items():
            runtime = self.runtime.get(agent_id)
            live_agents.append(
                {
                    "agent_id": agent_id,
                    "role": info.get("role", ""),
                    "goal": info.get("goal", ""),
                    "parent_agent_id": info.get("parent_agent_id"),
                    "state": runtime.state.value if runtime else info.get("state", "unknown"),
                    "iterations": runtime.iterations if runtime else 0,
                }
            )

        return {
            "session": session.to_dict(),
            "agents": live_agents,
            "memory": {
                "events": session.memory_events,
                "db_path": self.memory_pipeline.db_path,
            },
        }


@dataclass
class HubSession:
    session_id: str = field(default_factory=lambda: f"sess:{uuid.uuid4().hex[:12]}")
    name: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: float = field(default_factory=time.time)
    last_active_at: float = field(default_factory=time.time)
    memory_events: int = 0
    agents: Dict[str, Dict[str, Any]] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        roots = [agent_id for agent_id, item in self.agents.items() if not item.get("parent_agent_id")]
        subagents = [agent_id for agent_id, item in self.agents.items() if item.get("parent_agent_id")]
        return {
            "session_id": self.session_id,
            "name": self.name,
            "metadata": self.metadata,
            "created_at": self.created_at,
            "last_active_at": self.last_active_at,
            "memory_events": self.memory_events,
            "agent_count": len(self.agents),
            "root_agents": roots,
            "subagents": subagents,
        }
