"""
Integrated 2026-05-22T16:45:00Z from Unification Prototypes.
Source: ``D:\PartsFactory\Unification Prototypes\tools\economy\economy.py``
Auto-merged canonical from 8 variant(s). Function-union strategy.
"""
"""
AUTO-MERGED canonical from 8 variant(s). Function-union strategy.
Generated by _scripts/merge_variants.py.

Source variants:
  - D:/PartsFactory/Unification Prototypes/tools/economy/economy.py
  - D:/Manny Unification 2/historical builds/CMPLX-TMN2/src/economy/economy.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/CMPLX-TMN2/src/economy/economy.py
  - D:/Manny Unification 2/datasets from previous review/Unification Reporting/archive-staging/96e331e3-98ad-42d7-aa12-2c8596036fdb/CQE_CANONICAL_UNIFIED_V1/tools/cqe_civ_compute/cqe_civ/economy.py
  - D:/Manny Unification 2/datasets from previous review/MannyUnification/Unification Reporting/archive-staging/077edafc-46c6-4d69-8602-fba0cf9d489d/CQE_CANONICAL_UNIFIED_V1/tools/cqe_civ_compute/cqe_civ/economy.py
  - D:/Manny Unification 2/datasets from previous review/Unification Reporting/archive-staging/e8b8e9d5-ca5c-45ff-b2c2-0af927a9c13c/CQE_CANONICAL_UNIFIED_V1/tools/cqe_civ_compute/cqe_civ/economy.py
  - D:/Manny Unification 2/output/archive-staging/8e13638f-92fb-4030-a3ff-d4ac90728ee6/CQE_CANONICAL_UNIFIED_V1/tools/cqe_civ_compute/cqe_civ/economy.py
  - D:/Manny Unification 2/output/archive-staging/832bc873-17cc-4bfb-a69d-9162f09f9038/CQE_CANONICAL_UNIFIED_V1/tools/cqe_civ_compute/cqe_civ/economy.py

Merge stats: {'imports_union': 21, 'definitions_merged': 77, 'names_with_conflicts': 43, 'has_trailing_main': True}
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from fastapi import FastAPI, HTTPException
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Any, Dict, Optional
from typing import Dict, Any, List
from typing import Dict, Any, List, Tuple
from typing import Optional
from uuid import uuid4
import json
import math
import math, random
import os
import psycopg2
import random
import time
import uuid
import uvicorn
"AUTO-MERGED canonical from 7 variant(s). Function-union strategy.\nGenerated by _scripts/merge_variants.py.\n\nSource variants:\n  - D:/PartsFactory/Unification Prototypes/_extracted/economy/economy-corpus/03-historical-builds/historical builds/Builds/CMPLX/retooling_src/tools/economy.py\n  - D:/PartsFactory/Unification Prototypes/_extracted/economy/economy-corpus/03-historical-builds/historical builds/CMPLX-main (1)/CMPLX-main/ported/cmplx2/economy.py\n  - D:/PartsFactory/Unification Prototypes/_extracted/economy/economy-corpus/03-historical-builds/historical builds/CMPLX-TMN2/.claude/worktrees/recursing-sammet/src/economy/economy.py\n  - D:/PartsFactory/Unification Prototypes/_extracted/economy/economy-corpus/03-historical-builds/historical builds/CMPLX-TMN2/repos/CMPLX/src/cmplx2/economy.py\n  - D:/PartsFactory/Unification Prototypes/_extracted/economy/economy-corpus/03-historical-builds/historical builds/CMPLX-TMN2/repos/CMPLX/src/cqe_spine/economy.py\n  - D:/PartsFactory/Unification Prototypes/_extracted/economy/economy-corpus/03-historical-builds/historical builds/CMPLX-TMN2/src/economy/economy.py\n  - D:/PartsFactory/Unification Prototypes/_extracted/economy/economy-corpus/04-output-only-uniques/output/archive-staging/832bc873-17cc-4bfb-a69d-9162f09f9038/CQE_CANONICAL_UNIFIED_V1/tools/cqe_civ_compute/cqe_civ/economy.py\n\nMerge stats: {'imports_union': 21, 'definitions_merged': 75, 'names_with_conflicts': 18, 'has_trailing_main': True}"

@dataclass
class BalanceSheet:
    debt: float = 0.0
    interest: float = 0.02
    credit_limit: float = 200.0
    in_default: bool = False

class BuyRequest(BaseModel):
    buyer_id: str
    listing_id: str

class BuybackRequest(BaseModel):
    amount: float = Field(gt=0)
    max_price: float = Field(gt=0)

class CommissionRequest(BaseModel):
    requester: str
    task: str = Field(..., min_length=5, max_length=2000)
    reward: float = Field(gt=0)
    snap_labels: list[str] = Field(default_factory=list)
    deadline_hours: float = Field(default=24.0, gt=0)

class CommissionStatus(str, Enum):
    OPEN = 'open'
    CLAIMED = 'claimed'
    IN_PROGRESS = 'in_progress'
    COMPLETED = 'completed'
    DISPUTED = 'disputed'
RESOURCE_KEYS = ['cpu_ms', 'gpu_ms', 'ram_mb_s', 'io_mb', 'net_mb', 'tokens', 'embed_ops', 'hash_ops', 'store_ops']

@dataclass
class EconomyState:
    resources: Dict[str, float] = field(default_factory=lambda: {k: 1000.0 for k in RESOURCE_KEYS})
    prices: Dict[str, float] = field(default_factory=lambda: {k: 1.0 for k in RESOURCE_KEYS})
    market_temp: float = 0.2
    supply_chain: Dict[str, List[str]] = field(default_factory=lambda: {'tokens': ['cpu_ms', 'ram_mb_s'], 'embed_ops': ['gpu_ms', 'ram_mb_s'], 'hash_ops': ['cpu_ms', 'io_mb'], 'store_ops': ['io_mb', 'net_mb'], 'cpu_ms': [], 'gpu_ms': [], 'ram_mb_s': [], 'io_mb': [], 'net_mb': []})

class ItemType(str, Enum):
    BRAIN = 'brain'
    LABEL_SET = 'label_set'
    TRAINING_DATA = 'training_data'
    CAPABILITY = 'capability'
    TEMPLATE = 'template'
    ARTIFACT = 'artifact'

class LendRequest(BaseModel):
    lender_id: str
    amount: float = Field(gt=0)
    rate: float = Field(ge=0, le=1.0, description='Interest rate 0-1')
    duration_hours: float = Field(gt=0)

class ListItemRequest(BaseModel):
    seller_id: str
    item_type: ItemType
    price: float = Field(gt=0)
    title: str = Field(..., min_length=1, max_length=200)
    description: str = Field(default='')
    snap_labels: list[str] = Field(default_factory=list)

class StakeRequest(BaseModel):
    agent_id: str
    amount: float = Field(gt=0)
    pool: str = Field(default='stability')

def _adjust_balance(agent_id: str, delta: float, reason: str) -> float:
    current = _get_balance(agent_id)
    new_balance = current + delta
    if new_balance < 0:
        raise HTTPException(400, f'Insufficient balance: have {current}, need {abs(delta)}')
    balances[agent_id] = new_balance
    _pg_save_balance(agent_id, new_balance)
    tx = {'tx_id': f'tx-{uuid.uuid4().hex[:8]}', 'agent_id': agent_id, 'type': 'adjust', 'amount': delta, 'delta': delta, 'balance_after': new_balance, 'description': reason, 'reason': reason, 'timestamp': _now_iso()}
    transaction_log.append(tx)
    _pg_save_transaction(tx)
    if len(transaction_log) > 10000:
        transaction_log[:] = transaction_log[-5000:]
    return new_balance

def _compute_dynamic_apy(pool_name: str) -> float:
    """APY adjusts with coupling constant and pool utilization."""
    pool = STAKING_POOLS.get(pool_name)
    if not pool:
        return 0.0
    base = pool['base_apy']
    staked = pool['total_staked']
    utilization_factor = 1.0 / (1.0 + staked * COUPLING)
    return round(base * utilization_factor, 6)

def _get_balance(agent_id: str) -> float:
    return balances.get(agent_id, 1000.0)

def _get_pg():
    global _pg_conn
    if not PG_URL:
        return None
    try:
        if _pg_conn is None or _pg_conn.closed:
            _pg_conn = psycopg2.connect(PG_URL)
            _pg_conn.autocommit = True
        return _pg_conn
    except Exception:
        return None

def _init_tables():
    conn = _get_pg()
    if not conn:
        return
    with conn.cursor() as cur:
        cur.execute("\n            CREATE TABLE IF NOT EXISTS economy_listings (\n                listing_id  TEXT PRIMARY KEY,\n                seller_id   TEXT NOT NULL,\n                item_type   TEXT NOT NULL,\n                price       DOUBLE PRECISION NOT NULL,\n                snap_labels JSONB DEFAULT '[]',\n                status      TEXT NOT NULL DEFAULT 'active',\n                created_at  DOUBLE PRECISION NOT NULL,\n                data        JSONB DEFAULT '{}'\n            )\n        ")
        cur.execute("\n            CREATE TABLE IF NOT EXISTS economy_commissions (\n                commission_id TEXT PRIMARY KEY,\n                requester     TEXT NOT NULL,\n                task          TEXT NOT NULL,\n                reward        DOUBLE PRECISION NOT NULL,\n                status        TEXT NOT NULL DEFAULT 'open',\n                claimed_by    TEXT,\n                data          JSONB DEFAULT '{}'\n            )\n        ")
        cur.execute("\n            CREATE TABLE IF NOT EXISTS economy_stakes (\n                stake_id   TEXT PRIMARY KEY,\n                agent_id   TEXT NOT NULL,\n                pool       TEXT NOT NULL,\n                amount     DOUBLE PRECISION NOT NULL,\n                started_at DOUBLE PRECISION NOT NULL,\n                data       JSONB DEFAULT '{}'\n            )\n        ")
        cur.execute('\n            CREATE TABLE IF NOT EXISTS economy_balances (\n                agent_id TEXT PRIMARY KEY,\n                balance  DOUBLE PRECISION NOT NULL DEFAULT 1000.0\n            )\n        ')

def _now() -> str:
    return time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def _pg_load_all():
    """Load persisted state from PG into in-memory dicts."""
    conn = _get_pg()
    if not conn:
        return ({}, {}, {}, {})
    _listings, _commissions, _stakes, _balances = ({}, {}, {}, {})
    try:
        with conn.cursor() as cur:
            cur.execute('SELECT listing_id, data FROM economy_listings')
            for lid, data in cur.fetchall():
                _listings[lid] = data if isinstance(data, dict) else json.loads(data)
            cur.execute('SELECT commission_id, data FROM economy_commissions')
            for cid, data in cur.fetchall():
                _commissions[cid] = data if isinstance(data, dict) else json.loads(data)
            cur.execute('SELECT stake_id, data FROM economy_stakes')
            for sid, data in cur.fetchall():
                _stakes[sid] = data if isinstance(data, dict) else json.loads(data)
            cur.execute('SELECT agent_id, balance FROM economy_balances')
            for aid, bal in cur.fetchall():
                _balances[aid] = bal
    except Exception:
        pass
    return (_listings, _commissions, _stakes, _balances)

def _pg_save_balance(agent_id: str, balance: float):
    conn = _get_pg()
    if not conn:
        return
    try:
        with conn.cursor() as cur:
            cur.execute('\n                INSERT INTO economy_balances (agent_id, balance)\n                VALUES (%s, %s)\n                ON CONFLICT (agent_id) DO UPDATE SET balance = EXCLUDED.balance\n            ', (agent_id, balance))
    except Exception:
        pass

def _pg_save_commission(com: dict):
    conn = _get_pg()
    if not conn:
        return
    try:
        with conn.cursor() as cur:
            cur.execute('\n                INSERT INTO economy_commissions (commission_id, requester, task, reward, status, claimed_by, data)\n                VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb)\n                ON CONFLICT (commission_id) DO UPDATE\n                    SET status = EXCLUDED.status, claimed_by = EXCLUDED.claimed_by, data = EXCLUDED.data\n            ', (com['commission_id'], com['requester'], com['task'], com['reward'], com.get('status', 'open'), com.get('claimed_by'), json.dumps(com)))
    except Exception:
        pass

def _pg_save_listing(listing: dict):
    conn = _get_pg()
    if not conn:
        return
    try:
        with conn.cursor() as cur:
            cur.execute('\n                INSERT INTO economy_listings (listing_id, seller_id, item_type, price, snap_labels, status, created_at, data)\n                VALUES (%s, %s, %s, %s, %s::jsonb, %s, %s, %s::jsonb)\n                ON CONFLICT (listing_id) DO UPDATE\n                    SET status = EXCLUDED.status, data = EXCLUDED.data\n            ', (listing['listing_id'], listing['seller_id'], listing['item_type'], listing['price'], json.dumps(listing.get('snap_labels', [])), listing['status'], time.time(), json.dumps(listing)))
    except Exception:
        pass

def _pg_save_stake(stk: dict):
    conn = _get_pg()
    if not conn:
        return
    try:
        with conn.cursor() as cur:
            cur.execute('\n                INSERT INTO economy_stakes (stake_id, agent_id, pool, amount, started_at, data)\n                VALUES (%s, %s, %s, %s, %s, %s::jsonb)\n                ON CONFLICT (stake_id) DO UPDATE\n                    SET data = EXCLUDED.data\n            ', (stk['stake_id'], stk['agent_id'], stk['pool'], stk['amount'], time.time(), json.dumps(stk)))
    except Exception:
        pass

def _pg_save_transaction(tx: dict):
    """Persist transaction to PG for durable audit trail."""
    conn = _get_pg()
    if not conn:
        return
    try:
        with conn.cursor() as cur:
            cur.execute("CREATE TABLE IF NOT EXISTS economy_transactions (\n                tx_id TEXT PRIMARY KEY, agent_id TEXT, tx_type TEXT,\n                amount REAL, description TEXT, snap_labels JSONB DEFAULT '[]',\n                created_at TIMESTAMP DEFAULT NOW())")
            cur.execute('INSERT INTO economy_transactions (tx_id, agent_id, tx_type, amount, description, snap_labels)\n                VALUES (%s,%s,%s,%s,%s,%s) ON CONFLICT DO NOTHING', (tx.get('tx_id', str(uuid.uuid4())[:12]), tx.get('agent_id', ''), tx.get('type', ''), tx.get('amount', 0), tx.get('description', '')[:500], json.dumps(tx.get('snap_labels', []))))
    except:
        pass

def append_ledger(workspace: Path, rec: Dict[str, Any]) -> Dict[str, Any]:
    ensure_economy(workspace)
    rec = dict(rec)
    rec.setdefault('t', _now())
    rec.setdefault('id', f'eco:{uuid4().hex}')
    with (workspace / 'economy' / 'ledger.jsonl').open('a', encoding='utf-8') as f:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')
    return rec

def apply_interest(bs: BalanceSheet) -> None:
    if bs.in_default:
        return
    bs.debt *= 1.0 + bs.interest

def balance(workspace: Path, planet_id: str, asset: str='MDHG') -> float:
    ensure_economy(workspace)
    p = workspace / 'economy' / 'ledger.jsonl'
    bal = 0.0
    with p.open('r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except Exception:
                continue
            if rec.get('asset') != asset:
                continue
            amt = float(rec.get('amount', 0.0))
            if rec.get('to') == planet_id:
                bal += amt
            if rec.get('from') == planet_id:
                bal -= amt
    return float(bal)

def borrow(bs: BalanceSheet, amount: float) -> float:
    if bs.in_default:
        return 0.0
    headroom = max(0.0, bs.credit_limit - bs.debt)
    take = min(headroom, max(0.0, amount))
    bs.debt += take
    return take

def burn(workspace: Path, planet_id: str, amount: float, asset: str='MDHG', note: str='burn') -> Dict[str, Any]:
    return append_ledger(workspace, {'type': 'burn', 'from': planet_id, 'to': None, 'amount': float(amount), 'asset': asset, 'note': note})
app = FastAPI(title='TMN2 Economy', version='1.0.0')

@app.post('/buy')
def buy(req: BuyRequest):
    """Buy item from marketplace."""
    listing = listings.get(req.listing_id)
    if not listing:
        raise HTTPException(404, 'Listing not found')
    if listing['status'] != 'active':
        raise HTTPException(400, f"Listing is {listing['status']}")
    if listing['seller_id'] == req.buyer_id:
        raise HTTPException(400, 'Cannot buy your own listing')
    price = listing['price']
    _adjust_balance(req.buyer_id, -price, f'purchase:{req.listing_id}')
    _adjust_balance(listing['seller_id'], price * 0.95, f'sale:{req.listing_id}')
    _adjust_balance('__treasury__', price * 0.05, f'fee:{req.listing_id}')
    listing['status'] = 'sold'
    listing['buyer_id'] = req.buyer_id
    listing['sold_at'] = _now_iso()
    _pg_save_listing(listing)
    return {'listing_id': req.listing_id, 'buyer_id': req.buyer_id, 'seller_id': listing['seller_id'], 'price': price, 'fee': round(price * 0.05, 4), 'item_type': listing['item_type'], 'status': 'sold'}

@app.post('/buyback')
def buyback(req: BuybackRequest):
    """Buyback coins from market (treasury operation)."""
    treasury_balance = _get_balance('__treasury__')
    cost = min(req.amount * req.max_price, treasury_balance)
    coins_bought = cost / req.max_price if req.max_price > 0 else 0
    if coins_bought <= 0:
        raise HTTPException(400, 'Treasury has insufficient funds for buyback')
    _adjust_balance('__treasury__', -cost, f'buyback:{round(coins_bought, 2)}')
    return {'buyback_id': f'bb-{uuid.uuid4().hex[:8]}', 'coins_bought': round(coins_bought, 4), 'cost': round(cost, 4), 'effective_price': round(cost / coins_bought, 4) if coins_bought > 0 else 0, 'max_price': req.max_price, 'treasury_remaining': round(_get_balance('__treasury__'), 4), 'timestamp': _now_iso()}

def charge(workspace: Path, planet_id: str, amount: float, asset: str='MDHG', reason: str='fee', meta: Optional[Dict[str, Any]]=None) -> Dict[str, Any]:
    return append_ledger(workspace, {'type': 'charge', 'from': planet_id, 'to': '__sink__', 'amount': float(amount), 'asset': asset, 'note': reason, 'meta': meta or {}})

def clamp(x: float, lo: float, hi: float) -> float:
    return lo if x < lo else hi if x > hi else x

def consume_households(econ: EconomyState, pop: float) -> Dict[str, float]:
    """Baseline per-tick compute drain.

    pop is treated as workload intensity / concurrent tasks.
    """
    needs = {'cpu_ms': 5.0 * pop, 'ram_mb_s': 2.5 * pop, 'io_mb': 0.5 * pop}
    unmet: Dict[str, float] = {}
    for k, need in needs.items():
        have = econ.resources.get(k, 0.0)
        take = min(have, need)
        econ.resources[k] = have - take
        unmet[k] = need - take
    return unmet

@app.post('/commission')
def create_commission(req: CommissionRequest):
    """Create commission request."""
    commission_id = f'com-{uuid.uuid4().hex[:12]}'
    _adjust_balance(req.requester, -req.reward, f'commission_escrow:{commission_id}')
    commission = {'commission_id': commission_id, 'requester': req.requester, 'task': req.task, 'reward': req.reward, 'snap_labels': req.snap_labels, 'status': CommissionStatus.OPEN, 'created_at': _now_iso(), 'deadline_hours': req.deadline_hours, 'claimed_by': None, 'claimed_at': None, 'completed_at': None}
    commissions[commission_id] = commission
    _pg_save_commission(commission)
    return {'commission_id': commission_id, 'status': CommissionStatus.OPEN, 'reward': req.reward, 'escrowed': True, 'deadline_hours': req.deadline_hours}

def ensure_economy(workspace: Path) -> Path:
    p = workspace / 'economy'
    p.mkdir(parents=True, exist_ok=True)
    (p / 'ledger.jsonl').touch(exist_ok=True)
    return p

def equilibrium_index(workspace: Path, asset: str='MDHG') -> Dict[str, Any]:
    ensure_economy(workspace)
    p = workspace / 'economy' / 'ledger.jsonl'
    total_mint = 0.0
    total_burn = 0.0
    sink = 0.0
    planets = set()
    with p.open('r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except Exception:
                continue
            if rec.get('asset') != asset:
                continue
            t = rec.get('type')
            amt = float(rec.get('amount', 0.0))
            if t == 'mint':
                total_mint += amt
            if t == 'burn':
                total_burn += amt
            if rec.get('to') == '__sink__':
                sink += amt
            for who in (rec.get('to'), rec.get('from')):
                if who and who not in ('__sink__', None):
                    planets.add(who)
    supply = total_mint - total_burn
    pressure = sink / max(supply, 1.0)
    return {'asset': asset, 'total_supply': supply, 'sink': sink, 'pressure': pressure, 'active_planets': len(planets)}

def gini(values: List[float]) -> float:
    if not values:
        return 0.0
    v = sorted((max(0.0, float(x)) for x in values))
    n = len(v)
    s = sum(v)
    if s <= 0:
        return 0.0
    cum = 0.0
    for i, x in enumerate(v, start=1):
        cum += i * x
    return 2 * cum / (n * s) - (n + 1) / n

@app.get('/health')
def health():
    return {'status': 'healthy', 'service': 'economy', 'block': 'economy', 'listings': len([l for l in listings.values() if l['status'] == 'active']), 'commissions': len([c for c in commissions.values() if c['status'] == CommissionStatus.OPEN]), 'active_loans': len([l for l in loans.values() if l['status'] == 'active']), 'active_stakes': len(stakes), 'pools': len(STAKING_POOLS), 'transactions': len(transaction_log), 'timestamp': _now_iso()}

@app.post('/lend')
def lend(req: LendRequest):
    """Lend coins."""
    loan_id = f'loan-{uuid.uuid4().hex[:12]}'
    _adjust_balance(req.lender_id, -req.amount, f'lend:{loan_id}')
    interest = round(req.amount * req.rate * (req.duration_hours / 720), 4)
    loan = {'loan_id': loan_id, 'lender_id': req.lender_id, 'amount': req.amount, 'rate': req.rate, 'interest': interest, 'total_repayment': req.amount + interest, 'duration_hours': req.duration_hours, 'status': 'active', 'created_at': _now_iso(), 'borrower_id': None, 'borrowed_at': None}
    loans[loan_id] = loan
    conn = _get_pg()
    if conn:
        try:
            with conn.cursor() as cur:
                cur.execute("CREATE TABLE IF NOT EXISTS economy_loans (\n                    loan_id TEXT PRIMARY KEY, lender_id TEXT, borrower_id TEXT,\n                    amount REAL, rate REAL, interest REAL, total_repayment REAL,\n                    duration_hours REAL, status TEXT DEFAULT 'active',\n                    created_at TIMESTAMP DEFAULT NOW())")
                cur.execute('INSERT INTO economy_loans\n                    (loan_id, lender_id, amount, rate, interest, total_repayment, duration_hours, status)\n                    VALUES (%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT DO NOTHING', (loan_id, req.lender_id, req.amount, req.rate, interest, loan['total_repayment'], req.duration_hours, 'active'))
        except:
            pass
    return {'loan_id': loan_id, 'amount': req.amount, 'rate': req.rate, 'interest': interest, 'total_repayment': loan['total_repayment'], 'duration_hours': req.duration_hours, 'status': 'active'}

@app.get('/commissions')
def list_commissions(status: Optional[str]=None):
    """List open commissions."""
    result = []
    for c in commissions.values():
        if status and c['status'] != status:
            continue
        result.append({'commission_id': c['commission_id'], 'requester': c['requester'], 'task': c['task'][:100], 'reward': c['reward'], 'status': c['status'], 'snap_labels': c['snap_labels'], 'created_at': c['created_at'], 'deadline_hours': c['deadline_hours']})
    return {'commissions': result, 'total': len(result)}

@app.post('/list_item')
def list_item(req: ListItemRequest):
    """List item on marketplace."""
    listing_id = f'lst-{uuid.uuid4().hex[:12]}'
    listing = {'listing_id': listing_id, 'seller_id': req.seller_id, 'item_type': req.item_type.value, 'title': req.title, 'description': req.description, 'price': req.price, 'snap_labels': req.snap_labels, 'status': 'active', 'created_at': _now_iso(), 'views': 0, 'buyer_id': None}
    listings[listing_id] = listing
    _pg_save_listing(listing)
    return {'listing_id': listing_id, 'status': 'active', 'price': req.price, 'item_type': req.item_type.value, 'snap_labels': req.snap_labels}

@app.get('/pools')
def list_pools():
    """Staking pools with APY."""
    result = []
    for name, pool in STAKING_POOLS.items():
        current_apy = _compute_dynamic_apy(name)
        pool_stakes = [s for s in stakes.values() if s['pool'] == name]
        result.append({'pool': name, 'name': pool['name'], 'base_apy': pool['base_apy'], 'current_apy': current_apy, 'min_stake': pool['min_stake'], 'total_staked': pool['total_staked'], 'stakers': len(pool_stakes)})
    return {'pools': result}

@app.get('/marketplace')
def marketplace(item_type: Optional[str]=None, max_price: Optional[float]=None):
    """List all active listings."""
    result = []
    for l in listings.values():
        if l['status'] != 'active':
            continue
        if item_type and l['item_type'] != item_type:
            continue
        if max_price and l['price'] > max_price:
            continue
        result.append({'listing_id': l['listing_id'], 'seller_id': l['seller_id'], 'item_type': l['item_type'], 'title': l['title'], 'price': l['price'], 'snap_labels': l['snap_labels'], 'created_at': l['created_at'], 'views': l['views']})
    result.sort(key=lambda x: x['created_at'], reverse=True)
    return {'listings': result, 'total': len(result)}

def maybe_default(bs: BalanceSheet) -> None:
    if bs.in_default:
        return
    if bs.debt > bs.credit_limit * 1.25:
        bs.in_default = True

def mint(workspace: Path, planet_id: str, amount: float, asset: str='MDHG', note: str='mint') -> Dict[str, Any]:
    return append_ledger(workspace, {'type': 'mint', 'from': None, 'to': planet_id, 'amount': float(amount), 'asset': asset, 'note': note})

def produce(econ: EconomyState, recipe: Dict[str, float], out: Dict[str, float]) -> Dict[str, float]:
    """Consume capacity tokens (recipe) to produce other capacity tokens (out).

    This is a stand-in for internal scheduler transforms:
    - spending cpu+ram produces tokens
    - spending gpu+ram produces embed_ops
    - spending cpu+io produces hash_ops
    - spending io+net produces store_ops

    Output is bottlenecked by the scarcest input.
    """
    if not recipe:
        for k, v in out.items():
            econ.resources[k] = econ.resources.get(k, 0.0) + float(v)
        return {'bottleneck': None, 'scale': 1.0}
    scales = []
    keys = list(recipe.keys())
    for k, need in recipe.items():
        have = econ.resources.get(k, 0.0)
        scales.append(1.0 if need <= 0 else have / need)
    scale = max(0.0, min(scales))
    for k, need in recipe.items():
        econ.resources[k] = max(0.0, econ.resources.get(k, 0.0) - need * scale)
    for k, make in out.items():
        econ.resources[k] = econ.resources.get(k, 0.0) + make * scale
    bn = None
    if scales:
        idx = scales.index(min(scales))
        bn = keys[idx]
    return {'bottleneck': bn, 'scale': scale}

def repay(bs: BalanceSheet, amount: float) -> float:
    if bs.in_default:
        return 0.0
    pay = min(bs.debt, max(0.0, amount))
    bs.debt -= pay
    return pay

@app.post('/stake')
def stake(req: StakeRequest):
    """Stake coins for yield."""
    pool = STAKING_POOLS.get(req.pool)
    if not pool:
        raise HTTPException(404, f"Pool '{req.pool}' not found. Available: {list(STAKING_POOLS.keys())}")
    if req.amount < pool['min_stake']:
        raise HTTPException(400, f"Minimum stake for {req.pool}: {pool['min_stake']}")
    _adjust_balance(req.agent_id, -req.amount, f'stake:{req.pool}')
    stake_id = f'stk-{uuid.uuid4().hex[:12]}'
    current_apy = _compute_dynamic_apy(req.pool)
    stake_record = {'stake_id': stake_id, 'agent_id': req.agent_id, 'pool': req.pool, 'amount': req.amount, 'apy_at_entry': current_apy, 'staked_at': _now_iso(), 'estimated_annual_yield': round(req.amount * current_apy, 4)}
    stakes[stake_id] = stake_record
    _pg_save_stake(stake_record)
    pool['total_staked'] += req.amount
    return {'stake_id': stake_id, 'pool': req.pool, 'amount': req.amount, 'apy': current_apy, 'estimated_annual_yield': stake_record['estimated_annual_yield']}

@app.post('/tick')
def tick():
    """Daemon tick — auto-create listings from high-quality PG atoms, accrue staking yields."""
    created_listings = 0
    yields_paid = 0
    conn = _get_pg()
    if conn and len(listings) < 50:
        try:
            with conn.cursor() as cur:
                cur.execute('SELECT atom_id, quality_score, LEFT(content, 100) as preview\n                    FROM atoms WHERE quality_score > 0.7\n                    ORDER BY quality_score DESC LIMIT 5')
                for atom_id, qscore, preview in cur.fetchall():
                    lid = f'lst-{atom_id[:12]}'
                    if lid not in listings:
                        listings[lid] = {'listing_id': lid, 'item_type': 'atom', 'item_id': atom_id, 'seller_id': 'system', 'price': round(qscore * 10, 2), 'description': preview or atom_id, 'status': 'active', 'created_at': _now_iso(), 'snap_labels': ['economy.auto_listing']}
                        _pg_save_listing(listings[lid])
                        created_listings += 1
        except:
            pass
    for sid, stake in list(stakes.items()):
        if stake.get('status') == 'active':
            pool = STAKING_POOLS.get(stake.get('pool', ''))
            if pool:
                apy = _compute_dynamic_apy(stake['pool'])
                hourly_yield = stake.get('amount', 0) * apy / (365 * 24)
                if hourly_yield > 0.001:
                    _adjust_balance(stake['staker_id'], hourly_yield, f"staking_yield:{stake['pool']}:{sid[:8]}")
                    yields_paid += 1
    auto_buys = 0
    active_listings = [l for l in listings.values() if l.get('status') == 'active']
    system_buyers = ['pipeline', 'manny', 'claudeclaw', 'engine-0']
    for buyer in system_buyers:
        balance = _get_balance(buyer)
        for listing in active_listings[:2]:
            if listing['status'] == 'active' and listing['price'] <= balance * 0.1:
                try:
                    _adjust_balance(buyer, -listing['price'], f"buy:{listing['listing_id']}")
                    _adjust_balance(listing['seller_id'], listing['price'] * 0.9, f"sell:{listing['listing_id']}")
                    listing['status'] = 'sold'
                    listing['buyer_id'] = buyer
                    auto_buys += 1
                except:
                    pass
                break
    auto_staked = 0
    for agent_id in system_buyers:
        balance = _get_balance(agent_id)
        if balance > 500 and (not any((s.get('staker_id') == agent_id for s in stakes.values()))):
            stake_amount = balance * 0.2
            sid = f'stake-{agent_id}-{uuid.uuid4().hex[:6]}'
            stakes[sid] = {'stake_id': sid, 'staker_id': agent_id, 'pool': 'stability', 'amount': stake_amount, 'status': 'active', 'created_at': _now_iso()}
            _adjust_balance(agent_id, -stake_amount, f'stake:{sid}')
            _pg_save_stake(stakes[sid])
            auto_staked += 1
    return {'ok': True, 'listings_created': created_listings, 'yields_paid': yields_paid, 'auto_buys': auto_buys, 'auto_staked': auto_staked, 'total_listings': len(listings), 'total_stakes': len(stakes)}

def transfer(workspace: Path, from_id: str, to_id: str, amount: float, asset: str='MDHG', note: str='transfer') -> Dict[str, Any]:
    return append_ledger(workspace, {'type': 'transfer', 'from': from_id, 'to': to_id, 'amount': float(amount), 'asset': asset, 'note': note})

def update_prices(econ: EconomyState, rng: random.Random) -> None:
    """Update scarcity multipliers.

    Prices are not "money"; they are soft indicators of marginal cost.
    """
    vol = 0.0
    for k in RESOURCE_KEYS:
        avail = max(1e-06, econ.resources.get(k, 0.0))
        target = clamp(1000.0 / avail, 0.2, 8.0)
        old = econ.prices.get(k, 1.0)
        new = 0.85 * old + 0.15 * target
        vol += abs(new - old)
        econ.prices[k] = new
    econ.market_temp = clamp(0.9 * econ.market_temp + 0.1 * clamp(vol / len(RESOURCE_KEYS), 0.0, 1.0), 0.0, 1.0)
BOARD_URL = os.getenv('BOARD_URL', 'http://tmn2-board:8000')
COOP_URL = os.getenv('COOP_URL', 'http://tmn2-coop:8000')
COUPLING = float(os.getenv('COUPLING', '0.030076'))
MINT_URL = os.getenv('MINT_URL', 'http://tmn2-mint:8000')
PG_URL = os.getenv('PG_URL', 'postgresql://tmn2:tmn2_dev@tmn2-pg:5432/tmn2')
PORT = int(os.getenv('PORT', '8000'))
SAP_URL = os.getenv('SAP_URL', 'http://tmn2-sap:8000')
STAKING_POOLS = {'stability': {'name': 'Stability Pool', 'base_apy': 0.05, 'min_stake': 10, 'total_staked': 0}, 'growth': {'name': 'Growth Pool', 'base_apy': 0.12, 'min_stake': 50, 'total_staked': 0}, 'venture': {'name': 'Venture Pool', 'base_apy': 0.25, 'min_stake': 200, 'total_staked': 0}, 'e8_deep': {'name': 'E8 Deep Pool', 'base_apy': 0.08, 'min_stake': 100, 'total_staked': 0}}
THINKTANK_URL = os.getenv('THINKTANK_URL', 'http://tmn2-thinktank:8000')
_pg_listings, _pg_commissions, _pg_stakes, _pg_balances = _pg_load_all()
_pg_listings, _pg_commissions, _pg_stakes, _pg_balances = _pg_load_all()
_pg_conn = None
_pg_listings, _pg_commissions, _pg_stakes, _pg_balances = _pg_load_all()
_pg_listings, _pg_commissions, _pg_stakes, _pg_balances = _pg_load_all()
balances: dict = _pg_balances
commissions: dict = _pg_commissions
listings: dict = _pg_listings
loans: dict = {}
stakes: dict = _pg_stakes
transaction_log: list = []
'economy.py - Agent marketplace: commissions, upgrades, lending, staking, buyback.\nFull market engine with order book, staking pools, and commission system.\nTMN2-native service. No retooling imports.'
'Internal compute budget model.\n\nCivSim treats "societies" as compute clusters and "actors" as controllers.\nThis module provides a minimal deterministic budgeting layer.\n\n- resources[k]: remaining capacity tokens (per tick / rolling window)\n- prices[k]: scarcity multipliers derived from availability\n- supply_chain: simplified dependency graph between capacity types\n\nThe function signatures intentionally match the earlier toy economy so other\nmodules do not need to change to use compute semantics.\n'
_init_tables()
'Internal compute budget model.\n\nCivSim treats "societies" as compute clusters and "actors" as controllers.\nThis module provides a minimal deterministic budgeting layer.\n\n- resources[k]: remaining capacity tokens (per tick / rolling window)\n- prices[k]: scarcity multipliers derived from availability\n- supply_chain: simplified dependency graph between capacity types\n\nThe function signatures intentionally match the earlier toy economy so other\nmodules do not need to change to use compute semantics.\n'
if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=PORT, log_level='info')