"""
Function canonicals for the `swarm` family.

1 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- function: _read_json ---
# composed_from=33 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\e8\partsfactory\e8_embedding_ingest_controller.py
def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))
