"""
Composed canonical: LambdaTerm

Family: lambda
Decision: batch=8 id=647
Composition: method-union of 14 variants → 11 methods (20 conflicts resolved), 11 attrs

Auto-generated by place_canonicals.py from the atomic decision queue.
Do not edit by hand — re-run the merger to refresh.
"""
from __future__ import annotations

class LambdaTerm:
    """CQE proto-language lambda calculus term represented as glyph + vector embeddings."""
    term_type: str
    content: Any
    lambda_type: Optional[LambdaType] = None
    metadata: Dict[str, Any] = None
    name: Optional[str] = None
    body: Optional['LambdaTerm'] = None
    func: Optional['LambdaTerm'] = None
    arg: Optional['LambdaTerm'] = None
    e8_coords: Optional[List[float]] = None
    level: LambdaLevel
    value: Any

    def __init__(self, expr: str, shelling: ShellingCompressor, alena: ALENAOps, morsr: EnhancedMORSRExplorer):
        self.expr = expr
        self.shelling = shelling
        self.alena = alena
        self.morsr = morsr
        self.glyph_seq = self.shelling.compress_to_glyph(expr, level=3)
        self.vector = self.text_to_vector(self.glyph_seq)

    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}

    def __repr__(self) -> str:
        return f'LambdaTerm({self.term_type}, {self.to_string()[:60]})'

    def apply(self, arg: 'LambdaTerm') -> 'LambdaTerm':
        """Apply lambda term to argument."""
        combined_expr = f'({self.expr}) ({arg.expr})'
        combined_glyph = f'{self.glyph_seq}|{arg.glyph_seq}'
        combined_vector = self.vector + arg.vector
        combined_vector = combined_vector / np.linalg.norm(combined_vector) if np.linalg.norm(combined_vector) > 0 else combined_vector
        snapped = self.alena.r_theta_snap(combined_vector)
        pulsed, _ = self.morsr.explore(np.copy(snapped))
        new_term = LambdaTerm(combined_expr, self.shelling, self.alena, self.morsr)
        new_term.glyph_seq = combined_glyph
        new_term.vector = pulsed
        return new_term

    def depth(self):
        if self.kind == 'var':
            return 0
        sub = [a.depth() for a in self.args if isinstance(a, LambdaTerm)]
        return 1 + (max(sub) if sub else 0)

    def free_vars(self):
        if self.kind == 'var':
            return {self.args[0]}
        if self.kind == 'abs':
            body = self.args[1]
            bound = self.args[0]
            return (body.free_vars() if isinstance(body, LambdaTerm) else set()) - {bound}
        fv = set()
        for a in self.args:
            if isinstance(a, LambdaTerm):
                fv |= a.free_vars()
        return fv

    def reduce(self) -> 'LambdaTerm':
        """Simulate reduction step."""
        flipped = self.alena.weyl_flip(self.vector)
        mid = (self.vector + flipped) / 2
        norm_mid = mid * (E8_NORM / np.linalg.norm(mid)) if np.linalg.norm(mid) > 0 else mid
        reduced_term = LambdaTerm(self.expr, self.shelling, self.alena, self.morsr)
        reduced_term.glyph_seq = self.glyph_seq
        reduced_term.vector = norm_mid
        return reduced_term

    def size(self):
        if self.kind == 'var':
            return 1
        return 1 + sum((a.size() for a in self.args if isinstance(a, LambdaTerm)))

    def text_to_vector(self, text: str) -> np.ndarray:
        embed_dim = 128
        words = text.split()
        vec = np.bincount([hash(w) % embed_dim for w in words], minlength=embed_dim) / max(len(words), 1)
        norm_vec = vec / np.linalg.norm(vec) if np.linalg.norm(vec) > 0 else vec
        return norm_vec

    def to_feature_vector(self):
        """Convert term to 8D feature vector for E8 embedding."""
        return np.array([self.depth(), self.size(), len(self.free_vars()), float(self.kind == 'abs'), float(self.kind == 'app'), float(self.kind == 'var'), self.depth() * self.size() % 8, len(self.free_vars()) * self.depth() % 8], dtype=float)

    def to_string(self) -> str:
        """Convert lambda term to string representation."""
        if self.term_type == 'var':
            return self.content
        elif self.term_type == 'abs':
            var, body = self.content
            type_annotation = f': {self.lambda_type.value}' if self.lambda_type else ''
            return f'(λ {var}{type_annotation}. {body.to_string()})'
        elif self.term_type == 'app':
            func, arg = self.content
            return f'({func.to_string()} {arg.to_string()})'
        elif self.term_type == 'e8_op':
            op_name, args = self.content
            arg_strs = [a.to_string() if isinstance(a, LambdaTerm) else str(a) for a in args]
            return f"({op_name} {' '.join(arg_strs)})"
        elif self.term_type == 'dihedral_op':
            N, k, reflect, arg = self.content
            return f"(D_{N}^{k}{('*' if reflect else '')} {arg.to_string()})"
        elif self.term_type == 'path_op':
            op_name, paths = self.content
            path_strs = [p.to_string() if isinstance(p, LambdaTerm) else str(p) for p in paths]
            return f"({op_name} {' '.join(path_strs)})"
        else:
            return f'<{self.term_type}>'
