"""
Constant canonicals for the `niemeier` family.

1 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- assign: all_roots ---
# composed_from=11 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\morphon\morphonic\meta_morphon_and_48d.py
all_roots = e8.get_roots()
