"""
Function [pending review] canonicals for the `swarm` family.

24 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- function: _aggregate ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\build_swarm_concurrency_playbook.py
def _aggregate(rows: list[dict[str, Any]]) -> dict[str, Any]:
    runtime = [float(item.get("runtime_median_ms", 0.0) or 0.0) for item in rows]
    pass_rate = [float(item.get("pass_rate", 0.0) or 0.0) for item in rows]
    focus = [float(item.get("focus_required_rate", 0.0) or 0.0) for item in rows]
    fallback = [float(item.get("fallback_ratio_median", 0.0) or 0.0) for item in rows]
    det = [float(item.get("determinism_rate", 0.0) or 0.0) for item in rows]
    return {
        "count": len(rows),
        "runtime_median_ms": round(_median(runtime), 6),
        "pass_rate_median": round(_median(pass_rate), 6),
        "focus_required_rate_median": round(_median(focus), 6),
        "fallback_ratio_median": round(_median(fallback), 6),
        "determinism_rate_median": round(_median(det), 6),
    }

# --- function: _budget_agent ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _budget_agent(program: dict[str, Any]) -> AgentResult:
    findings: list[str] = []
    required_changes: list[str] = []
    score = 0

    model = program.get("budget_model", {})
    vars_ = model.get("variables", {})
    formulas = list(model.get("formulas", []))
    policies = list(model.get("policies", []))

    needed_vars = ["Z", "Y", "L", "C_min", "X"]
    if _has_all(list(vars_.keys()), needed_vars):
        findings.append("Budget variables include Z/Y/L/C_min/X.")
        score += 35
    else:
        required_changes.append("Define budget variables Z, Y, L, C_min, X.")

    if len(formulas) >= 3:
        findings.append("Budget formulas define agent count and batch allocation.")
        score += 35
    else:
        required_changes.append("Add complete budget formulas for X, batch_count, calls_per_batch.")

    if policies:
        findings.append("Budget fallback policy exists.")
        score += 30
    else:
        required_changes.append("Add policy for under-budget handling.")

    status = "approve" if not required_changes else "approve_with_conditions"
    return AgentResult(
        agent_id="agent_budget_model",
        title="Budget Model",
        status=status,
        score=score,
        findings=findings,
        required_changes=required_changes,
    )

# --- function: _build_linear_tasks ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _build_linear_tasks(program: dict[str, Any], linear_task_count: int) -> list[dict[str, Any]]:
    cycles = list(program.get("cycles", []))
    roles = [role for role in program.get("roles", []) if role != "writer_agent"]
    if not roles:
        roles = ["scanner_agent"]
    tasks: list[dict[str, Any]] = []
    for index in range(linear_task_count):
        cycle_id = cycles[index % len(cycles)] if cycles else f"cycle_{index + 1:02d}"
        role = roles[index % len(roles)]
        task_id = f"task_{index + 1:03d}"
        tasks.append(
            {
                "task_id": task_id,
                "cycle_id": cycle_id,
                "role": role,
                "scope_id": f"{cycle_id}::{role}::{task_id}",
            }
        )
    return tasks

# --- function: _build_micro_swarm_plan ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _build_micro_swarm_plan(program: dict[str, Any], budget_inputs: dict[str, Any]) -> dict[str, Any]:
    roles = [role for role in program.get("roles", []) if role != "writer_agent"]
    cycles = list(program.get("cycles", []))
    labels = list(program.get("label_families_required", []))

    z = max(1, _to_int(budget_inputs.get("z"), 120))
    y = max(1, _to_int(budget_inputs.get("y"), min(max(len(roles), 1), 8)))
    l = max(1, _to_int(budget_inputs.get("l"), max(len(cycles) * 2, 6)))
    c_min = max(1, _to_int(budget_inputs.get("c_min"), 8))

    x = min(y, z // c_min, l)
    effective_x = max(1, x)
    batch_count = max(1, (l + effective_x - 1) // effective_x)
    calls_per_batch = z // max(1, batch_count)
    budget_valid = x >= 1 and calls_per_batch >= c_min

    tasks = _build_linear_tasks(program, l)
    batches: list[dict[str, Any]] = []
    for batch_index in range(batch_count):
        start = batch_index * effective_x
        end = min(start + effective_x, len(tasks))
        window = tasks[start:end]
        assignments: list[dict[str, Any]] = []
        for slot_index, task in enumerate(window, start=1):
            assignments.append(
                {
                    "agent_instance_id": f"micro_agent_{batch_index + 1:02d}_{slot_index:02d}",
                    "agent_slot": slot_index,
                    "role": task["role"],
                    "task_id": task["task_id"],
                    "scope_contract": {
                        "scope_id": task["scope_id"],
                        "allowed_parts": labels[:5],
                        "allowed_tools": ["read", "extract", "label", "handoff"],
                        "input_schema": "atomic_input_v1",
                        "output_schema": "atomic_output_v1",
                        "invariant_set": ["append_only", "deterministic_ids", "receipt_chain"],
                    },
                    "writer_handoff_required": True,
                }
            )
        batches.append(
            {
                "batch_id": f"batch_{batch_index + 1:02d}",
                "task_range": {"start_index": start + 1, "end_index": end},
                "calls_budget": calls_per_batch,
                "assignments": assignments,
            }
        )

    return {
        "style": "thinktank_micro_swarm_non_enacting",
        "inputs": {"Z": z, "Y": y, "L": l, "C_min": c_min},
        "resolved": {
            "X": x,
            "batch_count": batch_count,
            "calls_per_batch": calls_per_batch,
            "budget_valid": budget_valid,
        },
        "tasks": tasks,
        "batches": batches,
        "writer_handoff_model": "many_readers_single_writer",
    }

# --- function: _build_rag ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\build_swarm_concurrency_playbook.py
def _build_rag(report: dict[str, Any]) -> dict[str, Any]:
    cards: list[dict[str, Any]] = []

    def add_card(title: str, summary: str, tags: list[str], source_ref: str, neighbors: list[str]) -> str:
        seed = {"title": title, "source_ref": source_ref, "summary": summary}
        card_id = prefixed_id("card", seed)
        cards.append(
            {
                "card_id": card_id,
                "title": title,
                "summary": summary,
                "tags": tags,
                "source_ref": source_ref,
                "neighbors": neighbors,
            }
        )
        return card_id

    hypothesis_id = add_card(
        "hypothesis:remove_one_at_a_time_bottleneck",
        "Validate swarm after shifting from one-at-a-time to single-writer safety.",
        ["swarm", "concurrency", "hypothesis"],
        "contract:update",
        [],
    )
    run_card_ids: list[str] = []
    for row in report["runs"]:
        cid = add_card(
            f"run:{row['run_file']}",
            f"mode={row['mode']} runtime_median_ms={row['runtime_median_ms']} pass_rate={row['pass_rate']} focus_required_rate={row['focus_required_rate']}",
            ["swarm", "run", row["mode"]],
            row["run_file"],
            [hypothesis_id],
        )
        run_card_ids.append(cid)

    integrity_id = add_card(
        "finding:single_writer_and_receipt_integrity_hold",
        "G_SWARM_4 and G_SWARM_5 passed across all lock-check runs.",
        ["swarm", "gates", "integrity"],
        report["reference_cycle_id"],
        run_card_ids[:],
    )
    performance_id = add_card(
        "finding:throughput_needs_parallel_agent_workers",
        report["conclusion"]["interpretation"],
        ["swarm", "performance", "bottleneck"],
        report["report_id"],
        run_card_ids[:],
    )
    action_id = add_card(
        "action:parallelize_run_micro_swarm_pilot",
        "Preserve single-writer DB safety while parallelizing per-task run execution.",
        ["swarm", "action", "next_step"],
        "src/cmplx_os/swarm/api.py",
        [integrity_id, performance_id],
    )

    return {
        "pack_id": prefixed_id("swarm_lockcheck", {"report_id": report["report_id"], "card_count": len(cards)}),
        "generated_at": report["generated_at"],
        "metadata": {
            "scope": "swarm_concurrency_validation",
            "invariant_set": ["single_writer", "append_only", "receipt_chain", "deterministic_ids"],
            "reference_cycle_id": report["reference_cycle_id"],
        },
        "cards": cards,
        "sections": [
            {"section_id": "hypothesis", "title": "Hypothesis", "card_ids": [hypothesis_id]},
            {"section_id": "runs", "title": "Run Evidence", "card_ids": run_card_ids},
            {"section_id": "findings", "title": "Findings", "card_ids": [integrity_id, performance_id]},
            {"section_id": "actions", "title": "Next Actions", "card_ids": [action_id]},
        ],
    }

# --- function: _collect_required_changes ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _collect_required_changes(results: list[AgentResult]) -> list[str]:
    ordered: list[str] = []
    seen: set[str] = set()
    for result in results:
        for change in result.required_changes:
            normalized = " ".join(change.split())
            if normalized in seen:
                continue
            seen.add(normalized)
            ordered.append(normalized)
    return ordered

# --- function: _decision_entries ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _decision_entries(results: list[AgentResult]) -> list[dict[str, Any]]:
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    by_agent = {result.agent_id: result for result in results}
    return [
        {
            "decision_id": "swarm_decision_budget_model_v1",
            "topic": "budget_model",
            "decision": "approved_with_conditions" if by_agent["agent_budget_model"].required_changes else "approved",
            "rationale": "; ".join(by_agent["agent_budget_model"].findings),
            "owner": "agent_budget_model",
            "timestamp": now,
        },
        {
            "decision_id": "swarm_decision_scope_contract_v1",
            "topic": "scope_contract",
            "decision": "approved_with_conditions" if by_agent["agent_scope_schema"].required_changes else "approved",
            "rationale": "; ".join(by_agent["agent_scope_schema"].findings),
            "owner": "agent_scope_schema",
            "timestamp": now,
        },
        {
            "decision_id": "swarm_decision_gates_v1",
            "topic": "gates",
            "decision": "approved_with_conditions",
            "rationale": "Gate set is strong but needs numeric MDHG gate thresholds and explicit measurement bindings.",
            "owner": "agent_mdhg_budget",
            "timestamp": now,
        },
        {
            "decision_id": "swarm_decision_labels_v1",
            "topic": "labels",
            "decision": "approved",
            "rationale": "; ".join(by_agent["agent_snap_hierarchy"].findings),
            "owner": "agent_snap_hierarchy",
            "timestamp": now,
        },
        {
            "decision_id": "swarm_decision_activation_blockers_v1",
            "topic": "activation_blockers",
            "decision": "approved",
            "rationale": "Activation blockers are explicit and correctly prevent premature enactment.",
            "owner": "agent_ops_integrity",
            "timestamp": now,
        },
    ]

# --- function: _gate_result ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\build_swarm_concurrency_playbook.py
def _gate_result(cycle_id: str, gate_id: str) -> dict[str, Any]:
    result = evaluate_swarm_program_gate(cycle_id=cycle_id, gate_id=gate_id)
    return {
        "gate_id": result.gate_id,
        "status": result.status,
        "passed": bool(result.passed),
        "reason": result.reason,
        "evidence_count": len(result.evidence or []),
    }

# --- function: _has_all ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _has_all(items: list[str], required: list[str]) -> bool:
    lookup = set(items)
    return all(item in lookup for item in required)

# --- function: _mdhg_agent ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _mdhg_agent(program: dict[str, Any]) -> AgentResult:
    findings: list[str] = []
    required_changes: list[str] = []
    score = 0

    intent = program.get("intent", {})
    tiers = list(program.get("embedding_tiers", []))
    gates = list(program.get("gates", []))

    if intent.get("mdhg_growth_control_required") is True:
        findings.append("MDHG growth control intent is explicit.")
        score += 30
    else:
        required_changes.append("Set intent.mdhg_growth_control_required=true.")

    if "tier3_mdhg_compressed_embeddings" in tiers:
        findings.append("Embedding tiers include MDHG compression stage.")
        score += 30
    else:
        required_changes.append("Add tier3_mdhg_compressed_embeddings to embedding_tiers.")

    if "G_SWARM_7_mdhg_budget" in gates:
        findings.append("MDHG budget gate exists.")
        score += 20
    else:
        required_changes.append("Add gate G_SWARM_7_mdhg_budget.")

    # This is the main practical gap for implementation readiness.
    required_changes.append("Define numeric MDHG budgets (max_new_embeddings_per_cycle, max_total_embedding_bytes, max_promotion_ratio).")

    if score < 60:
        status = "block"
    else:
        status = "approve_with_conditions"

    return AgentResult(
        agent_id="agent_mdhg_budget",
        title="MDHG Budget",
        status=status,
        score=score,
        findings=findings,
        required_changes=required_changes,
    )

# --- function: _median ---
# composed_from=3 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\build_swarm_concurrency_playbook.py
def _median(values: list[float]) -> float:
    if not values:
        return 0.0
    return float(statistics.median(values))

# --- function: _mode_from_name ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\build_swarm_concurrency_playbook.py
def _mode_from_name(name: str) -> str:
    lowered = name.lower()
    if "serialized" in lowered:
        return "serialized"
    return "parallel_default"

# --- function: _ops_agent ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _ops_agent(program: dict[str, Any]) -> AgentResult:
    findings: list[str] = []
    required_changes: list[str] = []
    score = 0

    roles = list(program.get("roles", []))
    write_model = program.get("write_model", {})

    if "writer_agent" in roles:
        findings.append("Writer agent exists for commit serialization.")
        score += 30
    else:
        required_changes.append("Include writer_agent in roles.")

    if write_model.get("pattern") == "many_readers_single_writer":
        findings.append("Concurrency pattern is correctly constrained.")
        score += 40
    else:
        required_changes.append("Set write_model.pattern='many_readers_single_writer'.")

    if write_model.get("append_only") is True and write_model.get("deterministic_ids") is True:
        findings.append("Append-only and deterministic ID guarantees are present.")
        score += 30
    else:
        required_changes.append("Require append_only=true and deterministic_ids=true.")

    status = "approve" if not required_changes else "approve_with_conditions"
    return AgentResult(
        agent_id="agent_ops_integrity",
        title="Ops Integrity",
        status=status,
        score=score,
        findings=findings,
        required_changes=required_changes,
    )

# --- function: _quorum_status ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _quorum_status(results: list[AgentResult]) -> str:
    statuses = [result.status for result in results]
    if any(status == "block" for status in statuses):
        return "block"
    if any(status == "approve_with_conditions" for status in statuses):
        return "approve_with_conditions"
    return "approve"

# --- function: _render_markdown ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\build_swarm_concurrency_playbook.py
def _render_markdown(report: dict[str, Any]) -> str:
    runs = report["runs"]
    aggregates = report["aggregates"]
    gate_snapshot = report["gate_snapshot"]
    conclusion = report["conclusion"]

    lines = [
        "# SWARM Concurrency Validation Playbook v1",
        "",
        "## Request",
        "",
        "- Validate whether removing strict one-at-a-time execution improved swarm behavior.",
        "- Produce explainable operator guidance and machine-readable RAG cards.",
        "",
        "## Runtime Context",
        "",
        "- DB policy: `single-writer integrity` retained.",
        "- Global DB serialization: toggle via `CMPLX_OS_DB_SERIALIZE_ALL`.",
        "- Swarm pilot envelope used: `tasks=6`, `batches=2`, `seed=core-docs-set`, `profile=morphon_persona_v1`.",
        "",
        "## Run Matrix",
        "",
        "| run_file | mode | cycle_id | runtime_median_ms | pass_rate | focus_required_rate | fallback_ratio_median | determinism_rate |",
        "|---|---|---|---:|---:|---:|---:|---:|",
    ]
    for row in runs:
        lines.append(
            "| `{run_file}` | `{mode}` | `{cycle_id}` | {runtime_median_ms} | {pass_rate} | {focus_required_rate} | {fallback_ratio_median} | {determinism_rate} |".format(
                **row
            )
        )

    lines.extend(
        [
            "",
            "## Aggregates",
            "",
            "| mode | count | runtime_median_ms | pass_rate_median | focus_required_rate_median | fallback_ratio_median | determinism_rate_median |",
            "|---|---:|---:|---:|---:|---:|---:|",
            "| `parallel_default` | {count} | {runtime_median_ms} | {pass_rate_median} | {focus_required_rate_median} | {fallback_ratio_median} | {determinism_rate_median} |".format(
                **aggregates["parallel_default"]
            ),
            "| `serialized` | {count} | {runtime_median_ms} | {pass_rate_median} | {focus_required_rate_median} | {fallback_ratio_median} | {determinism_rate_median} |".format(
                **aggregates["serialized"]
            ),
            "",
            "## Gate Snapshot (Reference Cycle)",
            "",
            f"- `reference_cycle_id`: `{report['reference_cycle_id']}`",
            "",
            "| gate | status | passed | reason |",
            "|---|---|---|---|",
        ]
    )
    for gate in gate_snapshot:
        lines.append(f"| `{gate['gate_id']}` | `{gate['status']}` | `{gate['passed']}` | {gate['reason']} |")

    lines.extend(
        [
            "",
            "## Conclusion",
            "",
            f"- `status`: `{conclusion['status']}`",
            f"- `integrity_ok`: `{conclusion['integrity_ok']}`",
            f"- `parallel_runtime_delta_pct_vs_serialized`: `{conclusion['parallel_runtime_delta_pct_vs_serialized']}`",
            f"- `interpretation`: {conclusion['interpretation']}",
            "",
            "## Why This Result Makes Sense",
            "",
            "1. Removing strict one-at-a-time command enforcement avoids unnecessary policy blocking.",
            "2. Current swarm pilot loop still executes task slices sequentially (`run_micro_swarm_pilot` iterates runs linearly).",
            "3. So integrity behavior improves/holds, but throughput gains require true parallel worker execution in swarm runtime.",
            "",
            "## Operator Commands",
            "",
            "```powershell",
            "$env:CMPLX_OS_DB_SERIALIZE_ALL='0'",
            "python -m cmplx_os.cli swarm pilot --seed core-docs-set --profile morphon_persona_v1 --tasks 6 --batches 2 --run-label lockcheck_parallel --comparative-label lockcheck",
            "Remove-Item Env:CMPLX_OS_DB_SERIALIZE_ALL",
            "",
            "$env:CMPLX_OS_DB_SERIALIZE_ALL='1'",
            "python -m cmplx_os.cli swarm pilot --seed core-docs-set --profile morphon_persona_v1 --tasks 6 --batches 2 --run-label lockcheck_serialized --comparative-label lockcheck",
            "Remove-Item Env:CMPLX_OS_DB_SERIALIZE_ALL",
            "```",
            "",
            "## Next Build Step",
            "",
            "- Implement parallel agent-run execution in `src/cmplx_os/swarm/api.py::run_micro_swarm_pilot` with per-run controller routing and existing single-writer DB safety.",
        ]
    )
    return "\n".join(lines).strip() + "\n"

# --- function: _routing_agent ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _routing_agent(program: dict[str, Any]) -> AgentResult:
    findings: list[str] = []
    required_changes: list[str] = []
    score = 0

    intent = program.get("intent", {})
    write_model = program.get("write_model", {})
    gates = list(program.get("gates", []))

    if intent.get("thinktank_routing_required") is True:
        findings.append("ThinkTank routing requirement is explicitly declared.")
        score += 35
    else:
        required_changes.append("Set intent.thinktank_routing_required=true.")

    if write_model.get("controller_handoff_required") is True:
        findings.append("Controller handoff is mandatory in write model.")
        score += 35
    else:
        required_changes.append("Set write_model.controller_handoff_required=true.")

    if "G_SWARM_3_controller_routing" in gates:
        findings.append("Routing gate exists for enforcement.")
        score += 30
    else:
        required_changes.append("Add gate G_SWARM_3_controller_routing.")

    if required_changes:
        return AgentResult(
            agent_id="agent_routing_guard",
            title="Routing Guard",
            status="approve_with_conditions",
            score=score,
            findings=findings,
            required_changes=required_changes,
        )
    return AgentResult(
        agent_id="agent_routing_guard",
        title="Routing Guard",
        status="approve",
        score=score,
        findings=findings,
        required_changes=required_changes,
    )

# --- function: _run_agents ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _run_agents(program: dict[str, Any]) -> list[AgentResult]:
    agents = [
        _routing_agent,
        _snap_agent,
        _mdhg_agent,
        _ops_agent,
        _schema_agent,
        _budget_agent,
    ]
    return [agent(program) for agent in agents]

# --- function: _schema_agent ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _schema_agent(program: dict[str, Any]) -> AgentResult:
    findings: list[str] = []
    required_changes: list[str] = []
    score = 0

    scope_contract = program.get("agent_scope_contract", {})
    required_fields = list(scope_contract.get("required_fields", []))
    needed = ["scope_id", "allowed_parts", "allowed_tools", "input_schema", "output_schema", "invariant_set"]
    if _has_all(required_fields, needed):
        findings.append("Agent scope contract fields cover typed boundaries.")
        score += 60
    else:
        required_changes.append("Complete required_fields for agent_scope_contract.")

    min_parts = int(scope_contract.get("atomic_parts_per_agent_min", 0) or 0)
    max_parts = int(scope_contract.get("atomic_parts_per_agent_max", 0) or 0)
    if min_parts >= 1 and min_parts <= max_parts <= 8:
        findings.append("Atomic parts bounds are plausible for constrained micro-agents.")
        score += 40
    else:
        required_changes.append("Set atomic_parts_per_agent bounds to a safe micro range.")

    status = "approve" if not required_changes else "approve_with_conditions"
    return AgentResult(
        agent_id="agent_scope_schema",
        title="Scope Schema",
        status=status,
        score=score,
        findings=findings,
        required_changes=required_changes,
    )

# --- function: _snap_agent ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _snap_agent(program: dict[str, Any]) -> AgentResult:
    findings: list[str] = []
    required_changes: list[str] = []
    score = 0

    labels = list(program.get("label_families_required", []))
    needed = ["snap_family", "atom_type", "layer_id", "invariant_set", "reassembly_key"]
    if _has_all(labels, needed):
        findings.append("SNAP hierarchy labels are present in required families.")
        score += 55
    else:
        required_changes.append("Require SNAP hierarchy labels: snap_family, atom_type, layer_id, invariant_set, reassembly_key.")

    layers = list(program.get("layer_model", []))
    if layers and layers[0] == "L0_lexicon" and "L1_atom" in layers:
        findings.append("Layer model starts with lexicon then atomic layer.")
        score += 45
    else:
        required_changes.append("Ensure layer_model starts with L0_lexicon and includes L1_atom.")

    status = "approve" if not required_changes else "approve_with_conditions"
    return AgentResult(
        agent_id="agent_snap_hierarchy",
        title="SNAP Hierarchy",
        status=status,
        score=score,
        findings=findings,
        required_changes=required_changes,
    )

# --- function: _to_int ---
# composed_from=2 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\mdhg\partsfactory\run_mdhg_thinktank_chain.py
def _to_int(value: Any, default: int = 0) -> int:
    try:
        return int(str(value).strip().replace('"', ""))
    except Exception:
        return default

# --- function: _to_markdown ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def _to_markdown(payload: dict[str, Any]) -> str:
    status = payload["quorum"]["status"]
    plan = payload.get("micro_swarm_plan", {})
    resolved = plan.get("resolved", {})
    batches = list(plan.get("batches", []))
    lines: list[str] = [
        "# SWARM_META_REVIEW_v1",
        "",
        "Status: `filled_from_micro_agent_quorum`",
        "Execution mode: `not_enacted`",
        "Linked draft: `docs/SWARM_PROGRAM_v1_DRAFT.md`",
        "",
        "## ThinkTank-Style Review Mode",
        "",
        "This review used a constrained micro-agent quorum (bastardized ThinkTank mode):",
        "1. scoped agents",
        "2. deterministic checks",
        "3. quorum synthesis",
        "4. no runtime enactment",
        "",
        "## Quorum Synthesis",
        "",
        f"- overall_status: `{status}`",
        f"- approve: {payload['quorum']['counts']['approve']}",
        f"- approve_with_conditions: {payload['quorum']['counts']['approve_with_conditions']}",
        f"- block: {payload['quorum']['counts']['block']}",
        "",
        "## ThinkTank-Style Micro-Swarm Plan (Simulated)",
        "",
        f"- style: `{plan.get('style', 'unknown')}`",
        f"- X active agents: {resolved.get('X', 0)}",
        f"- batch_count: {resolved.get('batch_count', 0)}",
        f"- calls_per_batch: {resolved.get('calls_per_batch', 0)}",
        f"- budget_valid: `{resolved.get('budget_valid', False)}`",
        "",
        "| batch_id | assignments | roles |",
        "|---|---|---|",
    ]
    for batch in batches[:8]:
        assignments = list(batch.get("assignments", []))
        role_set = sorted({entry.get("role", "") for entry in assignments if entry.get("role")})
        lines.append(
            f"| `{batch.get('batch_id', '')}` | {len(assignments)} | {', '.join(role_set)} |"
        )
    lines.extend(
        [
            "",
        "## Agent Outputs",
        "",
        "| agent_id | title | status | score |",
        "|---|---|---|---|",
        ]
    )
    for result in payload["agent_results"]:
        lines.append(
            f"| `{result['agent_id']}` | {result['title']} | `{result['status']}` | {result['score']} |"
        )
    lines.extend(["", "## Findings", ""])
    for result in payload["agent_results"]:
        lines.append(f"### {result['title']}")
        for finding in result["findings"]:
            lines.append(f"1. {finding}")
        if result["required_changes"]:
            lines.append("Required changes:")
            for change in result["required_changes"]:
                lines.append(f"1. {change}")
        lines.append("")

    lines.extend(["## Decision Log", "", "| decision_id | topic | decision | rationale | owner | timestamp |", "|---|---|---|---|---|---|"])
    for decision in payload["decision_log"]:
        lines.append(
            f"| `{decision['decision_id']}` | `{decision['topic']}` | `{decision['decision']}` | {decision['rationale']} | `{decision['owner']}` | `{decision['timestamp']}` |"
        )

    lines.extend(["", "## Activation Recommendation", ""])
    if status == "approve":
        lines.append("1. Draft is structurally ready for conversion into executable work order.")
    elif status == "approve_with_conditions":
        lines.append("1. Keep as draft. Resolve required changes before executable conversion.")
    else:
        lines.append("1. Do not proceed. Blockers must be resolved before further planning.")

    lines.extend(["", "## Consolidated Required Changes", ""])
    if payload["required_changes"]:
        for item in payload["required_changes"]:
            lines.append(f"1. {item}")
    else:
        lines.append("1. None.")

    lines.append("")
    return "\n".join(lines)

# --- function: _write_json ---
# composed_from=3 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\unclassified\partsfactory\cli.py
def _write_json(path: str | Path, payload: Any) -> Path:
    destination = Path(path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(_to_plain(payload), indent=2, sort_keys=True, ensure_ascii=True), encoding="utf-8")
    return destination

# --- function: build_report ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\build_swarm_concurrency_playbook.py
def build_report(run_paths: list[Path]) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    mode_buckets: dict[str, list[dict[str, Any]]] = {"parallel_default": [], "serialized": []}
    integrity_rows: list[dict[str, Any]] = []
    seen_cycles: set[str] = set()

    for path in run_paths:
        payload = _read_json(path)
        cycle_id = str(payload.get("cycle_id", "")).strip()
        if not cycle_id:
            continue
        summary = payload.get("summary", {}) if isinstance(payload.get("summary", {}), dict) else {}
        row = {
            "run_file": path.name,
            "mode": _mode_from_name(path.name),
            "cycle_id": cycle_id,
            "runtime_median_ms": round(float(summary.get("runtime_median_ms", 0.0) or 0.0), 6),
            "pass_rate": round(float(summary.get("pass_rate", 0.0) or 0.0), 6),
            "focus_required_rate": round(float(summary.get("focus_required_rate", 0.0) or 0.0), 6),
            "fallback_ratio_median": round(float(summary.get("fallback_ratio_median", 0.0) or 0.0), 6),
            "determinism_rate": round(float(summary.get("determinism_rate", 0.0) or 0.0), 6),
        }
        rows.append(row)
        mode_buckets.setdefault(row["mode"], []).append(row)

        if cycle_id not in seen_cycles:
            g4 = _gate_result(cycle_id, "G_SWARM_4_single_writer_integrity")
            g5 = _gate_result(cycle_id, "G_SWARM_5_receipt_chain_integrity")
            integrity_rows.append({"cycle_id": cycle_id, "g4": g4, "g5": g5})
            seen_cycles.add(cycle_id)

    rows = sorted(rows, key=lambda item: item["run_file"])
    parallel = _aggregate(mode_buckets.get("parallel_default", []))
    serialized = _aggregate(mode_buckets.get("serialized", []))
    serialized_runtime = float(serialized.get("runtime_median_ms", 0.0) or 0.0)
    parallel_runtime = float(parallel.get("runtime_median_ms", 0.0) or 0.0)

    if serialized_runtime > 0.0:
        runtime_delta_pct = round(((serialized_runtime - parallel_runtime) / serialized_runtime) * 100.0, 6)
    else:
        runtime_delta_pct = 0.0

    integrity_ok = all(item["g4"]["passed"] and item["g5"]["passed"] for item in integrity_rows)
    if not integrity_ok:
        status = "integrity_regression"
        interpretation = "Single-writer or receipt-chain integrity regressed; do not promote."
    elif runtime_delta_pct > 5.0:
        status = "improved"
        interpretation = "Parallel-default mode is measurably faster while preserving integrity."
    elif runtime_delta_pct < -5.0:
        status = "safety_ok_performance_needs_parallel_executor"
        interpretation = (
            "Integrity is healthy after removing strict one-at-a-time policy, but pilot throughput is not better; "
            "current swarm pilot still executes task slices sequentially."
        )
    else:
        status = "neutral"
        interpretation = "Integrity is healthy and performance is near-neutral under current pilot architecture."

    reference_cycle_id = ""
    for row in rows:
        if row["mode"] == "parallel_default":
            reference_cycle_id = row["cycle_id"]
    if not reference_cycle_id and rows:
        reference_cycle_id = rows[-1]["cycle_id"]

    gate_snapshot = [_gate_result(reference_cycle_id, gate_id) for gate_id in _GATES_CORE] if reference_cycle_id else []

    seed = {
        "rows": rows,
        "parallel": parallel,
        "serialized": serialized,
        "integrity_rows": integrity_rows,
    }
    report_hash = sha256_hex(seed)
    report_id = prefixed_id("swarm_lockcheck", {"hash": report_hash})
    generated_at = deterministic_iso_from_hash(report_hash)

    return {
        "report_id": report_id,
        "generated_at": generated_at,
        "request": "swarm_after_one_at_a_time_removal",
        "runs": rows,
        "aggregates": {
            "parallel_default": parallel,
            "serialized": serialized,
            "delta": {
                "runtime_delta_pct_parallel_vs_serialized": runtime_delta_pct,
            },
        },
        "integrity_checks": integrity_rows,
        "reference_cycle_id": reference_cycle_id,
        "gate_snapshot": gate_snapshot,
        "conclusion": {
            "status": status,
            "integrity_ok": integrity_ok,
            "parallel_runtime_delta_pct_vs_serialized": runtime_delta_pct,
            "interpretation": interpretation,
        },
    }

# --- function: run_meta_review ---
# composed_from=1 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\swarm\partsfactory\run_swarm_meta_review.py
def run_meta_review(program: dict[str, Any], *, budget_inputs: dict[str, Any] | None = None) -> dict[str, Any]:
    results = _run_agents(program)
    status = _quorum_status(results)
    counts = {"approve": 0, "approve_with_conditions": 0, "block": 0}
    for result in results:
        if result.status in counts:
            counts[result.status] += 1
    micro_swarm_plan = _build_micro_swarm_plan(program, budget_inputs or {})
    required_changes = _collect_required_changes(results)
    if not micro_swarm_plan.get("resolved", {}).get("budget_valid", False):
        required_changes.append("Increase Z or reduce L so budget model satisfies X >= 1 and calls_per_batch >= C_min.")
    payload = {
        "review_id": "swarm_meta_review_v1",
        "source_program_id": str(program.get("program_id", "")),
        "execution_mode": "not_enacted",
        "review_mode": "micro_agent_quorum",
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "quorum": {"status": status, "counts": counts},
        "agent_results": [
            {
                "agent_id": result.agent_id,
                "title": result.title,
                "status": result.status,
                "score": result.score,
                "findings": result.findings,
                "required_changes": result.required_changes,
            }
            for result in results
        ],
        "required_changes": required_changes,
        "decision_log": _decision_entries(results),
        "micro_swarm_plan": micro_swarm_plan,
    }
    payload["markdown"] = _to_markdown(payload)
    return payload
