"""
Function canonicals for the `niemeier` family.

3 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- function: cartan_A ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\niemeier\partsfactory\NiemeierSpecs.py
def cartan_A(n: int) -> Matrix:
    A = [[0]*n for _ in range(n)]
    for i in range(n):
        A[i][i] = 2
        if i>0: A[i][i-1] = -1
        if i<n-1: A[i][i+1] = -1
    return [list(map(float, r)) for r in A]

# --- function: cartan_D ---
# composed_from=11 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\niemeier\partsfactory\NiemeierSpecs.py
def cartan_D(n: int) -> Matrix:
    A = [[0]*n for _ in range(n)]
    for i in range(n):
        A[i][i] = 2
    for i in range(n-2):
        A[i][i+1] = A[i+1][i] = -1
    A[n-3][n-1] = A[n-1][n-3] = -1
    return [list(map(float, r)) for r in A]

# --- function: block_diag ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\niemeier\partsfactory\NiemeierSpecs1.py
def block_diag(blocks: List[Matrix]) -> Matrix:
    n = sum(len(b) for b in blocks)
    M = [[0.0]*n for _ in range(n)]
    o = 0
    for B in blocks:
        m = len(B)
        for i in range(m):
            for j in range(m):
                M[o+i][o+j] = B[i][j]
        o += m
    return M
