"""
Constant canonicals for the `agrm` family.

4 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

import logging

import numpy as np

# --- assign: logger ---
# composed_from=497 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_bridge.py
logger = logging.getLogger(__name__)

# --- assign: greedy_baseline_dict ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_cli_allrun.py
greedy_baseline_dict = {
    'pcb442': 18000, 'pr2392': 140000, 'rl5915': 360000,
    'rl11849': 700000, 'usa13509': 820000, 'brd14051': 860000,
    'd15112': 920000, 'pla33810': 2000000, 'pla85900': 5000000
}

# --- assign: optimal_baseline_dict ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_cli_allrun.py
optimal_baseline_dict = {
    'pcb442': 50778, 'pr2392': 378032, 'rl5915': 565530,
    'rl11849': 923288, 'usa13509': 19982859, 'brd14051': 469385,
    'd15112': 736468, 'pla33810': 660489, 'pla85900': 14238241
}

# --- assign: PHI ---
# composed_from=76 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\8a163c7d76bb__Bestbuild101325_2__Best_build_101325__CQE_GVS_MONOLITH.py
PHI = (1 + np.sqrt(5)) / 2
