"""
Function canonicals for the `agrm` family.

10 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

import json
from typing import Any, Dict

# --- function: fnv1a64 ---
# composed_from=19 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\53e25b8d_AGRM_refactored.py
def fnv1a64(data: bytes) -> int:
    h = 0xcbf29ce484222325
    for b in data:
        h ^= b
        h = (h * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return h

# --- function: stable_hash64 ---
# composed_from=19 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\53e25b8d_AGRM_refactored.py
def stable_hash64(key: Any) -> int:
    try:
        b = key if isinstance(key, (bytes, bytearray)) else str(key).encode("utf-8", "ignore")
    except Exception:
        b = repr(key).encode("utf-8", "ignore")
    return fnv1a64(b)

# --- function: quantiles_simple ---
# composed_from=13 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\53e25b8d_AGRM_refactored.py
def quantiles_simple(xs: list, qs=(0.5, 0.9)):
    if not xs:
        return {q: 0 for q in qs}
    s = sorted(xs)
    n = len(s)
    out = {}
    for q in qs:
        idx = max(0, min(n-1, int(q*n)-1))
        out[q] = s[idx]
    return out

    try:
        b = key if isinstance(key, (bytes, bytearray)) else str(key).encode("utf-8", "ignore")
    except Exception:
        b = repr(key).encode("utf-8", "ignore")
    return fnv1a64(b)

# --- function: run_agrm ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_cli_allrun.py
def run_agrm(loader, config_overrides, dataset_name="custom"):
    print(f"\n[RUNNING AGRM TEST] Dataset: {dataset_name}")
    diag = AGRMDiagnosticController()
    for k, v in config_overrides.items():
        diag.set_param(k, v)

    profiler = AGRMProfiler()
    profiler.start_timer()

    navigator = NavigatorGR()
    builder_fwd = BuilderAgent()
    builder_rev = BuilderAgent()
    evaluator = AGRMEvaluator()
    salesman = type('Salesman', (), {
        'scan_path': lambda self: print("[Salesman] Scanning path..."),
        'collect_feedback': lambda self: [{'type': 'reroute_proposal', 'node': 15, 'strain': 0.75}]
    })()

    class FeedbackBus:
        def __init__(self):
            self.queue = []
        def broadcast(self, batch):
            self.queue.extend(batch)
        def collect_all(self):
            batch = self.queue[:]
            self.queue.clear()
            return batch

    feedback_bus = FeedbackBus()

    runtime = AGRMRuntimeController(
        navigator, builder_fwd, builder_rev, evaluator, salesman, feedback_bus
    )

    while True:
        profiler.mark('cycles')
        if runtime.run_cycle():
            break

    profiler.stop_timer()
    print("\n--- AGRM Summary ---")
    profiler.print_report()
    return profiler.report()

# --- function: run_all_tests ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_cli_allrun.py
def run_all_tests():
    all_results = {}
    for name in TSPLIB_DATASETS.keys():
        tsp_path, opt_path = TSPLIB_DATASETS[name]
        os.makedirs("datasets", exist_ok=True)
        download_tsplib_file(os.path.basename(tsp_path), "datasets")
        download_tsplib_file(os.path.basename(opt_path), "datasets")
        loader, config, _ = select_tsp_dataset(name)
        report = run_agrm(loader, config, dataset_name=name)
        all_results[name] = report
    print("\n[ALL AGRM TESTS COMPLETE]")
    return all_results

# --- function: _validate_config ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\53e25b8d_AGRM_refactored.py
def _validate_config(cfg: AGRMConfig):
    if cfg.floors_per_building < 1:
        raise ValueError("floors_per_building must be >= 1")
    if cfg.rooms_per_floor < 2:
        raise ValueError("rooms_per_floor must be >= 2")
    if cfg.phi_scale <= 1.0 and cfg.resize_policy == "phi":
        raise ValueError("phi_scale must be > 1.0 when resize_policy='phi'")
    if not (0.0 < cfg.target_load < 1.0):
        raise ValueError("target_load must be in (0,1)")
    if cfg.promote_hits < 1:
        raise ValueError("promote_hits must be >= 1")
    if cfg.demote_after_idle < 1:
        raise ValueError("demote_after_idle must be >= 1")

# --- function: export_results_to_csv ---
# composed_from=12 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_core.py
def export_results_to_csv(results: Dict[str, Dict], filename: str = "agrm_results.csv"):
    if not results:
        print("[EXPORT] No results to export.")
        return
    with open(filename, mode='w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        headers = ["Dataset", "Cycles", "Runtime (s)", "Feedback Signals"]
        writer.writerow(headers)
        for name, data in results.items():
            row = [name, data.get('cycles'), data.get('runtime_sec'), data.get('feedback_signals')]
            writer.writerow(row)
    print(f"[EXPORT] Results saved to {filename}")

# --- function: export_results_to_json ---
# composed_from=12 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_core.py
def export_results_to_json(results: Dict[str, Dict], filename: str = "agrm_results.json"):
    with open(filename, 'w') as jsonfile:
        json.dump(results, jsonfile, indent=4)
    print(f"[EXPORT] Results saved to {filename}")

# --- function: plot_comparison_graph ---
# composed_from=12 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_core.py
def plot_comparison_graph(results: Dict[str, Dict], greedy_baseline: Dict[str, float], optimal_baseline: Dict[str, float]):
    datasets = list(results.keys())
    agrm_scores = [results[d]['cycles'] for d in datasets]
    greedy_scores = [greedy_baseline.get(d, None) for d in datasets]
    optimal_scores = [optimal_baseline.get(d, None) for d in datasets]

    plt.figure(figsize=(12, 6))
    plt.plot(datasets, agrm_scores, marker='o', label='AGRM (cycles)')
    plt.plot(datasets, greedy_scores, marker='x', linestyle='--', label='Greedy Baseline')
    plt.plot(datasets, optimal_scores, marker='s', linestyle=':', label='Known Optimal')

    plt.title("AGRM vs Greedy vs Optimal Comparison")
    plt.xlabel("Dataset")
    plt.ylabel("Cycle / Tour Cost Metric")
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# --- function: download_tsplib_file ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\agrm\mdhg_hierarchy\agrm_cli_allrun.py
def download_tsplib_file(filename: str, folder: str):
    url_base = "https://people.sc.fsu.edu/~jburkardt/datasets/tsp/"
    full_url = url_base + filename
    local_path = os.path.join(folder, filename)
    if not os.path.exists(local_path):
        print(f"[DOWNLOADING] {filename}...")
        r = requests.get(full_url)
        if r.status_code == 200:
            with open(local_path, 'wb') as f:
                f.write(r.content)
        else:
            print(f"[ERROR] Could not download {filename}: Status {r.status_code}")
    return local_path
