"""
Composed canonical: AGRMController

Family: agrm
Decision: batch=2 id=15
Composition: method-union of 15 variants → 34 methods (48 conflicts resolved), 1 attrs

Auto-generated by place_canonicals.py from the atomic decision queue.
Do not edit by hand — re-run the merger to refresh.
"""
from __future__ import annotations

class AGRMController(BaseController, ControllerContract):
    """ Orchestrates the AGRM TSP solving process using the agent stack. """
    patched = self.patcher.patch_subpath(path, start, end)

    def __init__(self, cities: List[Tuple[float, float]], config: Dict={}, previous_recommendations: Dict={}):
        """
        Initializes the controller and all agents.
        Args:
            cities: List of city coordinates.
            config: Base configuration dictionary.
            previous_recommendations: Parameter adjustments from previous PathAuditAgent run.
        """
        self.cities = cities
        self.num_nodes = len(cities)
        self.config = config.copy()
        if previous_recommendations:
            print(f'CONTROLLER: Applying {len(previous_recommendations)} recommendations from previous run.')
            self.config.update(previous_recommendations)
            print(f'  New Config Snippet: { {k: self.config[k] for k in previous_recommendations}}')
        self.bus = AGRMStateBus(cities, self.config)
        self.navigator = NavigatorGR(cities, self.config)
        self.validator = AGRMEdgeValidator(self.bus, self.config)
        self.mod_controller_agent = ModulationController(self.bus, self.config)
        self.builder_fwd: Optional[PathBuilder] = None
        self.builder_rev: Optional[PathBuilder] = None
        self.salesman = SalesmanValidator(self.bus, self.validator, self.config)
        self.path_audit = PathAuditAgent(self.bus, self.config)
        self.run_stats = {}

    def BROKEN_FUNC_FIX():
        """Minimal controller with phases and snapshotting hooks.
    Implements a sweep→adapt loop: each sweep updates thresholds/policies
    for the next sweep based on measured metrics.
    """

    def calculate_total_path_cost(self, path: Optional[List[int]]) -> float:
        """ Calculates the Euclidean distance of the TSP path. """
        if not path or len(path) < 2:
            return 0.0
        total_distance = 0.0
        for i in range(len(path) - 1):
            idx1, idx2 = (path[i], path[i + 1])
            if 0 <= idx1 < self.num_nodes and 0 <= idx2 < self.num_nodes:
                pos1 = self.cities[idx1]
                pos2 = self.cities[idx2]
                total_distance += math.dist(pos1, pos2)
            else:
                print(f'ERROR: Invalid node index in path during cost calculation: {idx1} or {idx2}')
                return 0.0
        return total_distance

    def get_capabilities(self) -> Dict[str, Any]:
        """Return capabilities."""
        return {'name': 'AGRM', 'type': 'domain', 'operations': list(self._capabilities.keys()), 'db_path': self.db_path}

    def get_knobs(self):
        return self._knobs

    def handle_request(self, request):
        req_type = request.get('type')
        if req_type == 'solve':
            cities = request.get('cities')
            if not cities:
                return {'status': 'error', 'message': "Missing 'cities' list"}
            req_config = request.get('config', {})
            run_config = {**self.agrm_config, **req_config}
            agrm = RealAGRMController(cities, run_config)
            path, stats = agrm.solve()
            return {'status': 'ok', 'path': path, 'stats': stats}
        elif req_type == 'stats':
            return {'status': 'ok', 'knobs': self._knobs}
        else:
            return {'status': 'error', 'message': f'Unknown request type: {req_type}'}

    def run_demo(self, n: int=10000, seed: int=0):
        random.seed(seed)
        for i in range(n):
            self.table.put(f'k{i}', i)
        for i in range(n * 2):
            key = f'k{int(random.random() ** 0.7 * (n - 1))}'
            _ = self.table.get(key)
        self.table.idle_sweep()
        if hasattr(self.table, 'snapshot'):
            self.table.snapshot(f'{self.snap_dir}/agrm_snapshot.json')
        return self.table.stats()

    def run_sweeps(self, sweeps: int=3, n: int=10000, seed: int=0):
        random.seed(seed)
        best = None
        best_score = float('inf')
        history = []
        cfg = self.cfg
        for s in range(sweeps):
            self.table = MDHGHashTable(cfg)
            variants = ['base', 'reverse', 'rot3', 'stride2']
            key_sz = self.cfg.rooms_per_floor
            chosen_variant_log = {}
            cached = self._variant_cache.get(key_sz)
            if cached:
                best_var = cached
                best_var_score = float('inf')
            else:
                best_var = 'base'
                best_var_score = float('inf')
            for v in variants:
                self.table.set_hamiltonian_variant(v)
                nprobe = max(1000, n // 10)
                for i in range(nprobe):
                    self.table.put(f'pv{i}', i)
                for i in range(nprobe):
                    _ = self.table.get(f'pv{i}')
                sprobe = self.table.stats()
                sc = self._score_vector(sprobe)
                if sc < best_var_score:
                    best_var_score, best_var = (sc, v)
                self.table = MDHGHashTable(cfg)
            self._variant_cache[key_sz] = best_var
            chosen_variant_log[key_sz] = best_var
            self.table.set_hamiltonian_variant(best_var)
            for i in range(n):
                self.table.put(f'k{i}', i)
            stuck = 0
            for i in range(n * 2):
                key = f'k{int(random.random() ** 0.7 * (n - 1))}'
                v = self.table.get(key)
                if v is None:
                    stuck += 1
                if stuck > max(100, n // 50):
                    self.table.idle_sweep()
                    stuck = 0
            stats = self.table.stats()
            stats['hamiltonian_variant'] = chosen_variant_log.get(self.cfg.rooms_per_floor)
            hits = self.table.hit_histogram()
            qs = quantiles_simple(hits, qs=(0.5, 0.9))
            stats['median_hits'] = qs.get(0.5, 0)
            stats['p90_hits'] = qs.get(0.9, 0)
            score = self._score_vector(stats)
            history.append({'sweep': s, 'stats': stats, 'score': score})
            if score < best_score:
                best, best_score = (stats, score)
            cfg = self._tune_from_sweeps(stats, cfg)
        Path(self.snap_dir).mkdir(parents=True, exist_ok=True)
        with open(f'{self.snap_dir}/sweep_history.json', 'w', encoding='utf-8') as f:
            json.dump(history, f, indent=2)
        return {'best': best, 'history': history}

    def set_knob(self, name, value):
        if name in self._knobs:
            self._knobs[name] = value
            self.agrm_config[name] = value
            print(f'[AGRM] knob {name} set to {value}')
        else:
            print(f'[AGRM] Unknown knob: {name}')

    def snapshot_pack(self, label: str='final'):
        import os
        os.makedirs(self.snap_dir, exist_ok=True)
        stats = self.table.stats()
        with open(f'{self.snap_dir}/stats_{label}.json', 'w', encoding='utf-8') as f:
            json.dump(stats, f, indent=2)
        tr = self.table.trace_dump()
        head = tr[:5000]
        tail = tr[-5000:] if len(tr) > 5000 else []
        with open(f'{self.snap_dir}/trace_{label}.json', 'w', encoding='utf-8') as f:
            json.dump(head + tail, f, indent=2)
        try:
            with open(f'{self.snap_dir}/best_config.json', 'r', encoding='utf-8') as _src:
                bc = json.load(_src)
            with open(f'{self.snap_dir}/best_config_{label}.json', 'w', encoding='utf-8') as f:
                json.dump(bc, f, indent=2)
        except Exception:
            pass
        with open(f'{self.snap_dir}/README_{label}.txt', 'w', encoding='utf-8') as f:
            f.write('This folder contains AGRM snapshots.\n')
            f.write('stats_*.json: aggregated metrics.\n')
            f.write('trace_*.json: head/tail-sampled trace.\n')
            f.write('best_config_*.json: best thresholds.\n')
            f.write('sweep_history.json: all sweeps summary.\n')

    def solve(self) -> Tuple[Optional[List[int]], Dict]:
        """ Runs the full AGRM TSP solving process, returning path and stats. """
        print(f'\n=== AGRM Controller: Starting Solve for {self.num_nodes} Nodes ===')
        overall_start_time = time.time()
        self.run_stats = {}
        sweep_results = self.navigator.run_sweep()
        self.bus.update_sweep_data(sweep_results)
        if self.bus.start_node_fwd is None or self.bus.start_node_rev is None:
            print('CONTROLLER ERROR: Navigator failed to determine start nodes.')
            return (None, {'error': 'Navigator failed'})
        self.run_stats['sweep_time'] = time.time() - overall_start_time
        self.builder_fwd = PathBuilder('forward', self.bus.start_node_fwd, self.bus, self.validator, self.config)
        self.builder_rev = PathBuilder('reverse', self.bus.start_node_rev, self.bus, self.validator, self.config)
        print('CONTROLLER: Starting Bidirectional Build Phase...')
        build_start_time = time.time()
        max_steps = self.num_nodes * self.config.get('runner_max_step_factor', 3)
        steps = 0
        build_complete = False
        while steps < max_steps:
            steps += 1
            progress_fwd = self.builder_fwd.step() if self.bus.builder_fwd_state['status'] in ['running', 'stalled'] else False
            progress_rev = self.builder_rev.step() if self.bus.builder_rev_state['status'] in ['running', 'stalled'] else False
            self.mod_controller_agent.update_controller_state()
            if self.bus.check_convergence():
                print(f'CONTROLLER: Convergence detected at step {steps}.')
                build_complete = self.bus.merge_paths()
                break
            if self.bus.builder_fwd_state['status'] == 'stalled_hard' and self.bus.builder_rev_state['status'] == 'stalled_hard':
                print('CONTROLLER ERROR: Both builders hard stalled. Attempting merge.')
                build_complete = self.bus.merge_paths()
                break
            if not progress_fwd and (not progress_rev) and (self.bus.builder_fwd_state['status'] not in ['running', 'converged']) and (self.bus.builder_rev_state['status'] not in ['running', 'converged']):
                print(f'CONTROLLER WARNING: No progress from either builder at step {steps}. Stopping build.')
                build_complete = self.bus.merge_paths()
                break
        if steps >= max_steps:
            print(f'CONTROLLER WARNING: Max steps ({max_steps}) reached during build phase.')
            build_complete = self.bus.merge_paths()
        self.run_stats['build_time'] = time.time() - build_start_time
        print(f"CONTROLLER: Build phase finished in {self.run_stats['build_time']:.4f}s ({steps} steps).")
        if self.bus.current_phase == 'patching':
            print('CONTROLLER: Entering patching phase for missed nodes...')
            patch_start_time = time.time()
            print(f'CONTROLLER WARNING: Path construction incomplete, {self.num_nodes - len(set(self.bus.full_path))} nodes missed. Patching logic not fully implemented.')
            build_complete = False
            self.run_stats['patch_time'] = time.time() - patch_start_time
            self.bus.current_phase = 'finalizing'
        if self.bus.full_path:
            print('CONTROLLER: Starting Salesman validation and refinement...')
            salesman_start_time = time.time()
            self.salesman.run_validation_and_patching()
            self.mod_controller_agent.process_salesman_feedback()
            accepted_patches = self.bus.get_accepted_patches()
            if accepted_patches:
                print(f'CONTROLLER: Applying {len(accepted_patches)} accepted patches...')
                spliced_count = 0
                for patch in accepted_patches:
                    if self.bus.splice_patch(patch):
                        spliced_count += 1
                print(f'CONTROLLER: Successfully spliced {spliced_count} patches.')
                self.bus.clear_accepted_patches()
            self.run_stats['salesman_time'] = time.time() - salesman_start_time
            print(f"CONTROLLER: Salesman phase complete in {self.run_stats['salesman_time']:.4f}s.")
        else:
            print('CONTROLLER: No path generated, skipping Salesman validation.')
            self.run_stats['salesman_time'] = 0.0
        print('CONTROLLER: Starting Path Audit...')
        audit_start_time = time.time()
        recommendations = self.path_audit.run_audit()
        self.run_stats['audit_time'] = time.time() - audit_start_time
        print(f"CONTROLLER: Path Audit complete in {self.run_stats['audit_time']:.4f}s.")
        overall_end_time = time.time()
        final_path = self.bus.full_path
        final_cost = self.calculate_total_path_cost(final_path) if final_path else 0.0
        final_stats = {'execution_time': overall_end_time - overall_start_time, 'sweep_time': self.run_stats.get('sweep_time', 0.0), 'build_time': self.run_stats.get('build_time', 0.0), 'patch_time': self.run_stats.get('patch_time', 0.0), 'salesman_time': self.run_stats.get('salesman_time', 0.0), 'audit_time': self.run_stats.get('audit_time', 0.0), 'path_complete': build_complete and bool(final_path) and (len(set(final_path[:-1])) == self.num_nodes), 'visited_nodes': len(set(final_path[:-1])) if final_path else 0, 'path_length_nodes': len(final_path) if final_path else 0, 'salesman_flags': self.salesman.stats.get('flags_generated', 0), 'salesman_proposals': self.salesman.stats.get('proposals_generated', 0), 'total_path_cost': final_cost, 'efficiency': final_cost / max(1, self.num_nodes), 'audit_recommendations': recommendations}
        self.bus.current_phase = 'complete'
        print(f"=== AGRM Controller: Solve Complete in {final_stats['execution_time']:.4f}s ===")
        return (final_path, final_stats)

    def start(self):
        print('[AGRM] Started (your implementation)')

    def stop(self):
        print('[AGRM] Stopped')

    def _apply_inference_rules(self, premises: List[str], goal: str) -> List[Dict]:
        """Apply inference rules to derive steps."""
        steps = []
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('SELECT pattern, transformation, validity_score FROM inference_rules')
        rules = cursor.fetchall()
        conn.close()
        step_num = len(premises) + 1
        for premise in premises:
            if any((word in goal for word in premise.split())):
                steps.append({'step': step_num, 'type': 'inference', 'from': premise, 'to': f'Contributes to: {goal}', 'confidence': 0.9})
                step_num += 1
        steps.append({'step': step_num, 'type': 'conclusion', 'statement': goal, 'confidence': 0.85})
        return steps

    def _are_contradictory(self, stmt1: str, stmt2: str) -> bool:
        """Check if two statements are contradictory."""
        negations = ['not ', 'no ', 'false', 'invalid']
        stmt1_lower = stmt1.lower()
        stmt2_lower = stmt2.lower()
        for neg in negations:
            if neg in stmt1_lower and stmt1_lower.replace(neg, '') in stmt2_lower:
                return True
            if neg in stmt2_lower and stmt2_lower.replace(neg, '') in stmt1_lower:
                return True
        return False

    def _build_inline(self, points):
        """Build InlineHasher from points with sector-based metadata"""
        points = np.asarray(points, dtype=float)
        ih = InlineHasher(dim=points.shape[1], grid=float(self.cfg.get('inline_grid', 32.0)), proj_dims=int(self.cfg.get('inline_proj_dims', 8)), seed=int(self.cfg.get('inline_seed', 17)))
        n = points.shape[0]
        center = points.mean(axis=0)
        vecs = points - center
        angles = np.arctan2(vecs[:, 1], vecs[:, 0])
        num_floors = self.cfg.get('num_sectors', 32)
        sec_edges = np.linspace(-np.pi, np.pi, num_floors + 1)
        sectors = np.digitize(angles, sec_edges) - 1
        for i in range(n):
            meta = {'building': self.cfg.get('building', 'default'), 'floor': f'F{sectors[i]}', 'room': 'R0'}
            ih.insert(i, points[i], meta)
        for i in range(n):
            ih.bump_heat([i])
        dual_export = ih.export_dualwrite()
        for i, h in dual_export['heat'].items():
            self.dual.heat[i] += h
        for a, b, w in dual_export['edges']:
            self.dual.record_edge_weight(a, b, w)
        return ih

    def _build_mdhg(self, points):
        """Build MDHG from points with sector-based metadata"""
        points = np.asarray(points, dtype=float)
        m = MDHG(dim=points.shape[1], decay_lambda=self.cfg.get('mdhg_decay', 0.01))
        n = points.shape[0]
        center = points.mean(axis=0)
        vecs = points - center
        angles = np.arctan2(vecs[:, 1], vecs[:, 0])
        num_floors = self.cfg.get('num_sectors', 32)
        sec_edges = np.linspace(-np.pi, np.pi, num_floors + 1)
        sectors = np.digitize(angles, sec_edges) - 1
        for i in range(n):
            meta = {'building': self.cfg.get('building', 'default'), 'floor': f'F{sectors[i]}', 'room': 'R0'}
            m.insert(i, points[i], meta)
        for i in range(n):
            m.bump_heat([i])
        return m

    def _combine_facts(self, fact1: str, fact2: str) -> Optional[str]:
        """Attempt to combine two facts."""
        words1 = set(fact1.lower().split())
        words2 = set(fact2.lower().split())
        shared = words1 & words2
        if len(shared) > 0:
            return f'Combined: {fact1} AND {fact2}'
        return None

    def _execute_command(self, command: str, payload: Dict) -> Any:
        """Execute command."""
        handler = self._capabilities.get(command)
        if handler:
            return handler(payload)
        else:
            return {'error': f'Unknown command: {command}'}

    def _handle_add_fact(self, payload: Dict) -> Dict[str, Any]:
        """
        Add geometric fact to knowledge base.

        Args:
            payload: {'statement': str, 'source': str, 'e8_coords': list}

        Returns:
            Addition confirmation
        """
        statement = payload.get('statement')
        source = payload.get('source', 'manual')
        e8_coords = payload.get('e8_coords', [])
        fact_id = f'fact_{hash(statement) % 100000}'
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('\n            INSERT OR REPLACE INTO geometric_facts\n            (fact_id, statement, e8_coords, source)\n            VALUES (?, ?, ?, ?)\n        ', (fact_id, statement, json.dumps(e8_coords), source))
        conn.commit()
        conn.close()
        return {'fact_id': fact_id, 'statement': statement, 'added': True}

    def _handle_check_consistency(self, payload: Dict) -> Dict[str, Any]:
        """
        Check consistency of a set of statements.

        Args:
            payload: {'statements': list}

        Returns:
            Consistency report
        """
        statements = payload.get('statements', [])
        contradictions = []
        for i, stmt1 in enumerate(statements):
            for j, stmt2 in enumerate(statements):
                if i < j:
                    if self._are_contradictory(stmt1, stmt2):
                        contradictions.append({'statement_1': stmt1, 'statement_2': stmt2})
        is_consistent = len(contradictions) == 0
        return {'consistent': is_consistent, 'statement_count': len(statements), 'contradictions': contradictions, 'confidence': 1.0 if is_consistent else 0.0}

    def _handle_infer(self, payload: Dict) -> Dict[str, Any]:
        """
        Infer new facts from existing knowledge.

        Args:
            payload: {'from_facts': list, 'depth': int}

        Returns:
            Inferred facts
        """
        from_facts = payload.get('from_facts', [])
        depth = payload.get('depth', 1)
        inferred = []
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('SELECT statement FROM geometric_facts WHERE verified = 1')
        all_facts = [row[0] for row in cursor.fetchall()]
        conn.close()
        all_facts.extend(from_facts)
        for i, fact1 in enumerate(all_facts):
            for j, fact2 in enumerate(all_facts):
                if i < j:
                    combined = self._combine_facts(fact1, fact2)
                    if combined:
                        inferred.append({'from': [fact1, fact2], 'inferred': combined, 'confidence': 0.75})
        return {'input_facts': len(from_facts), 'inferred_facts': inferred, 'inference_depth': depth}

    def _handle_prove(self, payload: Dict) -> Dict[str, Any]:
        """
        Attempt to prove a statement.

        Args:
            payload: {'statement': str, 'axioms': list}

        Returns:
            Proof attempt result
        """
        statement = payload.get('statement')
        axioms = payload.get('axioms', [])
        reasoning_result = self._handle_reason({'premises': axioms, 'goal': statement})
        is_proven = reasoning_result['confidence'] > 0.9
        return {'statement': statement, 'proven': is_proven, 'confidence': reasoning_result['confidence'], 'proof_chain': reasoning_result['chain_id'], 'steps': reasoning_result['steps'], 'axioms_used': axioms}

    def _handle_query(self, command: ControllerCommand) -> Dict[str, Any]:
        """Handle query."""
        query_type = command.payload.get('query_type')
        if query_type == 'stats':
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            cursor.execute('SELECT COUNT(*) FROM reasoning_chains')
            chain_count = cursor.fetchone()[0]
            cursor.execute('SELECT COUNT(*) FROM geometric_facts')
            fact_count = cursor.fetchone()[0]
            cursor.execute('SELECT COUNT(*) FROM inference_rules')
            rule_count = cursor.fetchone()[0]
            conn.close()
            return {'reasoning_chains': chain_count, 'geometric_facts': fact_count, 'inference_rules': rule_count, 'capabilities': list(self._capabilities.keys())}
        else:
            raise ValueError(f'Unknown query type: {query_type}')

    def _handle_query_facts(self, payload: Dict) -> List[Dict]:
        """
        Query geometric facts.

        Args:
            payload: {'keyword': str, 'verified_only': bool}

        Returns:
            Matching facts
        """
        keyword = payload.get('keyword', '')
        verified_only = payload.get('verified_only', False)
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        if keyword and verified_only:
            cursor.execute('\n                SELECT fact_id, statement, e8_coords, verified\n                FROM geometric_facts\n                WHERE statement LIKE ? AND verified = 1\n            ', (f'%{keyword}%',))
        elif keyword:
            cursor.execute('\n                SELECT fact_id, statement, e8_coords, verified\n                FROM geometric_facts\n                WHERE statement LIKE ?\n            ', (f'%{keyword}%',))
        elif verified_only:
            cursor.execute('\n                SELECT fact_id, statement, e8_coords, verified\n                FROM geometric_facts\n                WHERE verified = 1\n            ')
        else:
            cursor.execute('\n                SELECT fact_id, statement, e8_coords, verified\n                FROM geometric_facts\n            ')
        results = []
        for row in cursor.fetchall():
            results.append({'fact_id': row[0], 'statement': row[1], 'e8_coords': json.loads(row[2]) if row[2] else [], 'verified': bool(row[3])})
        conn.close()
        return results

    def _handle_reason(self, payload: Dict) -> Dict[str, Any]:
        """
        Perform geometric reasoning from premises.

        Args:
            payload: {'premises': list, 'goal': str}

        Returns:
            Reasoning chain
        """
        premises = payload.get('premises', [])
        goal = payload.get('goal', '')
        chain_id = f'chain_{hash(str(premises) + goal) % 10000}'
        steps = []
        current_confidence = 1.0
        for i, premise in enumerate(premises):
            steps.append({'step': i + 1, 'type': 'premise', 'statement': premise, 'confidence': 1.0})
        inferred_steps = self._apply_inference_rules(premises, goal)
        steps.extend(inferred_steps)
        for step in inferred_steps:
            current_confidence *= step.get('confidence', 0.9)
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('\n            INSERT OR REPLACE INTO reasoning_chains\n            (chain_id, premises, conclusion, steps, confidence)\n            VALUES (?, ?, ?, ?, ?)\n        ', (chain_id, json.dumps(premises), goal, json.dumps(steps), current_confidence))
        conn.commit()
        conn.close()
        return {'chain_id': chain_id, 'premises': premises, 'conclusion': goal, 'steps': steps, 'confidence': current_confidence, 'complete': current_confidence > 0.8}

    def _handle_validate_chain(self, payload: Dict) -> Dict[str, Any]:
        """
        Validate a reasoning chain.

        Args:
            payload: {'chain_id': str}

        Returns:
            Validation result
        """
        chain_id = payload.get('chain_id')
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('\n            SELECT steps, confidence FROM reasoning_chains\n            WHERE chain_id = ?\n        ', (chain_id,))
        row = cursor.fetchone()
        conn.close()
        if not row:
            return {'valid': False, 'error': 'Chain not found'}
        steps = json.loads(row[0])
        confidence = row[1]
        valid_steps = 0
        for step in steps:
            if step.get('confidence', 0) > 0.7:
                valid_steps += 1
        is_valid = valid_steps == len(steps) and confidence > 0.8
        return {'chain_id': chain_id, 'valid': is_valid, 'steps_valid': valid_steps, 'total_steps': len(steps), 'confidence': confidence}

    def _init_db(self):
        """Initialize database."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('\n            CREATE TABLE IF NOT EXISTS reasoning_chains (\n                chain_id TEXT PRIMARY KEY,\n                premises TEXT,\n                conclusion TEXT,\n                steps TEXT,\n                confidence REAL,\n                verified BOOLEAN DEFAULT 0,\n                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n            )\n        ')
        cursor.execute('\n            CREATE TABLE IF NOT EXISTS inference_rules (\n                rule_id TEXT PRIMARY KEY,\n                name TEXT,\n                pattern TEXT,\n                transformation TEXT,\n                validity_score REAL\n            )\n        ')
        cursor.execute('\n            CREATE TABLE IF NOT EXISTS geometric_facts (\n                fact_id TEXT PRIMARY KEY,\n                statement TEXT,\n                e8_coords TEXT,\n                verified BOOLEAN DEFAULT 0,\n                source TEXT\n            )\n        ')
        conn.commit()
        conn.close()

    def _init_tasks(self):
        """Initialize task controllers."""
        pass

    def _metrics_brief(self):
        """Generate brief metrics summary"""
        ticks = max(1, int(self.bus.stats.get('ticks', 1)))
        steps = max(1, int(self.bus.stats.get('steps', 1)))
        thrash = float(self.bus.stats.get('thrash', 0.0))
        coverage = float(self.bus.stats.get('coverage_gain', 0.0))
        return {'thrash_per_step': thrash / steps, 'coverage_rate': coverage / ticks, 'sectors_visited': int(self.bus.stats.get('sectors_visited', 0)), 'ticks': ticks, 'steps': steps}

    def _promotion_check(self, points, sample_ticks: int=3):
        """Run a tiny MDHG solve to compare core metrics"""
        old_bus = self.bus
        old_nav = self.navigator
        old_inline = self.inline
        old_mdhg = self.mdhg
        try:
            from .statebus import StateBus
            from .navigator import NavigatorGR
            from .vws_bridge import seed_vws_from_mdhg
            from .mdhg import MDHG
            self.bus = StateBus()
            self.navigator = NavigatorGR(self.cfg, self.bus)
            m = self._build_mdhg(points)
            self.mdhg = m
            self.bus.vws = seed_vws_from_mdhg(m, points, building=self.cfg.get('building', 'default'), k_each=self.cfg.get('vws_k', 5), top_edges=self.cfg.get('vws_edges', 128))
            _ = self.navigator.assign_shells_and_sectors(points)
            for _ in range(sample_ticks):
                _ = self.navigator.sweep_step(points)
            sample_metrics = self._metrics_brief()
            return sample_metrics
        finally:
            self.bus = old_bus
            self.navigator = old_nav
            self.inline = old_inline
            self.mdhg = old_mdhg

    def _register_capabilities(self):
        """Register capabilities."""
        self._capabilities.update({'reason': self._handle_reason, 'prove': self._handle_prove, 'check_consistency': self._handle_check_consistency, 'infer': self._handle_infer, 'validate_chain': self._handle_validate_chain, 'add_fact': self._handle_add_fact, 'query_facts': self._handle_query_facts})

    def _score_vector(self, s: dict) -> float:
        size = max(1, s.get('size', 1))
        load = s.get('load', 0.0)
        move_rate = s.get('moves', 0) / size
        pro = s.get('promotions', 0) / size
        demo = s.get('demotions', 0) / size
        imb = abs(pro - demo)
        time_proxy = s.get('lookups', 1) / size
        sh = s.get('shortcuts', {}).get('hits', 0)
        sl = s.get('shortcuts', {}).get('misses', 1)
        shortcut_eff = sh / max(1, sh + sl)
        return 0.5 * load + 0.3 * move_rate + 0.4 * imb + 0.3 * time_proxy - 0.2 * shortcut_eff

    def _tune_from_sweeps(self, prev_stats: dict, prev_cfg: AGRMConfig) -> AGRMConfig:
        pro = prev_stats.get('promotions', 0)
        demo = prev_stats.get('demotions', 0)
        size = max(1, prev_stats.get('size', 1))
        pro_rate = pro / size
        demo_rate = demo / size
        med = int(prev_stats.get('median_hits', 0))
        p90 = int(prev_stats.get('p90_hits', 0))
        base_promote = p90 if p90 > 0 else prev_cfg.promote_hits
        new_promote = max(2, base_promote)
        load = prev_stats.get('load', 0.0)
        new_phi = min(2.0, max(1.3, prev_cfg.phi_scale * (1.05 if load > prev_cfg.target_load else 0.97)))
        new_idle = max(5, med if med > 0 else prev_cfg.demote_after_idle)
        alpha = 0.6
        sm_phi = prev_cfg.phi_scale * (1 - alpha) + new_phi * alpha
        sm_promote = int(prev_cfg.promote_hits * (1 - alpha) + new_promote * alpha)
        sm_idle = int(prev_cfg.demote_after_idle * (1 - alpha) + new_idle * alpha)
        return AGRMConfig(phi_scale=sm_phi, target_load=prev_cfg.target_load, floors_per_building=prev_cfg.floors_per_building, rooms_per_floor=prev_cfg.rooms_per_floor, promote_hits=sm_promote, demote_after_idle=sm_idle, decay_rate=prev_cfg.decay_rate, enable_shortcuts=prev_cfg.enable_shortcuts, trace_limit=prev_cfg.trace_limit, resize_policy=prev_cfg.resize_policy)
