"""
AUTO-MERGED canonical from 8 variant(s). Function-union strategy.
Generated by _scripts/merge_variants.py.

Source variants:
  - D:/PartsFactory/Unification Prototypes/tools/tmn/tmn_core.py
  - D:/Manny Unification 2/datasets from previous review/CMPLX-TMN1/retooling/src/retooling/geometry/tmn_core.py
  - D:/Manny Unification 2/datasets from previous review/CMPLX-TMN1/tmn1-v2/shared/geometry/tmn_core.py
  - D:/Manny Unification 2/historical builds/CMPLX-TMN1/tmn1-v2/shared/geometry/tmn_core.py
  - D:/Manny Unification 2/historical builds/CMPLX-TMN1/retooling/src/retooling/geometry/tmn_core.py
  - D:/Manny Unification 2/historical builds/Builds/Retooling/src/retooling/geometry/tmn_core.py
  - D:/Manny Unification 2/historical builds/CMPLX-TMN1/intake-review/Start Here/Retooling/src/retooling/geometry/tmn_core.py
  - D:/Manny Unification 2/datasets from previous review/CMPLX-TMN1/intake-review/Start Here/Retooling/src/retooling/geometry/tmn_core.py

Merge stats: {'imports_union': 8, 'definitions_merged': 10, 'names_with_conflicts': 4, 'has_trailing_main': False}
"""


"""AUTO-MERGED canonical from 2 variant(s). Function-union strategy.
Generated by _scripts/merge_variants.py.

Source variants:
  - D:/PartsFactory/Unification Prototypes/tools/tmn/8e2eed19_tmn_core.py
  - D:/PartsFactory/Unification Prototypes/tools/tmn/tmn_core.py

Merge stats: {'imports_union': 8, 'definitions_merged': 9, 'names_with_conflicts': 0, 'has_trailing_main': False}"""


from core.legacy_stubs import build_module_getattr
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Tuple, Any
import hashlib
import json
import logging
import numpy as np


@dataclass
class ChannelState:
    """State of one parity channel in the manifold."""
    channel_id: int = 0
    policy_type: int = 1              # 1-8 matching PolicyChannel enum
    # Blocks managed by this channel
    block_indices: List[Tuple[int, int]] = field(default_factory=list)
    # Self-tuning
    local_lr: float = 0.001
    local_prune_threshold: float = 0.03
    # Health
    energy: float = 0.0
    sparsity: float = 0.0
    stability: float = 1.0
    update_count: int = 0
    repair_count: int = 0
    energy_history: List[float] = field(default_factory=list)
    max_history: int = 50


@dataclass
class ExpertModule:
    """Specialized expert module (post-critical period)."""
    name: str
    domain: str  # 'auditor', 'healer', 'expander', etc.
    weights: np.ndarray
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    specialization_score: float = 0.0


class Manifold:
    """
    Block-structured weight manifold with embedded micro-controllers.

    The 24D Leech lattice is built from 4D blocks. Each block has a
    MicroController that self-heals, self-learns, and self-monitors.

    Agents can:
      - Operate at different resolutions (4D, 8D, 24D)
      - Merge block-by-block (two agents combining specific competencies)
      - Split cleanly (agent forks take specific blocks)
      - Read/write to the Master TMN at block granularity
      - Trust that each block maintains its own health
    """

    def __init__(self, dims: int = 24, block_size: int = 4):
        self.dims = dims
        self.block_size = block_size
        self.n_blocks = dims // block_size  # 6 blocks for 24D/4D
        self.weights = np.random.randn(dims, dims) * np.sqrt(2.0 / dims)
        self._tick_count = 0

        # 10 channels: 4 right-chiral + 4 left-chiral + 2 parity (8b/10b)
        # RIGHT chiral (generative): write to W upper triangle. Creates, learns, explores.
        # LEFT chiral (recall): read from W^T lower triangle. Retrieves, verifies, stabilizes.
        # Chirality separates creation from memory — prevents catastrophic forgetting.
        all_blocks = [(i, j) for i in range(self.n_blocks) for j in range(self.n_blocks)]

        # Upper triangle + diagonal → right-chiral (generative)
        right_blocks = [(i, j) for i, j in all_blocks if j >= i]
        # Lower triangle + diagonal → left-chiral (recall)
        left_blocks = [(i, j) for i, j in all_blocks if i >= j]
        self.channels: List[MicroController] = []

        # 4 right-chiral channels (generative: higher LR for exploration)
        for ch in range(4):
            stripe = [right_blocks[k] for k in range(len(right_blocks)) if k % 4 == ch]
            ctrl = MicroController(
                channel_id=ch, block_indices=stripe,
                policy_type=ch + 1, is_parity=False, block_size=block_size
            )
            ctrl.state.local_lr = 0.0015  # generative: faster learning
            self.channels.append(ctrl)

        # 4 left-chiral channels (recall: lower LR for stability)
        for ch in range(4):
            stripe = [left_blocks[k] for k in range(len(left_blocks)) if k % 4 == ch]
            ctrl = MicroController(
                channel_id=4 + ch, block_indices=stripe,
                policy_type=ch + 5, is_parity=False, block_size=block_size
            )
            ctrl.state.local_lr = 0.0005  # recall: stable retrieval
            self.channels.append(ctrl)

        # 2 parity channels — cross-check chirality coherence
        self.channels.append(MicroController(
            channel_id=8, block_indices=[], policy_type=1,
            is_parity=True, block_size=block_size
        ))
        self.channels.append(MicroController(
            channel_id=9, block_indices=[], policy_type=2,
            is_parity=True, block_size=block_size
        ))

        # 3-tick chiral rotation:
        # tick%3==0: RIGHT channels 0,1,2,3 (generative — create, learn, write)
        # tick%3==1: LEFT channels 4,5,6,7 (recall — retrieve, verify, stabilize)
        # tick%3==2: PARITY 8,9 (cross-check: is generation coherent with recall?)
        self._rotation = {
            0: [0, 1, 2, 3],       # right-chiral: generative
            1: [4, 5, 6, 7],       # left-chiral: recall
            2: [8, 9],             # parity: coherence check
        }

    @property
    def blocks(self) -> List[np.ndarray]:
        """View weights as n_blocks x n_blocks grid of block_size x block_size matrices."""
        bs = self.block_size
        result = []
        for i in range(self.n_blocks):
            row = []
            for j in range(self.n_blocks):
                row.append(self.weights[i*bs:(i+1)*bs, j*bs:(j+1)*bs])
            result.append(row)
        return result

    def get_block(self, i: int, j: int) -> np.ndarray:
        """Get a specific block from the weight matrix."""
        bs = self.block_size
        return self.weights[i*bs:(i+1)*bs, j*bs:(j+1)*bs].copy()

    def set_block(self, i: int, j: int, block: np.ndarray):
        """Set a specific block in the weight matrix."""
        bs = self.block_size
        self.weights[i*bs:(i+1)*bs, j*bs:(j+1)*bs] = block

    def merge_from(self, other: "Manifold", block_indices: Optional[List[Tuple[int,int]]] = None,
                   alpha: float = 0.5):
        """Merge blocks from another manifold into this one.

        block_indices: list of (i,j) blocks to merge. None = all blocks.
        alpha: blend factor. 0 = keep self, 1 = take other.
        """
        if block_indices is None:
            block_indices = [(i, j) for i in range(self.n_blocks)
                             for j in range(self.n_blocks)]
        for i, j in block_indices:
            my_block = self.get_block(i, j)
            their_block = other.get_block(i, j)
            blended = (1 - alpha) * my_block + alpha * their_block
            self.set_block(i, j, blended)

    def split(self, block_indices: List[Tuple[int,int]]) -> "Manifold":
        """Create a new Manifold containing only the specified blocks.
        Other blocks are zeroed — the split agent only gets specific competencies.
        """
        child = Manifold(self.dims, self.block_size)
        child.weights = np.zeros_like(self.weights)
        for i, j in block_indices:
            child.set_block(i, j, self.get_block(i, j))
        return child

    def block_norms(self) -> np.ndarray:
        """Frobenius norm of each block — shows where knowledge is concentrated."""
        norms = np.zeros((self.n_blocks, self.n_blocks))
        for i in range(self.n_blocks):
            for j in range(self.n_blocks):
                norms[i, j] = np.linalg.norm(self.get_block(i, j))
        return norms

    def tick(self):
        """Run channels on 3-tick rotation. Only ~3-4 channels fire per tick.

        tick%3==0: data channels 0,1,2 — observe, heal, tune
        tick%3==1: data channels 3,4,5 — observe, heal, tune
        tick%3==2: data channels 6,7 + parity 8,9 — observe, heal, parity check

        This is error-correcting cadence: every block gets checked every 3 ticks.
        Parity channels fire on the last beat and cross-check all data channels.
        """
        self._tick_count += 1
        phase = self._tick_count % 3
        active_ids = self._rotation[phase]

        for ch_id in active_ids:
            ch = self.channels[ch_id]

            if ch.is_parity:
                # Parity channel: check all data channels for instability
                data_channels = [c for c in self.channels if not c.is_parity]
                unstable = ch.parity_check(data_channels)
                if unstable:
                    # Force-heal unstable channels on next tick
                    for uch_id in unstable:
                        uch = self.channels[uch_id]
                        blocks = {idx: self.get_block(*idx) for idx in uch.state.block_indices}
                        healed = uch.heal(blocks, self._safe_get_block)
                        for idx, hblock in healed.items():
                            self.set_block(*idx, hblock)
            else:
                # Data channel: observe and heal its block stripe
                blocks = {idx: self.get_block(*idx) for idx in ch.state.block_indices}
                ch.observe(blocks)
                healed = ch.heal(blocks, self._safe_get_block)
                for idx, hblock in healed.items():
                    self.set_block(*idx, hblock)
                ch.tune_lr()

    def _safe_get_block(self, i: int, j: int) -> Optional[np.ndarray]:
        """Get block, returning None if out of bounds."""
        if 0 <= i < self.n_blocks and 0 <= j < self.n_blocks:
            return self.get_block(i, j)
        return None

    def health_report(self) -> Dict[str, Any]:
        """Aggregate health from all 10 channels."""
        data_reports = [ch.health_report() for ch in self.channels if not ch.is_parity]
        parity_reports = [ch.health_report() for ch in self.channels if ch.is_parity]
        avg_stability = np.mean([r["stability"] for r in data_reports]) if data_reports else 1.0
        total_repairs = sum(r["repairs"] for r in data_reports)
        min_stability = min((r["stability"] for r in data_reports), default=1.0)
        weakest = min(data_reports, key=lambda r: r["stability"]) if data_reports else {}
        return {
            "n_channels": len(self.channels),
            "data_channels": len(data_reports),
            "parity_channels": len(parity_reports),
            "tick": self._tick_count,
            "phase": self._tick_count % 3,
            "avg_stability": round(float(avg_stability), 4),
            "min_stability": round(float(min_stability), 4),
            "total_repairs": total_repairs,
            "weakest_channel": weakest,
        }

    def get_block_lr(self, i: int, j: int) -> float:
        """Get the channel's tuned LR for the block at (i,j)."""
        for ch in self.channels:
            if not ch.is_parity and (i, j) in ch.state.block_indices:
                return ch.state.local_lr
        return 0.001

    def resolution(self, level: int = 1) -> np.ndarray:
        """View the manifold at different resolutions.
        level=1: full dims x dims
        level=2: n_blocks x n_blocks (block norms)
        level=3: scalar (total norm)
        """
        if level <= 1:
            return self.weights
        elif level == 2:
            return self.block_norms()
        else:
            return np.array([[np.linalg.norm(self.weights)]])

    def grow(self, new_dims: int) -> "Manifold":
        """Grow to larger dimensionality, preserving existing blocks."""
        grown = Manifold(new_dims, self.block_size)
        grown.weights = np.random.randn(new_dims, new_dims) * np.sqrt(2.0 / new_dims)
        min_d = min(self.dims, new_dims)
        grown.weights[:min_d, :min_d] = self.weights[:min_d, :min_d]
        return grown


class MicroController:
    """
    Self-healing channel controller — one per parity channel, not per block.

    8 data channels + 2 parity channels = 10 total (8b/10b encoding).
    Each channel manages a stripe of blocks in the manifold.
    Channels fire on a 3-tick rotation (error-correcting cadence):
      tick % 3 == 0: channels 0,1,2 fire (observe + heal)
      tick % 3 == 1: channels 3,4,5 fire
      tick % 3 == 2: channels 6,7 + parity 8,9 fire

    The parity channels don't manage blocks — they check the data channels.
    If a data channel reports instability, the parity channel triggers repair
    using the error-correcting properties of the Golay code structure.

    Constants (from policy_channel.py):
      PARITY_CHANNEL_COUNT = 8   (data channels)
      GOLAY_CODE_LENGTH = 24     (TMN dims)
      HAMMING_CODE_LENGTH = 7    (every 3rd tick)
      CONWAY_FRAME_SIZE = 4      (block size)
    """

    def __init__(self, channel_id: int, block_indices: List[Tuple[int, int]],
                 policy_type: int = 1, is_parity: bool = False, block_size: int = 4):
        self.state = ChannelState(
            channel_id=channel_id,
            policy_type=policy_type,
            block_indices=block_indices,
        )
        self.is_parity = is_parity
        self.block_size = block_size
        self._snapshots: Dict[Tuple[int,int], np.ndarray] = {}
        self._max_norm = 5.0
        self._min_norm = 0.01
        self._max_drift = 0.5

    def observe(self, blocks: Dict[Tuple[int,int], np.ndarray]):
        """Observe all blocks in this channel's stripe."""
        total_energy = 0.0
        total_sparsity = 0.0
        min_stability = 1.0
        n = len(blocks)

        for (i, j), block in blocks.items():
            energy = float(np.linalg.norm(block))
            sparsity = float(np.mean(np.abs(block) < 1e-6))
            total_energy += energy
            total_sparsity += sparsity

            # Drift detection
            prev = self._snapshots.get((i, j))
            if prev is not None:
                drift = float(np.linalg.norm(block - prev))
                stab = max(0, 1.0 - drift / self._max_drift)
                min_stability = min(min_stability, stab)
            self._snapshots[(i, j)] = block.copy()

        self.state.energy = total_energy / max(n, 1)
        self.state.sparsity = total_sparsity / max(n, 1)
        self.state.stability = min_stability
        self.state.energy_history.append(self.state.energy)
        if len(self.state.energy_history) > self.state.max_history:
            self.state.energy_history.pop(0)

    def heal(self, blocks: Dict[Tuple[int,int], np.ndarray],
             all_blocks_getter) -> Dict[Tuple[int,int], np.ndarray]:
        """Heal all blocks in this channel's stripe. Returns healed blocks."""
        healed = {}
        for (i, j), block in blocks.items():
            fixed = block.copy()
            repaired = False

            # Fix NaN/Inf from neighbor interpolation
            bad = ~np.isfinite(fixed)
            if np.any(bad):
                neighbors = []
                for di, dj in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                    try:
                        nb = all_blocks_getter(i + di, j + dj)
                        if nb is not None:
                            neighbors.append(nb)
                    except (IndexError, KeyError):
                        pass
                if neighbors:
                    fixed[bad] = np.mean(neighbors, axis=0)[bad]
                else:
                    fixed[bad] = 0.0
                repaired = True

            # Norm clipping
            norm = np.linalg.norm(fixed)
            if norm > self._max_norm:
                fixed *= self._max_norm / norm
                repaired = True

            # Stability dampening
            prev = self._snapshots.get((i, j))
            if self.state.stability < 0.3 and prev is not None:
                fixed = 0.7 * fixed + 0.3 * prev
                repaired = True

            if repaired:
                self.state.repair_count += 1
            healed[(i, j)] = fixed

        self.state.update_count += 1
        return healed

    def tune_lr(self) -> float:
        """Self-tune LR from energy trend."""
        if len(self.state.energy_history) < 5:
            return self.state.local_lr
        recent = self.state.energy_history[-5:]
        trend = recent[-1] - recent[0]
        if trend > 0.5:
            self.state.local_lr *= 0.9
        elif trend < -0.1 and self.state.stability > 0.7:
            self.state.local_lr *= 1.05
        self.state.local_lr = max(1e-6, min(0.01, self.state.local_lr))
        return self.state.local_lr

    def parity_check(self, data_channels: List["MicroController"]) -> List[int]:
        """Parity channel: check data channels for instability. Returns list of unstable channel IDs."""
        unstable = []
        for ch in data_channels:
            if ch.state.stability < 0.5:
                unstable.append(ch.state.channel_id)
        return unstable

    def health_report(self) -> Dict[str, Any]:
        return {
            "channel": self.state.channel_id,
            "policy": self.state.policy_type,
            "is_parity": self.is_parity,
            "blocks": len(self.state.block_indices),
            "energy": round(self.state.energy, 4),
            "sparsity": round(self.state.sparsity, 4),
            "stability": round(self.state.stability, 4),
            "local_lr": round(self.state.local_lr, 6),
            "updates": self.state.update_count,
            "repairs": self.state.repair_count,
        }


class TriadicManifoldNetwork:
    """
    Self-improving neural network using triadic constraints.
    
    Architecture:
    - 24D initial (Niemeier/Leech lattice)
    - Dynamic growth (increments of 8, E8 structure)
    - Critical period at epoch 300 (scale-3)
    - Expert modules post-hardening
    """
    
    def __init__(
        self,
        init_dims: int = 24,
        max_dims: int = 96,
        growth_increment: int = 8,
        prune_threshold: float = 0.03,
        critical_epoch: int = 300
    ):
        self.init_dims = init_dims
        self.max_dims = max_dims
        self.dims = init_dims
        self.growth_increment = growth_increment
        self.prune_threshold = prune_threshold
        self.critical_epoch = critical_epoch
        self.generation = 0
        self.crystallization_threshold = 0.5  # triadic energy must be below this
        self.crystallized = False
        self.glyph = None  # set when crystallized

        # Manifold — block-structured weight space
        self.manifold = Manifold(self.dims, block_size=4)

        # Triadic constraints
        self.triads = TriadicState()

        # State tracking
        self.epoch = 0
        self.frozen = False
        self.experts: List[ExpertModule] = []
        self.mi_history: List[float] = []
        self.sparsity_history: List[float] = []
        
        # Learning metrics
        self.hebbian_lr = 0.001
        self.mutual_information = 0.0

    @property
    def weights(self) -> np.ndarray:
        """Delegate to manifold — all existing code works unchanged."""
        return self.manifold.weights

    @weights.setter
    def weights(self, value: np.ndarray):
        self.manifold.weights = value

    def encode_code(self, code: str) -> np.ndarray:
        """Encode code snippet into manifold representation."""
        # Hash-based encoding for reproducibility
        code_hash = hashlib.sha256(code.encode()).hexdigest()
        np.random.seed(int(code_hash[:16], 16) % (2**32))
        
        # Generate 24D representation
        encoding = np.random.randn(self.dims)
        encoding = encoding / (np.linalg.norm(encoding) + 1e-8)
        
        return encoding
    
    def forward(self, x: np.ndarray) -> np.ndarray:
        """Forward pass with triadic modulation."""
        # Ensure correct dimensionality
        if len(x) != self.dims:
            x = np.pad(x, (0, self.dims - len(x))) if len(x) < self.dims else x[:self.dims]
        
        # Clip for stability
        x = np.clip(x, -10, 10)
        
        # Right-chiral forward: W @ x (generative direction)
        h = np.tanh(self.weights @ x)

        # Triadic modulation
        triad_gate = self._compute_triad_gate()

        return h * (1 + 0.1 * triad_gate)

    def recall(self, x: np.ndarray) -> np.ndarray:
        """Left-chiral pass: W^T @ x. Retrieves from memory without modifying it.

        Use this for queries, lookups, similarity checks — any read operation.
        The transpose of the weight matrix projects into the recall space,
        which is structurally different from the generative space.
        """
        if len(x) != self.dims:
            x = np.pad(x, (0, self.dims - len(x))) if len(x) < self.dims else x[:self.dims]
        x = np.clip(x, -10, 10)
        # Left-chiral: W^T @ x (recall direction)
        h = np.tanh(self.weights.T @ x)
        triad_gate = self._compute_triad_gate()
        return h * (1 + 0.1 * triad_gate)

    def chirality_coherence(self, x: np.ndarray) -> float:
        """Measure how coherent generation and recall are for input x.

        Returns cosine similarity between forward(x) and recall(x).
        High coherence (>0.5): what you generate, you can recall — grounded.
        Low coherence (<0.2): generation has diverged from memory — hallucinating.
        Negative coherence: generation and recall contradict — critical instability.
        """
        gen = self.forward(x)
        rec = self.recall(x)
        dot = np.dot(gen, rec)
        norms = np.linalg.norm(gen) * np.linalg.norm(rec)
        return float(dot / (norms + 1e-8))

    def _compute_triad_gate(self) -> float:
        """Compute triadic modulation factor."""
        n_mod = np.trace(self.triads.noether) / (np.linalg.norm(self.triads.noether) + 1e-8)
        s_mod = np.trace(self.triads.shannon) / (np.linalg.norm(self.triads.shannon) + 1e-8)
        l_mod = np.trace(self.triads.landauer) / (np.linalg.norm(self.triads.landauer) + 1e-8)
        
        return (n_mod + s_mod + l_mod) / 3.0
    
    def learn(self, input_data: str, output_data: str) -> Dict:
        """
        Hebbian learning from input-output pairs.
        Returns learning metrics.
        """
        if self.frozen:
            return {"status": "frozen", "epoch": self.epoch}
        
        # Encode to manifold
        x = self.encode_code(input_data)
        y_target = self.encode_code(output_data)
        
        # Forward pass
        y_pred = self.forward(x)
        
        # Hebbian update (fire together, wire together)
        self._hebbian_update(x, y_pred)
        
        # Update triads
        self._update_triads(x, y_pred)
        
        # Calculate mutual information proxy
        mi = np.corrcoef(y_pred, y_target)[0, 1] if len(y_pred) == len(y_target) else 0
        self.mutual_information = 0.9 * self.mutual_information + 0.1 * mi
        self.mi_history.append(self.mutual_information)
        
        # Check for growth
        grew = self._check_growth()
        
        # Increment epoch
        self.epoch += 1
        
        # Check critical period
        if self.epoch == self.critical_epoch:
            self._critical_period_pruning()
        
        return {
            "epoch": self.epoch,
            "mutual_information": float(self.mutual_information),
            "triadic_energy": float(self.triads.energy()),
            "sparsity": self._calculate_sparsity(),
            "grew": grew,
            "frozen": self.frozen
        }
    
    def _hebbian_update(self, x: np.ndarray, y: np.ndarray):
        """Apply Hebbian learning rule with per-block adaptive learning rates."""
        x_norm = x / (np.linalg.norm(x) + 1e-8)
        y_norm = y / (np.linalg.norm(y) + 1e-8)

        # Block-aware update: each block uses its micro-controller's tuned LR
        bs = self.manifold.block_size
        for bi in range(self.manifold.n_blocks):
            for bj in range(self.manifold.n_blocks):
                lr = self.manifold.get_block_lr(bi, bj)
                xi = x_norm[bi*bs:(bi+1)*bs]
                yj = y_norm[bj*bs:(bj+1)*bs]
                if len(xi) == bs and len(yj) == bs:
                    dW = lr * np.outer(yj, xi)
                    block = self.manifold.get_block(bi, bj)
                    self.manifold.set_block(bi, bj, block + dW)

        # Run micro-controllers (self-heal, observe, tune)
        self.manifold.tick()
    
    def _update_triads(self, x: np.ndarray, y: np.ndarray):
        """Update triadic constraint matrices."""
        if len(x) >= 3 and len(y) >= 3:
            x_triad = np.clip(x[:3].reshape(-1), -10, 10)
            y_triad = np.clip(y[:3].reshape(-1), -10, 10)
            
            # Noether: conservation (input auto-correlation)
            self.triads.noether += 0.01 * np.outer(x_triad, x_triad)
            
            # Shannon: channel (input-output correlation)
            self.triads.shannon += 0.01 * np.outer(y_triad, x_triad)
            
            # Landauer: energy (output magnitude)
            self.triads.landauer += 0.01 * np.outer(y_triad, y_triad)
    
    def _check_growth(self) -> bool:
        """Check if network should grow based on MI."""
        if self.dims >= self.max_dims:
            return False
        
        # Growth condition: MI exceeding threshold
        if self.mutual_information > 0.5 and self.epoch % 100 == 0:
            return self.grow()
        
        return False
    
    def grow(self) -> bool:
        """Expand network dimensionality."""
        if self.dims >= self.max_dims:
            return False
        
        new_dims = min(self.dims + self.growth_increment, self.max_dims)
        
        # Expand weights
        new_weights = np.random.randn(new_dims, new_dims) * np.sqrt(2.0 / new_dims)
        new_weights[:self.dims, :self.dims] = self.weights
        self.weights = new_weights
        self.dims = new_dims
        
        return True
    
    def _critical_period_pruning(self):
        """Prune weak connections at critical period — structural hardening, NOT permanent freeze.

        Zeroes weights below threshold to sharpen learned patterns (increases sparsity).
        Does NOT set frozen=True — the epoch gate in agent_life.py handles the
        compress→merge→grow cycle. Freezing here was a bug: it stopped all learning
        permanently at the first epoch-300 boundary.
        """
        weight_mags = np.abs(self.weights)
        w_max = np.max(weight_mags)
        if w_max < 1e-10:
            return

        threshold = self.prune_threshold * w_max
        pruned_mask = weight_mags < threshold
        self.weights[pruned_mask] = 0

        pruned_count = int(np.sum(pruned_mask))
        logger.debug("Critical period pruning: %d/%d weights zeroed (threshold=%.4f)",
                     pruned_count, self.weights.size, threshold)

        # Create expert modules from the hardened structure (read-only snapshots)
        self._create_experts()
    
    def _create_experts(self):
        """Create specialized expert modules post-pruning."""
        domains = ["auditor", "healer", "expander", "optimizer", "validator"]
        
        for domain in domains:
            # Extract domain-specific weights
            expert_weights = self.weights.copy()
            
            expert = ExpertModule(
                name=f"expert_{domain}",
                domain=domain,
                weights=expert_weights,
                specialization_score=0.7
            )
            self.experts.append(expert)
    
    def _calculate_sparsity(self) -> float:
        """Calculate weight sparsity."""
        return float(np.mean(self.weights == 0))

    # ── Crystallization Cycle ─────────────────────────────────────

    def _check_crystallization(self) -> bool:
        """At max_dims (96D), the manifold crystallizes into an atom.

        Conditions:
          1. Dims have reached max_dims (96D = 4× Leech)
          2. Triadic energy is below threshold (stable)
          3. Epoch is past critical period (hardened)
          4. Not already crystallized
        """
        if self.crystallized:
            return False
        if self.dims < self.max_dims:
            return False
        if self.triads.energy() > self.crystallization_threshold:
            return False
        if self.epoch < self.critical_epoch:
            return False
        return True

    def crystallize(self) -> Dict:
        """Compress the full manifold into a single glyph atom.

        The weights ARE the content. The eigenspectrum IS the address.
        The spinor signature IS the quantum identity.

        Returns a glyph dict that can seed a new generation or be stored
        as a Level 1 slot in the Master TMN.
        """
        import hashlib

        # Compute spinor signature
        from core.legacy_stubs import decompose, quantum_numbers  # was: tools.cmplx.unified_cmplx
        spectrum = decompose(self)
        qn = quantum_numbers(spectrum)

        content_hash = hashlib.sha256(self.weights.tobytes()).hexdigest()

        # E8 address from first 8×8 block (the "seed" region)
        e8_address = self.weights[:8, :8].flatten()[:8].tolist()

        glyph = {
            'content_hash': content_hash,
            'e8_address': e8_address,
            'spinor_signature': qn,
            'generation': self.generation,
            'dims_at_crystal': self.dims,
            'epoch_at_crystal': self.epoch,
            'triadic_energy': float(self.triads.energy()),
            'n_experts': len(self.experts),
            'sparsity': self._calculate_sparsity(),
            'strand_count': spectrum.total_strands,
            'dominant_period': spectrum.dominant_period,
            'chirality_balance': spectrum.chirality_balance,
        }

        self.crystallized = True
        self.glyph = glyph
        return glyph

    def spawn_next_generation(self, glyph: Optional[Dict] = None) -> 'TriadicManifoldNetwork':
        """Create a new 24D TMN seeded from a crystallized glyph.

        The glyph's E8 address seeds the initial weight structure via
        rank-1 outer product. The child starts with structure, not random noise.
        This is informed initialization from the Master TMN's knowledge.
        """
        glyph = glyph or self.glyph
        if glyph is None:
            raise ValueError("No glyph to spawn from — crystallize first")

        child = TriadicManifoldNetwork(
            init_dims=self.init_dims,
            max_dims=self.max_dims,
            growth_increment=self.growth_increment,
            critical_epoch=self.critical_epoch,
        )
        child.generation = glyph['generation'] + 1

        # Seed from glyph's E8 address — rank-1 initialization
        seed = np.array(glyph['e8_address'][:8])
        seed = seed / (np.linalg.norm(seed) + 1e-8)
        # The outer product gives the child directional bias from the parent
        child.weights[:8, :8] = np.outer(seed, seed) * np.sqrt(2.0 / 8)

        return child

    def analyze_code(self, code: str, context: str = "") -> Dict:
        """
        Analyze code using manifold representation.
        Returns analysis metrics.
        """
        # Encode code
        encoding = self.encode_code(code)
        
        # Forward pass through manifold
        processed = self.forward(encoding)
        
        # Calculate properties
        norm = np.linalg.norm(processed)
        sparsity = np.mean(np.abs(processed) < 0.1)
        
        # Triadic analysis
        triad_scores = {
            "conservation": float(np.trace(self.triads.noether)),
            "information": float(np.trace(self.triads.shannon)),
            "energy": float(np.trace(self.triads.landauer))
        }
        
        return {
            "encoding_norm": float(norm),
            "sparsity": float(sparsity),
            "triadic_scores": triad_scores,
            "manifold_position": processed[:8].tolist(),
            "context": context
        }
    
    def get_expert(self, domain: str) -> Optional[ExpertModule]:
        """Get expert module for specific domain."""
        for expert in self.experts:
            if expert.domain == domain:
                return expert
        return None
    
    def state_dict(self) -> Dict:
        """Serialize network state."""
        return {
            "dims": self.dims,
            "epoch": self.epoch,
            "frozen": self.frozen,
            "weights_shape": list(self.weights.shape),
            "triads": self.triads.to_dict(),
            "mutual_information": float(self.mutual_information),
            "experts": [
                {
                    "name": e.name,
                    "domain": e.domain,
                    "specialization": e.specialization_score
                }
                for e in self.experts
            ]
        }

    # ── Persistence ──────────────────────────────────────────────────

    def save(self, path: str) -> str:
        """Save full TMN state to disk. Returns the path written."""
        import os
        os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
        state = {
            "dims": self.dims,
            "max_dims": self.max_dims,
            "growth_increment": self.growth_increment,
            "prune_threshold": self.prune_threshold,
            "critical_epoch": self.critical_epoch,
            "epoch": self.epoch,
            "frozen": self.frozen,
            "hebbian_lr": self.hebbian_lr,
            "mutual_information": float(self.mutual_information),
            "mi_history": [float(x) for x in self.mi_history[-1000:]],  # last 1000
            "weights": self.weights.tolist(),
            "triads_noether": self.triads.noether.tolist(),
            "triads_shannon": self.triads.shannon.tolist(),
            "triads_landauer": self.triads.landauer.tolist(),
            "experts": [
                {"name": e.name, "domain": e.domain, "specialization": e.specialization_score,
                 "weights_shape": list(e.weights.shape)}
                for e in self.experts
            ],
        }
        with open(path, "w") as f:
            json.dump(state, f)
        return path

    @classmethod
    def load(cls, path: str) -> "TriadicManifoldNetwork":
        """Load TMN state from disk. Returns a fully restored network."""
        with open(path) as f:
            state = json.load(f)
        tmn = cls(
            init_dims=state["dims"],
            max_dims=state.get("max_dims", 96),
            growth_increment=state.get("growth_increment", 8),
            prune_threshold=state.get("prune_threshold", 0.03),
            critical_epoch=state.get("critical_epoch", 300),
        )
        tmn.epoch = state["epoch"]
        tmn.frozen = state["frozen"]
        tmn.hebbian_lr = state.get("hebbian_lr", 0.001)
        tmn.mutual_information = state.get("mutual_information", 0.0)
        tmn.mi_history = state.get("mi_history", [])
        tmn.weights = np.array(state["weights"])
        tmn.dims = tmn.weights.shape[0]
        if "triads_noether" in state:
            tmn.triads.noether = np.array(state["triads_noether"])
            tmn.triads.shannon = np.array(state["triads_shannon"])
            tmn.triads.landauer = np.array(state["triads_landauer"])
        return tmn

    def learn_from_action(self, action_type: str, content: str, result: str = "") -> Dict:
        """Learn from an agent action. This is the primary memory-building call.

        action_type: what happened (bounty_complete, finding_posted, question_answered, etc.)
        content: the input (bounty need, question text, etc.)
        result: the output (answer, deliverable, finding, etc.)

        The TMN encodes both as 24D vectors, runs a Hebbian update,
        updates triadic constraints, and returns learning metrics.
        The weights change. The agent's brain changes. This IS memory.
        """
        # Combine action type into content for richer encoding
        input_str = f"{action_type}:{content[:500]}"
        output_str = result[:500] if result else content[:500]
        return self.learn(input_str, output_str)

    def query(self, content: str) -> np.ndarray:
        """Query the TMN — what does this content activate?

        Returns the manifold position (24D vector) that this content
        maps to in the trained network. Nearby positions = related knowledge.
        """
        encoding = self.encode_code(content)
        return self.forward(encoding)


@dataclass
class TriadicState:
    """Current state of triadic constraints."""
    noether: np.ndarray = field(default_factory=lambda: np.zeros((3, 3)))  # Conservation
    shannon: np.ndarray = field(default_factory=lambda: np.zeros((3, 3)))  # Information
    landauer: np.ndarray = field(default_factory=lambda: np.zeros((3, 3)))  # Energy
    
    def to_dict(self) -> Dict:
        return {
            "noether_trace": float(np.trace(self.noether)),
            "shannon_trace": float(np.trace(self.shannon)),
            "landauer_trace": float(np.trace(self.landauer)),
            "triadic_energy": float(self.energy())
        }
    
    def energy(self) -> float:
        """Calculate total triadic energy."""
        return (np.trace(self.noether) + 
                np.trace(self.shannon) + 
                np.trace(self.landauer))


__getattr__ = build_module_getattr(__name__, "origin_main_superset")


logger = logging.getLogger("retooling.geometry.tmn_core")


"""Triadic Manifold Network (TMN) Core
====================================

Implementation of the TMN architecture for self-improvement.
Uses 24D Niemeier/Leech geometry with triadic constraints."""


"""AUTO-MERGED canonical from 4 variant(s). Function-union strategy.
Generated by _scripts/merge_variants.py.

Source variants:
  - D:/PartsFactory/Unification Prototypes/_extracted/tmn/tmn-corpus/03-historical-builds/historical builds/Builds/CMPLX/retooling_src/geometry/tmn_core.py
  - D:/PartsFactory/Unification Prototypes/_extracted/tmn/tmn-corpus/03-historical-builds/historical builds/Builds/Retooling/src/retooling/geometry/tmn_core.py
  - D:/PartsFactory/Unification Prototypes/_extracted/tmn/tmn-corpus/03-historical-builds/historical builds/CMPLX-TMN1/tmn1-v2/shared/geometry/tmn_core.py
  - D:/PartsFactory/Unification Prototypes/_extracted/tmn/tmn-corpus/03-historical-builds/historical builds/CMPLX-TMN2/repos/CMPLX/src/cqe_spine/tmn_core.py

Merge stats: {'imports_union': 7, 'definitions_merged': 7, 'names_with_conflicts': 1, 'has_trailing_main': False}"""
