"""
Integrated 2026-05-19T00:52:23Z from external toolkit.
Source: ``D:\Manny Unification 2\datasets from previous review\Manus dev and review\unified_e8.py``
"""
from __future__ import annotations

"""
Unified module for family: e8

Canon build: e8_lattice_suite_100641
Layer: 2
Adapter: geometric_core

This module contains all unique functions and classes discovered
across every material build in the e8 family.
Each symbol includes provenance metadata (source build, file).

Auto-generated by scripts/family_unifier.py on 2026-02-23T12:38:56.654110+00:00
"""

# --- Provenance metadata ---
__family_key__ = 'e8'
__canon_build__ = 'e8_lattice_suite_100641'
__layer__ = 2
__adapter__ = 'geometric_core'

# --- Common imports (best-effort) ---
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple
import hashlib
import json
import logging
import os
import re
import sys

# --- Build-sourced imports (may need adaptation) ---
# from hashlib import blake2b  # TODO: verify availability
# from itertools import permutations, product  # TODO: verify availability
# from itertools import product  # TODO: verify availability
# from kernel.db_helpers import fetch_recent_trails  # TODO: verify availability
# from kernel.telemetry import emit  # TODO: verify availability
# import math  # TODO: verify availability
# import numpy as np  # TODO: verify availability
# import pathlib, json  # TODO: verify availability
# import random  # TODO: verify availability

logger = logging.getLogger(f'cmplx.unified.{__family_key__}')

#===============================================================================
# CLASSES (27 unique)
#===============================================================================

# Source: e8_toolkit_v5 / e8/lattice.py

class D24Plus:
    """
    Experimental 24D even lattice approximating D_24^+ behavior:
    - Start with D24: integer vectors with even coordinate sum
    - Add a glue shift by 0.5 to allow half-integer cosets with mod-2 parity
    This is *not* the true Leech lattice; it's a practical higher-D even lattice
    to exercise higher-dimensional cascades and parity structure.
    """
    def __init__(self):
        self.n = 24
        # Simple-root-like basis for D_n
        B = np.zeros((self.n, self.n))
        for i in range(self.n-1):
            B[i, i] = 1.0
            B[i, i+1] = -1.0
        # Last row encodes e_{n-1}+e_n pattern
        B[self.n-1, self.n-2] = 1.0
        B[self.n-1, self.n-1] = 1.0
        self.B = B
        self.Q, self.R = np.linalg.qr(self.B)

    def snap(self, v: np.ndarray, return_meta: bool=False):
        # Nearest-plane in this basis
        y = v.copy()
        z = np.linalg.solve(self.R, self.Q.T @ y)
        z_round = np.round(z)
        y_snap = self.Q @ (self.R @ z_round)
        # Project into ambient and enforce even-sum (D24) by minimal tweak
        x = y_snap
        s = int(np.round(np.sum(x)))
        if s % 2 != 0:
            # toggle the smallest magnitude coordinate sign to restore even sum
            idx = np.argmin(np.abs(x))
            x[idx] = -x[idx]
        residual = y - x
        # Coset heuristic
        t = 2.0 * x
        near_int = np.allclose(t, np.round(t), atol=1e-8)
        coset = "Z-even" if near_int else "Z+1/2-even"
        meta = {"snapped": x, "residual": residual, "input": v, "coset": coset,
                "basis": self.B, "Q": self.Q, "R": self.R}
        return meta if return_meta else x


# Source: E8_code_part05 / CODE/snaplat_mono_v2_fullproto39/ecc/e8.py

class E8Code:
    # Store lattice point as ints; if half=True, these represent twice-the-value.
    y: Tuple[int, ...]
    half: bool


# Source: e8_toolkit_v5 / e8/lattice.py

class E8Lattice:
    def __init__(self, B: np.ndarray=None):
        # Simple-root basis
        if B is None:
            B = np.array([
                [ 1, -1,  0,  0,  0,  0,  0,  0],
                [ 0,  1, -1,  0,  0,  0,  0,  0],
                [ 0,  0,  1, -1,  0,  0,  0,  0],
                [ 0,  0,  0,  1, -1,  0,  0,  0],
                [ 0,  0,  0,  0,  1, -1,  0,  0],
                [ 0,  0,  0,  0,  0,  1, -1,  0],
                [ 0,  0,  0,  0,  0,  1,  1,  0],
                [-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5, 0.5]
            ], dtype=float)
        self.B = B
        self.Q, self.R = np.linalg.qr(self.B)

    def snap(self, v: np.ndarray, k_neighbors:int=1, return_meta:bool=False) -> Any:
        # Nearest-plane projection
        y = v.copy()
        z = np.linalg.solve(self.R, self.Q.T @ y)
        z_round = np.round(z)
        y_snap = self.Q @ (self.R @ z_round)
        residual = y - y_snap

        # Coset detection (rough): check if all coords in snapped are integers or half-integers with even sum parity
        # Project snapped into the standard E8 coordinate chart by solving Bx = y_snap for x, then reconstruct "ambient".
        # For practicality, just check the parity of 2*y_snap.
        t = 2.0 * y_snap
        near_int = np.allclose(t, np.round(t), atol=1e-8)
        if near_int:
            # even unimodular parity: sum of coordinates in 2y is divisible by 4 for E8 (heuristic check)
            s = int(np.round(np.sum(t))) % 4
            coset = "Z-even" if s == 0 or s == 2 else "other"
        else:
            coset = "Z+1/2-even"

        if return_meta:
            return {
                "snapped": y_snap,
                "residual": residual,
                "input": v,
                "coset": coset,
                "basis": self.B,
                "Q": self.Q,
                "R": self.R
            }
        return y_snap


# Source: e8_lattice_suite_100641 / repo/lattice_ai/encode/e8_lattice.py

class E8LatticeEncoder:
    """E8 lattice-aware encoder that maps inputs into R^8 vectors and assigns them
    into pre-allocated lattice banks labeled by shape.

    Shapes are tracked with explicit labels so downstream systems know the intended
    sub-structure and dimensionality semantics (e.g., Shell:k, D8 sublattice).

    Notes:
    - This implementation is deterministic and stateless w.r.t inputs.
    - Banks are pre-allocated to guarantee O(1) inserts and predictable memory locality.
    """
    banks: Dict[str, LatticeBank] = field(default_factory=dict)
    salt: str = "E8"

    def allocate_bank(self, name: str, shape: str, capacity: int = 4096, dims: int = 8) -> None:
        if name in self.banks:
            raise ValueError(f"Bank '{name}' already exists")
        if dims != 8:
            raise ValueError("This encoder is R^8-native; dims must be 8")
        self.banks[name] = LatticeBank(name=name, shape=shape, dims=dims, capacity=capacity)

    def list_banks(self) -> List[Tuple[str, str, int]]:
        return [(b.name, b.shape, b.capacity) for b in self.banks.values()]

    # --- Encoding primitives ---
    def _stable_hash(self, x: bytes, salt: str) -> int:
        return int.from_bytes(hashlib.blake2b(salt.encode('utf-8')+x, digest_size=16).digest(), 'little')

    def _pick_roots(self, h: int, k: int) -> np.ndarray:
        """Pick k root directions deterministically from E8 roots using hash h."""
        idx = list(_cached_root_idx(h, k))
        return _E8_ROOTS[np.array(idx, dtype=int)]  # (k, 8)

    def _mix(self, roots: np.ndarray, weights: np.ndarray) -> np.ndarray:
        v = (roots * weights.reshape(-1,1)).sum(axis=0)
        n = np.linalg.norm(v) + 1e-12
        return (v / n).astype(np.float32)

    def encode_text(self, text: str, bank: Optional[str] = None, k: int = 3, shell_k: int = 1) -> Dict[str, Any]:
        """Encode text to R^8, with optional insertion into a bank.

        Args:
            text: input string
            bank: optional bank name to store the vector
            k:    number of root directions to mix
            shell_k: which 'shell' label to attach (metadata only)

        Returns:
            dict: {vector, meta, (optional) bank_index}
        """
        b = text.encode('utf-8')
        h = self._stable_hash(b, self.salt)
        roots = self._pick_roots(h, k)
        # weights derived from another hash stream in [-1,1]
        w = []
        cur = h ^ 0x9E3779B97F4A7C15
        for i in range(k):
            cur = (cur * 1442695040888963407 + 11400714819323198485) & ((1<<64)-1)
            w.append(((cur & 0xFFFF) / 32767.5) - 1.0)
        v = self._mix(roots, np.array(w, dtype=np.float32))
        meta = {
            "shape": "E8",
            "dims": 8,
            "coxeter": _coxeter_coords(v).tolist(),
            "gdist": float(_geodesic_proxy(v)),
            "shell": f"Shell:{shell_k}",
            "k_roots": k,
            "roots_idx": None,  # omitted for now to keep meta light; can add if needed
            "salt": self.salt,
            "kind": "text",
        }
        rec = {"vector": v, "meta": meta}
        if bank is not None:
            if bank not in self.banks:
                raise KeyError(f"Unknown bank '{bank}'")
            i = self.banks[bank].put(v, meta | {"payload_preview": text[:64]})
            rec["bank_index"] = i
        return rec

    def encode_bytes(self, blob: bytes, bank: Optional[str] = None, k: int = 4, shell_k: int = 2) -> Dict[str, Any]:
        h = self._stable_hash(blob, self.salt)
        roots = self._pick_roots(h, k)
        # weights from blob chunks
        w = []
        cur = h ^ 0xD1B54A32D192ED03
        for i in range(k):
            cur = (cur * 3202034522624059733 + 6364136223846793005) & ((1<<64)-1)
            w.append(((cur & 0xFFFF) / 32767.5) - 1.0)
        v = self._mix(roots, np.array(w, dtype=np.float32))
        meta = {"shape": "E8", "dims": 8, "coxeter": _coxeter_coords(v).tolist(), "gdist": float(_geodesic_proxy(v)), "shell": f"Shell:{shell_k}", "k_roots": k, "salt": self.salt, "kind": "bytes"}
        rec = {"vector": v, "meta": meta}
        if bank is not None:
            if bank not in self.banks: raise KeyError(f"Unknown bank '{bank}'")
            i = self.banks[bank].put(v, meta | {"payload_len": len(blob)})
            rec["bank_index"] = i
        return rec

    # Batch helpers
    def encode_texts(self, texts: List[str], bank: Optional[str] = None, k: int = 3, shell_k: int = 1) -> Dict[str, Any]:
        out = [self.encode_text(t, bank=bank, k=k, shell_k=shell_k) for t in texts]
        V = np.stack([o["vector"] for o in out], axis=0)
        meta = [o["meta"] for o in out]
        idx = [o.get("bank_index") for o in out]
        return {"vectors": V, "meta": meta, "bank_indices": idx}

    # Introspection
    def bank_snapshot(self, name: str, limit: int = 10) -> Dict[str, Any]:
        b = self.banks[name]
        return {
            "shape": b.shape, "dims": b.dims, "capacity": b.capacity, "next": getattr(b, "_next", 0),
            "sample": [{"i": i, "meta": b.meta[i]} for i in range(min(limit, getattr(b, "_next", 0)))]
        }


# Source: E8_code_part05 / CODE/snaplat_mono_v2_fullproto39/triads/agencies/e8_quant.py

class E8QuantizeAgency(Agency):
    name: str = "e8_quant"
    scale: float = 1.0

    def run(self, job: Job) -> dict:
        payload = job.payload or {}
        vecs: List[List[float]] = payload.get("vectors", [])
        if not vecs:
            return {"ok": False, "error": "no vectors", "count": 0}

        # ---- Scale selection ----
        scale = None
        eval_grid = None
        grid = payload.get("scale_grid")
        if isinstance(grid, (list, tuple)) and grid:
            eval_grid = {}
            for s in grid:
                qtmp = SnapE8(scale=float(s))
                total = 0.0
                for v in vecs[: min(64, len(vecs))]:
                    _, resid = qtmp.encode(v)
                    total += sum(r*r for r in resid)
                eval_grid[float(s)] = total / max(1, min(64, len(vecs)))
            # pick lowest loss
            scale = min(eval_grid, key=lambda k: eval_grid[k])
        else:
            scale = choose_scale(vecs, candidate_scales=(0.5, 1.0, 2.0), sample=min(64, len(vecs)))

        q = SnapE8(scale=scale, pre=whiten.pre_hadamard)

        # ---- Stats before/after whitening ----
        flat = [x for v in vecs for x in v]
        k_pre = whiten.kurtosis(flat) if flat else 0.0
        wvecs = [q.pre(v) if q.pre else v for v in vecs]
        flat_w = [x for v in wvecs for x in v]
        k_post = whiten.kurtosis(flat_w) if flat_w else 0.0

        # ---- Encode timing ----
        t0 = time.perf_counter()
        out = q.encode_batch(vecs)
        t1 = time.perf_counter()

        # ---- CAS write timing ----
        hashes = []
        t2a = time.perf_counter()
        for rec in out:
            try:
                h = put({ "cell_id": rec["cell_id"], "residual": rec["residual"], "tick": payload.get("tick") })
                hashes.append(h)
            except Exception as e:
                emit("e8.cas_error", "agency", {"err": str(e)})
        t2b = time.perf_counter()

        timing = {
            "encode_ms": round((t1 - t0) * 1000.0, 3),
            "cas_ms": round((t2b - t2a) * 1000.0, 3),
            "per_vec_ms": round(((t1 - t0) + (t2b - t2a)) * 1000.0 / max(1, len(out)), 4)
        }

        emit("e8.quantized", "agency", {
            "count": len(out),
            "tick": payload.get("tick"),
            "kurtosis": {"pre": k_pre, "post": k_post},
            "scale": scale,
            "timing": timing,
            "scale_eval": eval_grid
        })

        return {
            "ok": True,
            "count": len(out),
            "cas": hashes,
            "kurtosis": {"pre": k_pre, "post": k_post},
            "scale": scale,
            "timing": timing,
            "scale_eval": eval_grid
        }


# Source: e8_toolkit_v5 / e8/evidence.py

class EvidenceSurface:
    """
    Treat each snap as an evidence surface: a small perturbation can flip many coupled binary states.
    We model this with an Ising-like energy:  Phi(s) = -0.5 s^T J s - h^T s,  s in {-1,+1}^M (masked where unknown).
    Variables:
      - s_i: sign of each of 8 coordinates (0 abstains)
      - nz_i: nonzero indicator of each coord (maps to field, not a spin here)
      - coset_half: +1 if half-integers (Z+1/2-even), -1 if integers (Z-even)
    Couplings:
      - sign-sign: pairwise couplings derived from E8 root combinatorics (pairs appear in (±1,±1,0^6) roots).
      - coset-sign: weak coupling encouraging half-integers to decorrelate signs; integers to align pairs.
    External field:
      - from residual direction and magnitude: pushes spins to align with residual.
    """
    def __init__(self, lambda_pair: float = 0.2, lambda_coset: float = 0.05, lambda_residual: float = 0.8):
        self.lambda_pair = float(lambda_pair)
        self.lambda_coset = float(lambda_coset)
        self.lambda_residual = float(lambda_residual)

    @staticmethod
    def _pair_matrix():
        # In E8, "type I" roots have two ±1 and six zeros. For any i<j, there are 4 sign combos.
        # Use a normalized adjacency where each distinct pair contributes equally.
        A = np.ones((8,8), dtype=float) - np.eye(8)
        A *= 4.0  # count of sign combos
        # Normalize by max degree (7*4) so entries in [0,1]
        A /= (7.0*4.0)
        return A

    @staticmethod
    def _torus_closure(theta):
        """
        Simple octet closure score on the 8-torus: penalize phases far from multiples of pi/4.
        theta: 8-vector of angles in radians (0..2pi)
        Returns small when phases are near 8-ary grid.
        """
        target = (np.pi/4.0) * np.round(theta / (np.pi/4.0))
        return float(np.linalg.norm(np.angle(np.exp(1j*(theta - target)))))

    def build_problem(self, meta: Dict[str, Any]) -> Dict[str, Any]:
        x = np.asarray(meta["snapped"], dtype=float)
        r = np.asarray(meta["residual"], dtype=float)
        coset = meta.get("coset","other")
        # spins for signs
        s = np.array([sign_bin(v) for v in x], dtype=int)  # {-1,0,+1}
        mask = (s != 0)
        s[~mask] = 1  # fill to +1 where abstaining; masked in updates
        # fields
        h = np.zeros(9, dtype=float)  # 8 sign spins + 1 coset spin
        # residual field pushes sign toward sign of r (if residual has structure)
        h[:8] = self.lambda_residual * np.tanh(r)  # soft field from residual
        # coset spin: +1 half, -1 integer
        c = 1.0 if coset == "Z+1/2-even
(Content truncated due to size limit. Use line ranges to read remaining content)