#!/usr/bin/env python3
"""
Analyze massive monolithic files (>100K lines) to extract unique capabilities.

Identifies:
- Concatenated dumps vs authored code
- Duplicate monoliths across paths
- Unique function/class signatures
- Capability mapping
"""
import psycopg2
import json
import os
import ast
from collections import defaultdict

CACHE_DSN = os.environ.get("CACHE_DSN") or os.environ.get("CACHE_PG_URL")


def translate_path(host_path):
    """Convert Windows path to container path."""
    if not host_path:
        return None
    path = host_path.replace('\\\\', '/')
    if path.startswith('D:/PartsFactory/'):
        return '/mnt/d/' + path[3:]
    if path.startswith('D:/OC build/'):
        return '/workspace/OCbuild/' + path[12:]
    if path.startswith('D:/Manny Unification 2/'):
        return '/workspace/MannyUnification2/' + path[23:]
    if path.startswith('d:/PartsFactory/'):
        return '/mnt/d/' + path[3:]
    if path.startswith('d:/OC build/'):
        return '/workspace/OCbuild/' + path[12:]
    if path.startswith('d:/Manny Unification 2/'):
        return '/workspace/MannyUnification2/' + path[23:]
    return path


def analyze_file_structure(path, max_lines=1000):
    """Analyze first N lines to determine file structure."""
    try:
        with open(path, 'r', encoding='utf-8', errors='replace') as f:
            lines = []
            for i, line in enumerate(f):
                if i >= max_lines:
                    break
                lines.append(line)
        
        source = ''.join(lines)
        
        # Check for concatenation markers
        markers = {
            'file_separator': sum(1 for l in lines if l.startswith('# ===') or l.startswith('#---') or l.startswith('// ===')),
            'filename_comments': sum(1 for l in lines if '# File:' in l or '# file:' in l or '# FILE:' in l),
            'module_headers': sum(1 for l in lines if l.startswith('# Module:') or l.startswith('# module:')),
            'auto_generated': sum(1 for l in lines if 'auto-generated' in l.lower() or 'autogenerated' in l.lower() or 'generated by' in l.lower()),
        }
        
        # Check AST structure of first chunk
        ast_depth = 0
        try:
            tree = ast.parse(source)
            ast_depth = max((node.lineno for node in ast.walk(tree) if hasattr(node, 'lineno')), default=0)
        except:
            pass
        
        return {
            'sample_lines': len(lines),
            'markers': markers,
            'ast_depth': ast_depth,
            'avg_line_length': sum(len(l) for l in lines) / len(lines) if lines else 0,
        }
    except Exception as e:
        return {'error': str(e)}


def analyze_monoliths():
    pg = psycopg2.connect(CACHE_DSN)
    pg_cur = pg.cursor()
    
    # Find all monoliths (>100K lines)
    print("Finding monolithic files (>100K lines)...")
    pg_cur.execute("""
        SELECT 
            cs.source_id,
            s.host_path,
            s.relative_path,
            s.root_label,
            cs.line_count,
            cs.language,
            jsonb_array_length(cs.function_names) as func_count,
            jsonb_array_length(cs.class_names) as class_count,
            cs.system_of_origin
        FROM catalog.code_source cs
        JOIN artifact.source s ON cs.source_id = s.id
        WHERE cs.line_count > 100000
        ORDER BY cs.line_count DESC
    """)
    
    monoliths = pg_cur.fetchall()
    print(f"Found {len(monoliths)} monolithic files\n")
    
    # Group by basename to find duplicates
    by_basename = defaultdict(list)
    for row in monoliths:
        source_id, host_path, rel_path, root_label, lines, lang, funcs, classes, system = row
        basename = rel_path.split('/')[-1] if rel_path else 'unknown'
        by_basename[basename].append({
            'source_id': source_id,
            'host_path': host_path,
            'rel_path': rel_path,
            'root_label': root_label,
            'lines': lines,
            'lang': lang,
            'funcs': funcs,
            'classes': classes,
            'system': system
        })
    
    print("=== MONOLITH ANALYSIS ===\n")
    
    for basename, files in sorted(by_basename.items(), key=lambda x: x[1][0]['lines'], reverse=True):
        total_lines = sum(f['lines'] for f in files)
        total_funcs = sum(f['funcs'] for f in files)
        total_classes = sum(f['classes'] for f in files)
        
        print(f"\n{basename}")
        print(f"  Copies: {len(files)} | Total lines: {total_lines:,} | Functions: {total_funcs:,} | Classes: {total_classes:,}")
        
        # Check if all copies are identical
        all_same_lines = all(f['lines'] == files[0]['lines'] for f in files)
        all_same_funcs = all(f['funcs'] == files[0]['funcs'] for f in files)
        
        if all_same_lines and all_same_funcs:
            print(f"  ⚠️  EXACT DUPLICATES — all {len(files)} copies are identical")
        else:
            print(f"  Variants differ in size")
        
        # Show locations
        for f in files:
            print(f"    [{f['root_label']}] {f['rel_path'][:80]} ({f['lines']:,} lines)")
        
        # Analyze first copy's structure
        if files:
            container_path = translate_path(files[0]['host_path'])
            if container_path and os.path.exists(container_path):
                structure = analyze_file_structure(container_path)
                if 'error' not in structure:
                    markers = structure['markers']
                    print(f"  Structure analysis (first {structure['sample_lines']} lines):")
                    print(f"    File separators: {markers['file_separator']}")
                    print(f"    Filename comments: {markers['filename_comments']}")
                    print(f"    Module headers: {markers['module_headers']}")
                    print(f"    Auto-generated markers: {markers['auto_generated']}")
                    print(f"    AST depth: {structure['ast_depth']} lines")
                    if markers['file_separator'] > 5 or markers['filename_comments'] > 5:
                        print(f"    → LIKELY CONCATENATED DUMP")
                    elif markers['auto_generated'] > 0:
                        print(f"    → LIKELY AUTO-GENERATED")
    
    # Find exact SHA-256 duplicates among monoliths
    print("\n\n=== EXACT HASH DUPLICATES AMONG MONOLITHS ===")
    pg_cur.execute("""
        SELECT 
            s.sha256,
            COUNT(*) as copies,
            MIN(cs.line_count) as lines,
            array_agg(DISTINCT s.root_label) as labels,
            array_agg(s.relative_path) as paths
        FROM artifact.source s
        JOIN catalog.code_source cs ON s.id = cs.source_id
        WHERE cs.line_count > 100000
          AND s.sha256 IS NOT NULL
          AND s.sha256 != ''
        GROUP BY s.sha256
        HAVING COUNT(*) > 1
        ORDER BY COUNT(*) DESC
    """)
    
    for row in pg_cur.fetchall():
        sha256, copies, lines, labels, paths = row
        print(f"\nHash: {sha256[:16]}... | {copies} copies | {lines:,} lines")
        print(f"  Spaces: {', '.join(labels)}")
        for p in paths[:3]:
            print(f"    {p}")
    
    pg_cur.close()
    pg.close()


if __name__ == "__main__":
    analyze_monoliths()
