#!/usr/bin/env python3
"""
Combined A+B+C: Inspect, verify, and canonicalize top candidates per domain.

For each domain:
1. Read the best candidate file
2. Analyze if it's clean or a dump
3. If clean: copy to src/canon/<domain>/ with LF endings
4. If suspicious: flag for review and search for alternatives
5. Record everything in PostgreSQL canonicalization tables
"""
import psycopg2
import os
import ast
import hashlib
import json
from datetime import datetime, timezone
from collections import defaultdict

CACHE_DSN = "postgresql://research:research_hub_dev@postgres-cache:5432/unification_aggregator"
HUB_DSN = "postgresql://research:research_hub_dev@postgres:5432/unification_hub"

# Domain -> best candidate basename mapping from previous analysis
DOMAIN_CANDIDATES = {
    'geometry_lattice': ['lattice.py', 'e8_lattice.py'],
    'governance_snap': ['snap.py', 'agrm.py'],
    'mmdb_memory': ['store.py', 'crystal.py', 'mmdb.py'],
    'morphonic': ['state.py', 'morphonic.py', 'morph.py'],
    'mdhg_hierarchy': ['mdhg.py', 'tree.py'],
    'speedlight': ['speedlight.py', 'receipt.py', 'cache.py'],
    'identity_wallet': ['identity.py', 'wallet.py'],
    'server_runtime': ['main.py', 'app.py', 'server.py', 'run.py'],
    'core_engine': ['registry.py', 'think_tank.py', 'pipeline.py', 'engine.py'],
    'observability': ['logger.py', 'metrics.py', 'monitor.py'],
    'cryptography': ['hash.py', 'crypto.py', 'sign.py'],
}


def translate_path(host_path):
    if not host_path:
        return None
    path = host_path.replace('\\\\', '/')
    if path.startswith('D:/PartsFactory/'):
        return '/mnt/d/' + path[3:]
    if path.startswith('D:/OC build/'):
        return '/workspace/OCbuild/' + path[12:]
    if path.startswith('D:/Manny Unification 2/'):
        return '/workspace/MannyUnification2/' + path[23:]
    if path.startswith('d:/PartsFactory/'):
        return '/mnt/d/' + path[3:]
    if path.startswith('d:/OC build/'):
        return '/workspace/OCbuild/' + path[12:]
    if path.startswith('d:/Manny Unification 2/'):
        return '/workspace/MannyUnification2/' + path[23:]
    return path


def is_likely_dump(source, lines):
    """Heuristics to detect concatenated dumps."""
    if lines > 5000:
        return True, "Excessive line count (>5000)"
    
    # Check for file separators
    separators = sum(1 for l in source.split('\n') if l.startswith('# ===') or l.startswith('#---') or l.startswith('# File:'))
    if separators > 5:
        return True, f"Contains {separators} file separators"
    
    # Check for auto-generated markers
    auto_markers = sum(1 for l in source.split('\n') if 'auto-generated' in l.lower() or 'generated by' in l.lower())
    if auto_markers > 2:
        return True, f"Contains {auto_markers} auto-generated markers"
    
    # Check if AST is parseable and reasonable
    try:
        tree = ast.parse(source)
        top_level = len(list(ast.iter_child_nodes(tree)))
        if top_level > 100:
            return True, f"Excessive top-level nodes ({top_level})"
    except:
        return True, "Cannot parse AST"
    
    return False, "Looks clean"


def read_and_normalize(path):
    """Read file and normalize to LF line endings."""
    try:
        with open(path, 'rb') as f:
            data = f.read()
        # Normalize CRLF to LF
        data = data.replace(b'\r\n', b'\n')
        return data.decode('utf-8', errors='replace')
    except Exception as e:
        return None, str(e)


def canonicalize():
    cache_pg = psycopg2.connect(CACHE_DSN)
    cache_cur = cache_pg.cursor()
    
    hub_pg = psycopg2.connect(HUB_DSN)
    hub_cur = hub_pg.cursor()
    
    print("=== COMBINED A+B+C: INSPECT, VERIFY, CANONICALIZE ===\n")
    
    for domain, basenames in DOMAIN_CANDIDATES.items():
        print(f"\n{'='*60}")
        print(f"DOMAIN: {domain}")
        print(f"{'='*60}")
        
        # Find all candidates for this domain
        placeholders = ','.join(['%s'] * len(basenames))
        cache_cur.execute(f"""
            SELECT 
                cs.source_id,
                s.host_path,
                s.relative_path,
                s.root_label,
                cs.line_count,
                jsonb_array_length(cs.function_names) as func_count,
                jsonb_array_length(cs.class_names) as class_count,
                s.sha256,
                s.size_bytes
            FROM catalog.code_source cs
            JOIN artifact.source s ON cs.source_id = s.id
            WHERE split_part(s.relative_path, '/', -1) IN ({placeholders})
              AND cs.line_count BETWEEN 10 AND 10000
            ORDER BY 
                CASE WHEN s.root_label = 'partsfactory' THEN 0 ELSE 1 END,
                cs.line_count DESC
        """, basenames)
        
        candidates = cache_cur.fetchall()
        
        if not candidates:
            print(f"  ⚠️  No candidates found")
            continue
        
        # Inspect top 3 candidates
        canonical_chosen = None
        for i, row in enumerate(candidates[:3]):
            source_id, host_path, rel_path, root_label, lines, funcs, classes, sha256, size = row
            container_path = translate_path(host_path)
            basename = rel_path.split('/')[-1] if rel_path else 'unknown'
            
            print(f"\n  Candidate {i+1}: {basename}")
            print(f"    Path: {rel_path}")
            print(f"    Lines: {lines} | Functions: {funcs} | Classes: {classes}")
            
            if not container_path or not os.path.exists(container_path):
                print(f"    ⚠️  File not accessible")
                continue
            
            source = read_and_normalize(container_path)
            if source is None:
                print(f"    ⚠️  Cannot read file")
                continue
            
            is_dump, reason = is_likely_dump(source, lines)
            
            if is_dump:
                print(f"    ❌ DUMP DETECTED: {reason}")
                continue
            
            print(f"    ✅ CLEAN: {reason}")
            
            # This is our canonical candidate
            if not canonical_chosen:
                canonical_chosen = {
                    'source_id': source_id,
                    'basename': basename,
                    'rel_path': rel_path,
                    'host_path': host_path,
                    'lines': lines,
                    'funcs': funcs,
                    'classes': classes,
                    'source': source,
                    'size': size
                }
        
        if not canonical_chosen:
            print(f"\n  ❌ No clean candidate found for {domain}")
            continue
        
        # Write canonical file
        c = canonical_chosen
        canon_dir = f"src/canon/{domain}"
        canon_path = f"{canon_dir}/{c['basename']}"
        
        os.makedirs(canon_dir, exist_ok=True)
        
        with open(canon_path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(c['source'])
        
        # Compute hash of canonical file
        with open(canon_path, 'rb') as f:
            canon_hash = hashlib.sha256(f.read()).hexdigest()
        
        print(f"\n  📄 WRITTEN: {canon_path}")
        print(f"     Size: {len(c['source'])} bytes | Hash: {canon_hash[:16]}...")
        
        # Record in PostgreSQL
        cluster_key = f"{domain}:{c['basename']}"
        
        hub_cur.execute("""
            INSERT INTO canonical_clusters (cluster_key, basename, description)
            VALUES (%s, %s, %s)
            ON CONFLICT (cluster_key) DO UPDATE SET
                description = EXCLUDED.description,
                updated_at = NOW()
            RETURNING id
        """, (cluster_key, c['basename'], f"Canonical {domain} implementation from {c['rel_path']}"))
        
        cluster_id = hub_cur.fetchone()[0]
        
        # Record the source artifact
        hub_cur.execute("""
            INSERT INTO canonical_artifacts 
            (cluster_id, source_path, content_hash, file_size, line_count, language, system_name, is_canonical, canonical_reason, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT DO NOTHING
        """, (cluster_id, c['host_path'], sha256 or canon_hash, c['size'], c['lines'], 'python', c['rel_path'].split('/')[0] if c['rel_path'] else 'unknown', False, f"Source candidate for {domain}", datetime.now(timezone.utc).isoformat()))
        
        # Record the canonical file
        hub_cur.execute("""
            INSERT INTO canonical_artifacts 
            (cluster_id, source_path, content_hash, file_size, line_count, language, system_name, is_canonical, canonical_reason, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT DO NOTHING
        """, (cluster_id, canon_path, canon_hash, os.path.getsize(canon_path), c['lines'], 'python', 'canon', True, f"Canonical {domain} implementation", datetime.now(timezone.utc).isoformat()))
        
        # Log
        hub_cur.execute("""
            INSERT INTO canonicalization_log (cluster_key, action, details, created_at)
            VALUES (%s, %s, %s, %s)
        """, (cluster_key, 'canonicalize', json.dumps({
            'canonical_path': canon_path,
            'source_path': c['rel_path'],
            'lines': c['lines'],
            'functions': c['funcs'],
            'classes': c['classes']
        }), datetime.now(timezone.utc).isoformat()))
        
        hub_pg.commit()
    
    cache_cur.close()
    cache_pg.close()
    hub_cur.close()
    hub_pg.close()
    
    print("\n\n=== CANONICALIZATION COMPLETE ===")


if __name__ == "__main__":
    canonicalize()
