#!/usr/bin/env python3
"""
Extract corpus zips and find clean canonical implementations inside.
"""
import zipfile
import os
import ast
from collections import defaultdict

# Container mount: D:/PartsFactory/ -> /workspace/PartsFactory/
CORPUS_DIR = "/workspace/PartsFactory"
EXTRACT_DIR = "corpus_extracted"

CORPUS_ZIPS = {
    'geometry_lattice': 'dimensional-forms-split-under-200mb-corrected-20260508-170026/dimensional-forms__lattice_root_systems-code.zip',
    'mmdb_memory': 'mmdb-corpus.zip',
    'governance_snap': 'snap-deduped.zip',
    'morphonic': 'morphon-corpus.zip',
    'mdhg_hierarchy': 'agrm-corpus.zip',
    'speedlight': 'cqe-corpus.zip',
    'core_engine': 'tmn-corpus.zip',
    'observability': 'aletheia-corpus.zip',
    'cryptography': 'tarpit-corpus.zip',
}


def is_clean_python_file(path, source):
    """Check if a Python file looks clean (not a dump)."""
    lines = source.split('\n')
    if len(lines) > 5000:
        return False, "Too many lines"
    if len(lines) < 10:
        return False, "Too few lines"
    
    separators = sum(1 for l in lines if l.startswith('# ===') or l.startswith('#---') or '# File:' in l)
    if separators > 3:
        return False, f"Has {separators} file separators"
    
    auto = sum(1 for l in lines if 'auto-generated' in l.lower() or 'generated by' in l.lower())
    if auto > 1:
        return False, f"Has {auto} auto-generated markers"
    
    try:
        tree = ast.parse(source)
        top_level = len(list(ast.iter_child_nodes(tree)))
        if top_level > 100:
            return False, f"Too many top-level nodes ({top_level})"
    except:
        return False, "Cannot parse AST"
    
    return True, "Clean"


def extract_and_analyze(domain, zip_rel_path):
    zip_path = os.path.join(CORPUS_DIR, zip_rel_path)
    extract_path = os.path.join(EXTRACT_DIR, domain)
    
    if not os.path.exists(zip_path):
        print(f"\n{domain}: ZIP NOT FOUND: {zip_path}")
        return None
    
    print(f"\n{'='*60}")
    print(f"DOMAIN: {domain}")
    print(f"ZIP: {zip_rel_path} ({os.path.getsize(zip_path):,} bytes)")
    print(f"{'='*60}")
    
    os.makedirs(extract_path, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(extract_path)
    
    py_files = []
    for root, dirs, files in os.walk(extract_path):
        for f in files:
            if f.endswith('.py'):
                full = os.path.join(root, f)
                py_files.append(full)
    
    print(f"  Extracted {len(py_files)} Python files")
    
    clean_files = []
    for path in py_files:
        try:
            with open(path, 'r', encoding='utf-8', errors='replace') as f:
                source = f.read()
        except:
            continue
        
        is_clean, reason = is_clean_python_file(path, source)
        if is_clean:
            lines = len(source.split('\n'))
            try:
                tree = ast.parse(source)
                funcs = len([n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)])
                classes = len([n for n in ast.walk(tree) if isinstance(n, ast.ClassDef)])
            except:
                funcs = classes = 0
            
            rel = path[len(extract_path)+1:]
            clean_files.append((lines, funcs, classes, rel, path))
    
    print(f"  Found {len(clean_files)} clean Python files")
    
    clean_files.sort(reverse=True)
    
    print(f"\n  Top 10 clean files:")
    for i, (lines, funcs, classes, rel, path) in enumerate(clean_files[:10]):
        print(f"  {i+1}. {rel:<50} | {lines:>5}L | {funcs:>3}F {classes:>3}C")
    
    best = None
    for lines, funcs, classes, rel, path in clean_files:
        if 50 <= lines <= 2000 and funcs > 0:
            best = (lines, funcs, classes, rel, path)
            break
    
    if best:
        print(f"\n  BEST CANDIDATE: {best[3]}")
        print(f"    Lines: {best[0]} | Functions: {best[1]} | Classes: {best[2]}")
    else:
        print(f"\n  ⚠️  No suitable clean candidate found")
    
    return best


def main():
    os.makedirs(EXTRACT_DIR, exist_ok=True)
    
    print("=== EXTRACTING CORPUS ZIPS ===")
    
    results = {}
    for domain, zip_rel_path in CORPUS_ZIPS.items():
        best = extract_and_analyze(domain, zip_rel_path)
        results[domain] = best
    
    print("\n\n=== SUMMARY ===")
    for domain, best in results.items():
        if best:
            lines, funcs, classes, rel, path = best
            print(f"{domain:<20}: {rel:<50} ({lines}L, {funcs}F, {classes}C)")
        else:
            print(f"{domain:<20}: No suitable candidate")


if __name__ == "__main__":
    main()
