"""
Function canonicals for the `cqe` family.

47 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- function: phi ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def phi(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    e8 = state["e8"]
    features = feature_pack(
        geom = max(0.0, 1.0 - e8["root_distance"]),
        parity = 0.5,
        sparsity = 0.4,
        kissing = 0.3
    )
    val = compute_phi(features, system.cfg.phi_weights)
    return {"phi": val, "phi_features": features}

# --- function: e8_embed ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def e8_embed(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    text = payload.get("text","")
    e8 = embed_string(text, seed=system.cfg.seed)
    return {"e8": e8}

# --- function: fractal ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def fractal(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    text = payload.get("text","")
    fr = analyze_string(text) if system.cfg.enable_mandelbrot else {"behavior": "SKIP"}
    return {"fractal": fr}

# --- function: governance ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def governance(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    gates_in = {
        "W4": state["phi_features"]["geom"],
        "W80": state["phi_features"]["parity"],
        "Wexp": state["phi_features"]["sparsity"],
        "LAWFUL": state["phi_features"]["kissing"]
    }
    gov = Governance().evaluate(gates_in)
    # Simple V_total as in validation module
    from .validation import compute_v_total, band_for
    v = compute_v_total(scores={k:v["score"] for k,v in gov.items()}, weights={"W4":0.3,"W80":0.3,"Wexp":0.2,"LAWFUL":0.2})
    band = band_for(v)
    return {"gov_results": gov, "v_total": v, "band": band}

# --- function: ingest_text ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def ingest_text(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    text = payload.get("text","")
    meta = system.io.ingest_text(text)
    return {"text_digest": meta["digest"]}

# --- function: semantics ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def semantics(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    e8 = state["e8"]
    sem = extract_semantics(e8_distance=e8["root_distance"], angle_hint=0.2)
    return {"semantics": sem}

# --- function: toroidal ---
# composed_from=40 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def toroidal(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    tor = generate_toroidal_shell(n_points=64, seed=system.cfg.seed) if system.cfg.enable_toroidal else []
    patterns = {}
    for p in tor:
        patterns[p["pattern"]] = patterns.get(p["pattern"], 0) + 1
    return {"toroidal_patterns": patterns}

# --- function: mandelbrot_null_model ---
# composed_from=32 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def mandelbrot_null_model(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Compute significance of a simple alignment between behavior and a 3-6-9 style mapping.
    Observed statistic: S=1 if behavior in {"ESCAPING"→"OUTWARD","PERIODIC"→"TRANSFORM"} else 0.
    Null: permute labels 1,000x and compute rank-based p plus Cohen's d.
    """
    behavior = state["fractal"]["behavior"]
    # Map behavior → sacred class (demo)
    sacred_map = {"ESCAPING":"OUTWARD","BOUNDED":"INWARD","PERIODIC":"TRANSFORM"}
    obs = 1.0 if sacred_map.get(behavior) in ("OUTWARD","TRANSFORM") else 0.0

    # Build a tiny cohort by perturbing the text signature (if available)
    # Here we just reuse the same behavior 10× to keep it headless-speedy; real code would sample nearby c's.
    cohort = [obs for _ in range(10)]
    mu_obs = sum(cohort)/len(cohort)

    # Null via permutations: Bernoulli(0.5) draws as a stand-in
    N = 1000
    null = []
    for _ in range(N):
        # shuffled labels → draw same-size cohort with p=0.5
        k = sum(1 if random.random()<0.5 else 0 for _ in range(len(cohort)))
        null.append(k/len(cohort))

    mu = sum(null)/N
    sd = (sum((x-mu)**2 for x in null)/(N-1))**0.5 or 1.0

    # Rank-based p-value
    rank = sum(1 for x in null if x >= mu_obs)
    p = (rank + 1) / (N + 1)

    # Effect size (Cohen's d) of observed against null mean
    d = (mu_obs - mu) / sd
    return {"mndl_p_value": p, "mndl_effect_size": d, "mndl_stat": mu_obs, "null_mean": mu, "null_std": sd}

# --- function: toroidal_e8_nearest_root ---
# composed_from=36 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def toroidal_e8_nearest_root(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Project the centroid of toroidal shell points into E8 and estimate robustness:
    small perturbations should rarely flip the nearest-root identity.
    """
    from .embedding_e8 import _normalize, nearest_root
    # if toroidal patterns were not computed, generate a tiny shell
    pts = []
    if "toroidal_patterns" not in state:
        pts = generate_toroidal_shell(n_points=64, seed=system.cfg.seed)
    else:
        # regenerate to have coordinates (patterns-only state doesn't retain coords); small demo shell
        pts = generate_toroidal_shell(n_points=64, seed=system.cfg.seed)

    # build a naive 8D feature by aggregating simple moments (demo)
    # (mean x,y,z, var x,y,z, and a bias) → normalized
    xs = [p["x"] for p in pts]; ys = [p["y"] for p in pts]; zs = [p["z"] for p in pts]
    def var(a):
        m = sum(a)/len(a)
        return sum((x-m)**2 for x in a)/len(a)
    vec = [sum(xs)/len(xs), sum(ys)/len(ys), sum(zs)/len(zs),
           var(xs), var(ys), var(zs), 0.0, 1.0]
    v = _normalize(vec)
    base_root, base_dist = nearest_root(v)

    # perturbations
    flips = 0; D = []
    for _ in range(50):
        vp = [x + random.uniform(-1e-3, 1e-3) for x in v]
        rp, dp = nearest_root(vp)
        D.append(dp)
        if rp != base_root:
            flips += 1
    flip_rate = flips/50.0
    mean_dist = sum(D)/len(D)
    return {"torus_flip_rate": flip_rate, "torus_root_distance_mean": mean_dist}

# --- function: uvibs_windows ---
# composed_from=32 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2c621e2b7303__cqe_unified_cqe_unified__slice_impls.py
def uvibs_windows(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Evaluate multiple windows (W4/W80/Wexp/Monster) as a structured dict.
    Placeholder scoring: tie each to a phi_feature for now; real versions replace these.
    """
    pf = state["phi_features"]
    windows = {
        "W4": {"score": pf["geom"], "threshold": 0.7, "msg": "Coxeter-plane / local geometry"},
        "W80": {"score": pf["parity"], "threshold": 0.7, "msg": "E8x10 / lane parity window"},
        "Wexp": {"score": pf["sparsity"], "threshold": 0.6, "msg": "Exponential window / sparsity"},
        "Monster": {"score": pf["kissing"], "threshold": 0.8, "msg": "24D projection sanity"}
    }
    for k,v in windows.items():
        v["pass"] = v["score"] >= v["threshold"]
    return {"uvibs_windows": windows}

# --- function: phi_regimen_bench ---
# composed_from=28 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\31c1cc5741a6__cqe_unified_cqe_unified__slice_impls.py
def phi_regimen_bench(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Compare three simplistic regimens on the same features snapshot:
    A: static weights; B: annealed (slightly different weights); C: adaptive (rebalance by feature magnitude).
    Report final phi and deltas.
    """
    from .objective_phi import compute_phi
    feats = state["phi_features"]
    W_A = system.cfg.phi_weights
    W_B = {k:(v*0.95 if k!="geom" else v*1.05) for k,v in W_A.items()}
    # Adaptive: prioritize larger features
    s = sum(feats.values()) or 1.0
    W_C = {k:(0.25 + 0.75*(feats[k]/s))/4 for k in feats}  # renormalize roughly

    phi_A = compute_phi(feats, W_A)
    phi_B = compute_phi(feats, W_B)
    phi_C = compute_phi(feats, W_C)
    return {"phi_bench": {"A":phi_A, "B":phi_B, "C":phi_C, "C_minus_A":phi_C - phi_A, "B_minus_A":phi_B - phi_A}}

# --- function: pose_gauge_invariance ---
# composed_from=28 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\31c1cc5741a6__cqe_unified_cqe_unified__slice_impls.py
def pose_gauge_invariance(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generate two toroidal shells with theta/phi offsets and compare pattern distributions.
    Report L1 difference; smaller is more invariant.
    """
    base = generate_toroidal_shell(n_points=256, seed=system.cfg.seed, theta_offset=0.0, phi_offset=0.0)
    off  = generate_toroidal_shell(n_points=256, seed=system.cfg.seed, theta_offset=0.37, phi_offset=0.23)
    def dist(pts):
        d = {}
        for p in pts:
            d[p["pattern"]] = d.get(p["pattern"],0)+1
        total = sum(d.values())
        for k in d: d[k] /= total
        return d
    db, do = dist(base), dist(off)
    keys = set(db)|set(do)
    l1 = sum(abs(db.get(k,0)-do.get(k,0)) for k in keys)
    return {"pose_invariance_stat": 1.0 - 0.5*l1}  # 1==identical, 0==disjoint

# --- function: semantics_calibration ---
# composed_from=28 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\31c1cc5741a6__cqe_unified_cqe_unified__slice_impls.py
def semantics_calibration(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Build a tiny synthetic cohort around the current e8 root distance, produce confidences via extract_semantics,
    and compute Brier score + a simple ECE over 5 bins (toy). Labels are derived from a threshold on distance.
    """
    import math
    e8d = state["e8"]["root_distance"]
    xs = [max(0.0, min(1.0, e8d + (i-5)*0.02)) for i in range(11)]
    preds = []
    labels = []
    for x in xs:
        sem = extract_semantics(e8_distance=x, angle_hint=0.2)
        p = max(0.0, min(1.0, sem["confidence"]))  # already 0..1-ish
        y = 1 if x < 0.25 else 0  # toy ground truth: NEAR→1
        preds.append(p); labels.append(y)
    # Brier
    brier = sum((p - y)**2 for p,y in zip(preds, labels)) / len(labels)
    # ECE with 5 bins
    bins = [[] for _ in range(5)]
    for p,y in zip(preds, labels):
        idx = min(4, int(p*5))
        bins[idx].append((p,y))
    ece = 0.0
    for b in bins:
        if not b: continue
        conf = sum(p for p,_ in b)/len(b)
        acc = sum(y for _,y in b)/len(b)
        ece += (len(b)/len(labels)) * abs(conf-acc)
    return {"sem_calibration": {"brier": brier, "ece5": ece, "n": len(labels)}}

# --- function: _digital_root ---
# composed_from=24 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\31c1cc5741a6__cqe_unified_cqe_unified__slice_impls.py
def _digital_root(n: int) -> int:
    n = abs(n)
    while n >= 10:
        s = 0
        while n > 0:
            s += n % 10
            n //= 10
        n = s
    return n

# --- function: _get ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\5c456209e379__src_cqe_core__spine.py
def _get(mod, attr: str):
    return getattr(mod, attr)

# --- function: carlson_correspondence_check ---
# composed_from=24 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\31c1cc5741a6__cqe_unified_cqe_unified__slice_impls.py
def carlson_correspondence_check(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    invariants = {"dim_E8": 8, "roots": 240, "weyl_order": 696729600, "coxeter_number": 30}
    drs = {k: _digital_root(v) for k,v in invariants.items()}
    sacred_set = {3,6,9}
    observed = sum(1 for v in drs.values() if v in sacred_set)
    import random, json, os
    s = "".join(str(v) for v in invariants.values())
    N = 200
    null = []
    for _ in range(N):
        t = "".join(random.sample(s, len(s)))
        chunks = [t[:1], t[1:4], t[4:13], t[13:]]
        vals = [int(c) if c else 0 for c in chunks]
        d = [_digital_root(x) for x in vals]
        null.append(sum(1 for x in d if x in sacred_set))
    mu = sum(null)/N
    sd = (sum((x-mu)**2 for x in null)/(N-1))**0.5 or 1.0
    z = (observed - mu)/sd
    exhibit = {"invariants": invariants, "digital_roots": drs, "observed_sacred_hits": observed, "null_mean": mu, "null_sd": sd, "z_score": z}
    path = os.path.join(system.cfg.artifacts_dir, f"carlson_exhibit_{system.run_id}.json")
    with open(path, "w") as fh:
        json.dump(exhibit, fh, indent=2)
    system.emit("carlson_exhibit", {"artifact": path})
    return {"carlson_exhibit": path}

# --- function: governance_recommendations ---
# composed_from=24 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\31c1cc5741a6__cqe_unified_cqe_unified__slice_impls.py
def governance_recommendations(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    feats = state["phi_features"]
    recs = []
    if feats["geom"] < 0.7:
        recs.append("Improve geometric alignment: run morsr_complete_traversal to search better root alignment.")
    if feats["parity"] < 0.7:
        recs.append("Strengthen lane parity features; consider W80 tuning.")
    if feats["sparsity"] < 0.6:
        recs.append("Promote sparsity; prune low-signal atoms.")
    if feats["kissing"] < 0.8:
        recs.append("Check local packing; adjust toroidal shell parameters.")
    return {"recommendations": recs}

# --- function: morsr_complete_traversal ---
# composed_from=24 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\31c1cc5741a6__cqe_unified_cqe_unified__slice_impls.py
def morsr_complete_traversal(system, payload: Dict[str, Any], state: Dict[str, Any]) -> Dict[str, Any]:
    from .e8_lattice import normalized_e8_roots, chamber_signature
    v = state["e8"]["vector"]
    roots = normalized_e8_roots()
    best = {"score": -1e9, "index": None, "root": None, "chamber": None}
    scores = []
    chambers = {}
    from .embedding_e8 import cosine
    for i, r in enumerate(roots):
        s = cosine(v, r)
        ch = chamber_signature(r)
        scores.append(s)
        chambers[ch] = chambers.get(ch, 0) + 1
        system.emit("morsr_node", {"i": i, "score": s, "chamber": ch})
        if s > best["score"]:
            best.update({"score": s, "index": i, "root": r, "chamber": ch})
    overlay = {
        "best": best,
        "score_min": min(scores), "score_max": max(scores), "score_mean": sum(scores)/len(scores),
        "chambers": chambers, "n": len(scores)
    }
    import json, os
    path = os.path.join(system.cfg.artifacts_dir, f"morsr_overlay_{system.run_id}.json")
    with open(path, "w") as fh:
        json.dump(overlay, fh, indent=2)
    system.emit("morsr_overlay", {"artifact": path})
    return {"morsr_best": best, "morsr_overlay_path": path}

# --- function: read_json ---
# composed_from=22 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\cqe_api_server.py
def read_json(environ):
    try: length = int(environ.get('CONTENT_LENGTH','0'))
    except (ValueError): length = 0
    body = environ['wsgi.input'].read(length) if length>0 else b'{}'
    return json.loads(body.decode('utf-8') or "{}")

# --- function: text_to_faces ---
# composed_from=14 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\9051c9818113__cqe_core__cqe_harness_v2.py
def text_to_faces(text: str) -> Tuple[Face, Face]:
    """Map text into two aligned numeric streams: mod10 (decagon) and mod8 (octagon). Deterministic."""
    # FNV-1a 64-bit rolling hash over bytes; split into bases.
    h = 0xcbf29ce484222325  # FNV offset
    d10: List[int] = []
    d8: List[int] = []
    for ch in text.encode("utf-8", errors="ignore"):
        h ^= ch
        h = (h * 0x100000001b3) & ((1<<64)-1)  # FNV prime
        d10.append((h // 2654435761) % 10)
        d8.append((h // 11400714819323198485) % 8)
    if not d10:
        d10 = [0]; d8 = [0]
    return Face(d10, 10, "decagon"), Face(d8, 8, "octagon")

# --- function: now_stamp ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\56f232645b80__cqe_core__cqe_harness_v1.py
def now_stamp() -> str:
    return datetime.utcnow().strftime("%Y%m%d_%H%M%S")

# --- function: sha256_hex ---
# composed_from=11 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\9051c9818113__cqe_core__cqe_harness_v2.py
def sha256_hex(obj: Any) -> str:
    b = json.dumps(obj, sort_keys=True, ensure_ascii=False, default=_json_default).encode("utf-8")
    return hashlib.sha256(b).hexdigest()

# --- function: ladder_hook ---
# composed_from=22 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\5eb9a193b215__cqe_core__cqe_complete_system.py
def ladder_hook(func):
    """Decorator to escalate module interactions via Jacob's ladder."""
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        result = func(self, *args, **kwargs)
        if hasattr(self, 'lit_paths'):
            self.lit_paths += 1
        return result
    return wrapper

# --- function: mainspace_context ---
# composed_from=17 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\5eb9a193b215__cqe_core__cqe_complete_system.py
def mainspace_context():
    """Context manager to bound CQE operations."""
    yield
    print("MainSpace context released.")

# --- function: _import ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\5c456209e379__src_cqe_core__spine.py
def _import(path: str):
    return importlib.import_module(path)

# --- function: dwm_charter_init ---
# composed_from=16 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\52a4955c2192__cqe_unified_cqe_unified__slice_impls.py
def dwm_charter_init(system, payload, state):
    charter = {
        "llm_first": True,
        "cqe_augmented": True,
        "harness2": {"native":"planner","support":"worker"},
        "gate": {"parity":"even","delta_phi":"<=0"},
        "operators": {"×":"diagonal_shift","÷":"midpoint_smooth","%":"toroidal_residue","~":"parity_mirror","#2":"occupancy_target_2"},
        "categories": {"TRIANGLE":["×","÷","#2"],"LOOP":["÷","~"],"FLOW_SIGMOID":["%","÷"],"MULTI_STROKE":["%","÷","~"],"BARS":["÷"]},
        "evidence_channels": ["runner","itinerary","category","macro","analysis","readme","pdf","tools"],
        "sources_priority": ["project_corpus","irl_refs_when_uncertain","session_tokens"],
        "change_control": {"semver": True, "receipt_schema_change":"major"}
    }
    system.emit("dwm_charter", charter)
    system._overlay_registry = {}
    system._hyperperm_oracle = {"items":{}}
    return {"dwm_charter": charter, "overlay_registry": system._overlay_registry, "hyperperm_oracle": system._hyperperm_oracle}

# --- function: glyphs_apply_overlay ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\3e6cdad747b4__cqe_unified_cqe_unified__slice_impls.py
def glyphs_apply_overlay(system, payload, state):
    """
    Apply an overlay (program) for a glyph on a simple pose state using one rung with parallel rails.
    payload: {"glyph":"A","rails":[["×","÷","#2"],["÷","~"]]}
    """
    from .glyphs_lambda import init_state, run_rung, compute_phi, OverlayRegistry
    glyph = payload.get("glyph","A")
    rails = payload.get("rails",[["×","÷","#2"],["÷","~"]])
    S0 = init_state(n=8, seed=system.cfg.seed)
    S1, rec = run_rung(S0, rails)
    system.emit("glyph_rung", {"glyph": glyph, **rec})
    return {"glyph_receipt": rec}

# --- function: hyperperm_update ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\3e6cdad747b4__cqe_unified_cqe_unified__slice_impls.py
def hyperperm_update(system, payload, state):
    """
    Update hyperpermutation oracle with an observed ordering from a given channel.
    payload: {"atoms":["×","÷","%","~"], "sequence":["%","÷","~"], "channel":"runner"}
    """
    try:
        from .glyphs_lambda import HyperpermOracle
    except ImportError:
        return {
            "hyperperm_status": {
                "skipped": True,
                "reason": "glyphs_lambda unavailable (CQE operator-order oracle gated)",
            }
        }
    if not hasattr(system, "_hyperperm"):
        system._hyperperm = HyperpermOracle()
    atoms = payload.get("atoms",["×","÷","%","~"])
    seq = payload.get("sequence",["%","÷","~"])
    ch = payload.get("channel","runner")
    status = system._hyperperm.add_order(atoms, seq, ch)
    system.emit("hyperperm", {"key":"|".join(sorted(atoms)), "locked": status["locked"], "count": len(status["orders"])})
    return {"hyperperm_status": {"locked": status["locked"], "n": len(status["orders"]) }}

# --- function: pose_optimizer ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\3e6cdad747b4__cqe_unified_cqe_unified__slice_impls.py
def pose_optimizer(system, payload, state):
    """
    Search simple pose transforms (cyclic shifts and sign flips) to improve nearest-root cosine.
    """
    from .embedding_e8 import nearest_root
    v = state["e8"]["vector"]
    best = (v, nearest_root(v)[1])  # distance = 1-cos; lower better
    # generate candidates
    def shifts(vec):
        for s in range(len(vec)):
            yield vec[s:]+vec[:s]
    def sign_flips(vec):
        for mask in range(1<<3):  # flip up to 3 dims for speed
            vv = vec[:]
            for i in range(3):
                if (mask>>i)&1: vv[i] = -vv[i]
            yield vv
    for cand in shifts(v):
        for c2 in sign_flips(cand):
            d = nearest_root(c2)[1]
            if d < best[1]:
                best = (c2, d)
    gain = state["e8"]["root_distance"] - best[1]
    system.emit("pose_search", {"gain": gain, "improved": gain>0})
    return {"pose_optimized": best[0], "pose_gain": gain}

# --- function: serve ---
# composed_from=12 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\cqe_api_server.py
def serve(host="127.0.0.1", port=9091):
    httpd = make_server(host, port, app)
    print(f"Viewer24 v2 + CA + Inverse on http://{host}:{port}")
    httpd.serve_forever()

# --- function: uvibs_monster_validate ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\3e6cdad747b4__cqe_unified_cqe_unified__slice_impls.py
def uvibs_monster_validate(system, payload, state):
    """
    Compute UVIBS (W4/W80/Wexp) and a Monster-style 24D heuristic, emit scores and pass flags.
    """
    from .uvibs_monster import w4_geometry, w80_parity_stability, wexp_sparsity, monster_24D_projection, monster_pass
    v = state["e8"]["vector"]
    w4 = w4_geometry(v)
    w80 = w80_parity_stability(v)
    wexp = wexp_sparsity(v)
    inv = monster_24D_projection(v)
    mon = monster_pass(inv)
    windows = {
        "W4": {"score": w4, "threshold": 0.7, "pass": w4>=0.7},
        "W80": {"score": w80, "threshold": 0.7, "pass": w80>=0.7},
        "Wexp": {"score": wexp, "threshold": 0.6, "pass": wexp>=0.6},
        "Monster": {"score": mon, "threshold": 0.6, "pass": mon>=0.6, "invariants": inv}
    }
    system.emit("uvibs_monster", {"windows": windows})
    return {"uvibs_monster": windows}

# --- function: app ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\cqe_api_server.py
def app(environ, start_response):
    path = environ.get('PATH_INFO','/'); method = environ.get('REQUEST_METHOD','GET')

    if path == "/api/load" and method == "POST":
        payload = read_json(environ); SESSION["points"]=payload.get("points") or []; SESSION["meta"]=payload.get("meta") or {}
        return respond(start_response,'200 OK',{"ok":True,"count":len(SESSION["points"])})
    if path == "/api/screens":
        labs = NIEMEIER_SPECS + ["LEECH"]
        return respond(start_response,'200 OK',{"screens":[{"index":i,"label":lab} for i,lab in enumerate(labs)]})
    if path == "/api/frame":
        q = parse_qs(environ.get('QUERY_STRING','')); w=int(q.get('w',['320'])[0]); h=int(q.get('h',['180'])[0])
        s,tx,ty = world_to_screen(SESSION.get("points") or [], w, h, padding=0.08)
        return respond(start_response,'200 OK',{"s":s,"tx":tx,"ty":ty})
    # CA controls
    if path == "/api/ca/init":
        q = parse_qs(environ.get('QUERY_STRING','')); n=int(q.get('n',['64'])[0])
        global CA,N,INV; N=n; CA=DihedralCA(tiles_x=TILES_X, tiles_y=TILES_Y, n=N, seed=1337); CA.seed_from_specs(NIEMEIER_SPECS+["LEECH"]); INV = ResidueAnalyzer(CA)
        return respond(start_response,'200 OK',{"ok":True,"n":N})
    if path == "/api/ca/step":
        q = parse_qs(environ.get('QUERY_STRING','')); steps=int(q.get('steps',['1'])[0]); kappa=float(q.get('kappa',['0.08'])[0])
        for _ in range(steps): CA.step(kappa=kappa, dual=True)
        return respond(start_response,'200 OK',{"ok":True,"step":CA.step_id})
    if path == "/api/ca/tile":
        q = parse_qs(environ.get('QUERY_STRING','')); idx=int(q.get('index',['0'])[0]); alpha=int(q.get('alpha',['160'])[0])
        tile = CA.tile_pixels_em(idx, alpha=alpha); return respond(start_response,'200 OK',tile)
    # Inverse/residue endpoints
    if path == "/api/inverse/baseline":
        INV.capture_baseline(); return respond(start_response,'200 OK',{"ok":True})
    if path == "/api/inverse/tile":
        q = parse_qs(environ.get('QUERY_STRING','')); idx=int(q.get('index',['0'])[0])
        tile = INV.residue_tile(idx)
        return respond(start_response,'200 OK',tile)
    # Static
    if path == "/":
        with open("./static/index.html","rb") as f: data=f.read()
        start_response('200 OK',[('Content-Type','text/html')]); return [data]
    if path == "/inverse":
        with open("./static/inverse.html","rb") as f: data=f.read()
        start_response('200 OK',[('Content-Type','text/html')]); return [data]
    if path.startswith("/static/"):
        p = "."+path
        if not os.path.exists(p): start_response('404 NOT FOUND',[('Content-Type','text/plain')]); return [b'not found']
        ctype="text/plain"
        if p.endswith(".html"): ctype="text/html"
        if p.endswith(".js"): ctype="text/javascript"
        if p.endswith(".css"): ctype="text/css"
        with open(p,"rb") as f: data=f.read()
        start_response('200 OK',[('Content-Type',ctype)]); return [data]
    start_response('404 NOT FOUND',[('Content-Type','application/json')]); return [b'{}']

# --- function: governance_lock_and_seal ---
# composed_from=16 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\52a4955c2192__cqe_unified_cqe_unified__slice_impls.py
def governance_lock_and_seal(system, payload, state):
    from .dwm_support import seal_envelope
    receipts = payload.get("receipts", [])
    witnesses = payload.get("witnesses", [])
    quorum = payload.get("quorum", {"type":"majority","k":1})
    qpass = len(witnesses) >= quorum.get("k",1)
    seal_path, root = seal_envelope(system.run_id, receipts, state.get("dwm_charter", {}), witnesses, system.cfg.artifacts_dir)
    system.emit("governance_seal", {"root": root, "qpass": qpass})
    return {"seal_path": seal_path, "merkle_root": root, "quorum_pass": qpass}

# --- function: harness2_turn ---
# composed_from=16 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\52a4955c2192__cqe_unified_cqe_unified__slice_impls.py
def harness2_turn(system, payload, state):
    from .glyphs_lambda import init_state, run_rung
    from .dwm_support import make_startup_packet, make_pause_token, make_resume_token
    demand = payload.get("demand", {"category":"MULTI_STROKE","rails":[["%","÷","~"],["÷","~"]]})
    S0 = init_state(n=8, seed=system.cfg.seed)
    rails = demand.get("rails", [["÷"],["÷","~"]])
    S1, rec = run_rung(S0, rails)
    rec["rung"] = 1
    receipts = [rec]
    supply = {"accepted": rec["accepted"], "winner_seq": rec["winner_seq"], "phi_after": rec["phi_after"]}
    spath = make_startup_packet(system.run_id, demand, receipts, {"note":"demo turn"}, system.cfg.artifacts_dir)
    ptoken = make_pause_token(system.run_id, pointer=spath, outdir=system.cfg.artifacts_dir)
    rtoken = make_resume_token(system.run_id, pointer=spath, outdir=system.cfg.artifacts_dir)
    system.emit("harness2", {"demand": demand, "supply": supply, "startup_packet": spath})
    return {"startup_packet": spath, "demand": demand, "supply": supply, "pause_token": ptoken, "resume_token": rtoken}

# --- function: respond ---
# composed_from=22 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\cqe_api_server.py
def respond(start_response, status, obj, ctype="application/json"):
    data = json.dumps(obj).encode("utf-8")
    start_response(status, [('Content-Type', ctype), ('Content-Length', str(len(data)))])
    return [data]

# --- function: sha256_json ---
# composed_from=12 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\064d9231b45d__cqe_harness__orchestrator.py
def sha256_json(obj: Any) -> str:
    b = json.dumps(obj, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(b).hexdigest()

# --- function: e8_nearest ---
# composed_from=19 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2dccdc708e35__cqe_experimental__o8.py
def e8_nearest(y):
    z0 = np.rint(y)
    if (int(np.sum(z0)) & 1) == 1:
        frac = np.abs(y - z0); k = int(np.argmin(frac))
        z0[k] += 1 if y[k] > z0[k] else -1
    d0 = np.linalg.norm(y - z0)
    yh = y - 0.5
    z1 = np.rint(yh)
    if (int(np.sum(z1)) & 1) == 1:
        frac = np.abs(yh - z1); k = int(np.argmin(frac))
        z1[k] += 1 if yh[k] > z1[k] else -1
    x1 = z1 + 0.5
    d1 = np.linalg.norm(y - x1)
    if d0 <= d1:
        return z0, d0, d0, d1, "int", x1
    else:
        return x1, d1, d0, d1, "half", z0

# --- function: run_cqe_daemon ---
# composed_from=12 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\6b2a9bd6431a__cqe_modules__cqe_operating_system.py
def run_cqe_daemon(config: CQEOSConfig = None):
    """Run CQE OS as daemon"""
    os_instance = create_cqe_os(config)
    
    try:
        os_instance.run_daemon()
    finally:
        os_instance.shutdown()

# --- function: coset_margin ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2dccdc708e35__cqe_experimental__o8.py
def coset_margin(di, dh, eps=1e-9):
    return np.abs(di - dh) / (di + dh + eps)

# --- function: create_ultimate_cqe_system ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\6464e95b7018__cqe_modules__complete_system.py
def create_ultimate_cqe_system(governance_type: str = "ultimate", **kwargs) -> UltimateCQESystem:
    """Factory function to create ultimate CQE system."""
    governance_enum = AdvancedGovernanceType(governance_type.lower())
    return UltimateCQESystem(governance_type=governance_enum, **kwargs)

# --- function: fixed_rotations ---
# composed_from=12 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2dccdc708e35__cqe_experimental__o8.py
def fixed_rotations(seed=2025):
    rng = np.random.default_rng(seed)
    A = rng.normal(size=(8,8)); Q, _ = np.linalg.qr(A)
    H = hadamard8()
    Sflip = np.diag([1,1,1,1,-1,-1,-1,-1])
    return [np.eye(8), H, Q, Sflip@H]

# --- function: hadamard8 ---
# composed_from=13 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\2dccdc708e35__cqe_experimental__o8.py
def hadamard8():
    H2 = np.array([[1,1],[1,-1]],float)
    H4 = np.kron(H2,H2)
    H8 = np.kron(H4,H2)
    return H8/np.sqrt(8.0)

# --- function: create_enhanced_cqe_system ---
# composed_from=11 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\855fc69e15a0__cqe_modules__unified_system.py
def create_enhanced_cqe_system(governance_type: str = "hybrid", **kwargs) -> EnhancedCQESystem:
    """Factory function to create enhanced CQE system with specified governance."""
    governance_enum = GovernanceType(governance_type.lower())
    return EnhancedCQESystem(governance_type=governance_enum, **kwargs)

# --- function: demonstrate_sacred_geometry_cqe ---
# composed_from=11 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\core_demonstrate_sacred_geometry_cqe.py
def demonstrate_sacred_geometry_cqe():
    """Demonstrate the sacred geometry enhanced CQE system"""
    
    print("Sacred Geometry Enhanced CQE System Demonstration")
    print("=" * 60)
    
    # Initialize system
    sacred_cqe = SacredGeometryEnhancedCQE()
    
    # Test with sacred frequencies
    sacred_frequencies = [432, 528, 396, 741, 852, 963]
    
    print("\n1. Sacred Frequency Analysis:")
    for freq in sacred_frequencies:
        atom = sacred_cqe.create_sacred_atom(freq)
        print(f"  {freq} Hz -> Digital Root: {atom.digital_root}, Pattern: {atom.rotational_pattern.value}")
        print(f"    Classification: {atom.carlson_classification}")
        print(f"    Resonance: {atom.resonance_alignment}")
    
    # Test time-space integration
    print("\n2. Time-Space Integration:")
    time_data = [1, 2, 4, 8, 16, 32]  # Doubling sequence
    space_data = [3, 6, 12, 24, 48, 96]  # Tripling sequence
    
    combined_embeddings = sacred_cqe.embed_temporal_patterns_in_e8(time_data, space_data)
    print(f"  Combined {len(combined_embeddings)} time-space embeddings")
    print(f"  First embedding shape: {combined_embeddings[0].shape}")
    
    # Analyze natural constants
    print("\n3. Natural Constants Analysis:")
    constants_analysis = sacred_cqe.analyze_natural_constants()
    
    for constant_name, analysis in constants_analysis.items():
        print(f"  {constant_name}:")
        print(f"    Digital Root: {analysis['digital_root']}")
        print(f"    Pattern: {analysis['rotational_pattern']}")
        print(f"    Sacred Frequency: {analysis['sacred_frequency']} Hz")
        print(f"    Classification: {analysis['carlson_classification']}")
    
    print("\n4. Sacred Geometry Validation:")
    
    # Test 9/6 pattern recognition
    test_values = [9, 18, 27, 6, 12, 24, 3, 21, 30]
    
    for value in test_values:
        atom = sacred_cqe.create_sacred_atom(value)
        expected_pattern = "INWARD" if value % 9 == 0 else ("OUTWARD" if value % 6 == 0 else "CREATIVE")
        actual_pattern = atom.rotational_pattern.value
        
        match = "✓" if expected_pattern in actual_pattern else "✗"
        print(f"  {value} -> Expected: {expected_pattern}, Got: {actual_pattern} {match}")
    
    print("\nSacred Geometry Enhanced CQE System Demonstration Complete!")

# --- function: generate_e8_state ---
# composed_from=20 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\8a163c7d76bb__Bestbuild101325_2__Best_build_101325__CQE_GVS_MONOLITH.py
def generate_e8_state(seed: Optional[int] = None) -> np.ndarray:
    """Generate random E8 state vector."""
    if seed is not None:
        np.random.seed(seed)
    
    # Generate random vector
    vector = np.random.randn(E8_DIM)
    
    # Normalize to E8 manifold
    norm = np.linalg.norm(vector)
    if norm > 0:
        vector = vector / norm * E8_NORM
    
    return vector

# --- function: _json_default ---
# composed_from=11 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\9051c9818113__cqe_core__cqe_harness_v2.py
def _json_default(o: Any) -> str:
    try:
        return repr(o)
    except Exception:
        return f"<unrepr {type(o).__name__}>"

# --- function: _rot2 ---
# composed_from=10 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\cqe\partsfactory\cqe_time.py
def _rot2(x: float, y: float, theta: float) -> Tuple[float, float]:
    c, s = math.cos(theta), math.sin(theta)
    return c*x - s*y, s*x + c*y
