"""
Constant canonicals for the `interrogation` family.

6 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- assign: BLOCK ---
# composed_from=17 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\mmdb\mmdb_memory\mmdb__3.py
BLOCK = os.getenv("TMN2_BLOCK", "data")

# --- assign: PG_URL ---
# composed_from=38 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\interrogation\partsfactory\interrogation.py
PG_URL = os.getenv("PG_URL", "postgresql://tmn2:tmn2_dev@tmn2-pg:5432/tmn2")

# --- assign: COOP_URL ---
# composed_from=13 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\morphon\morphonic\morphon.py
COOP_URL = os.environ.get("COOP_URL", "http://tmn2-coop:8000")

# --- assign: GATEWAY_URL ---
# composed_from=11 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\interrogation\partsfactory\interrogation.py
GATEWAY_URL = os.getenv("GATEWAY_URL", "http://tmn2-gateway:8000")

# --- assign: THINKTANK_URL ---
# composed_from=14 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\interrogation\partsfactory\interrogation.py
THINKTANK_URL = os.getenv("THINKTANK_URL", "http://tmn2-thinktank:8000")

# --- assign: _pg_conn ---
# composed_from=30 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\interrogation\partsfactory\interrogation.py
_pg_conn = None
