"""
Function canonicals for the `interrogation` family.

1 entries, auto-generated by place_canonicals.py.
"""
from __future__ import annotations

# --- function: _get_pg ---
# composed_from=11 witness=D:\PartsFactory\CMPLX-PartsFactory\staging\by-family\interrogation\partsfactory\interrogation.py
def _get_pg():
    global _pg_conn
    if not PG_URL:
        return None
    try:
        import psycopg2
        if _pg_conn is None or _pg_conn.closed:
            _pg_conn = psycopg2.connect(PG_URL)
            _pg_conn.autocommit = True
        return _pg_conn
    except Exception as e:
        logger.warning("PG not available: %s", e)
        return None
