"""
Composed canonical: E8Lattice

Family: e8lattice
Decision: batch=7 id=415
Composition: method-union of 28 variants → 100 methods (89 conflicts resolved), 6 attrs

Auto-generated by place_canonicals.py from the atomic decision queue.
Do not edit by hand — re-run the merger to refresh.
"""
from __future__ import annotations

class E8Lattice:
    """E8 exceptional Lie group lattice operations."""
    SIMPLE_ROOTS = [np.array([0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, 0.5]), np.array([1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), np.array([-1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), np.array([0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]), np.array([0.0, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 0.0]), np.array([0.0, 0.0, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0]), np.array([0.0, 0.0, 0.0, 0.0, -1.0, 1.0, 0.0, 0.0]), np.array([0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 1.0, 0.0])]
    KISSING_NUMBER = 240
    MINIMAL_NORM_SQ = 2
    DIMENSION = 8
    ROOT_COUNT = 240
    _instance: Optional['E8Lattice'] = None

    def __init__(self):
        """Initialize the E8 lattice."""
        self.dimension = 8
        self.num_roots = 240
        self.basis = self._construct_e8_basis()
        self.roots = self._generate_roots()
        from ..weyl import WeylChamberNavigator
        simple_roots = self.roots[:8]
        self.weyl_navigator = WeylChamberNavigator(simple_roots)

    def __repr__(self) -> str:
        return f'E8Lattice(dim={self.dimension}, roots={self.num_roots})'

    def add(self, v1: E8Vector, v2: E8Vector) -> E8Vector:
        """Add two vectors."""
        return v1 + v2

    def babai_nearest(self, y):
        y = np.asarray(y, dtype=float)
        z = np.linalg.solve(self.R, self.Q.T @ y)
        z_round = np.round(z)
        x = self.A @ z_round
        return x

    def basis(self, index: int) -> E8Vector:
        """Return basis vector."""
        return E8Vector.basis(index)

    def cartan_distance(self, point1: np.ndarray, point2: np.ndarray) -> float:
        """Compute distance using Cartan metric"""
        diff = point1 - point2
        return np.sqrt(np.dot(diff, np.dot(self.cartan_matrix, diff)))

    def cartan_matrix(self) -> List[List[int]]:
        """
        Return E8 Cartan matrix (8x8).

        The Cartan matrix encodes the simple root structure.
        """
        return [[2, -1, 0, 0, 0, 0, 0, 0], [-1, 2, -1, 0, 0, 0, 0, 0], [0, -1, 2, -1, 0, 0, 0, 0], [0, 0, -1, 2, -1, 0, 0, 0], [0, 0, 0, -1, 2, -1, 0, -1], [0, 0, 0, 0, -1, 2, -1, 0], [0, 0, 0, 0, 0, -1, 2, 0], [0, 0, 0, 0, -1, 0, 0, 2]]

    def chamber_distance(self, vec1: np.ndarray, vec2: np.ndarray) -> float:
        """Calculate chamber-aware distance between vectors."""
        proj1 = self.project_to_chamber(vec1)
        proj2 = self.project_to_chamber(vec2)
        return np.linalg.norm(proj1 - proj2)

    def closest_vector(self, query: np.ndarray) -> Tuple[np.ndarray, float]:
        """
        Find closest lattice point to query (CVP for E8).

        Uses simple rounding for efficiency.
        """
        rounded = np.round(query)
        if sum(rounded) % 2 != 0:
            errors = [(query[i] - rounded[i]) ** 2 for i in range(8)]
            min_idx = errors.index(min(errors))
            rounded[min_idx] += 1
        dist = np.linalg.norm(rounded - query)
        return (rounded, dist)

    def compute_digital_root(self, vector: np.ndarray) -> int:
        """Compute digital root (0-9) from E8 vector."""
        total = int(np.sum(np.abs(vector)) * 1000)
        while total >= 10:
            total = sum((int(d) for d in str(total)))
        return total if total > 0 else 9

    def compute_parity_channels(self, vector: np.ndarray) -> np.ndarray:
        """Compute 24 parity channels from E8 vector."""
        channels = np.zeros(24)
        channels[:8] = vector
        for i in range(8, 24):
            mod = i % 3 + 3
            channels[i] = np.sum(vector) * COUPLING * i % mod
        return channels

    def coxeter_number(self) -> int:
        """Return Coxeter number of E8 (30)."""
        return 30

    def determinant(self):
        return abs(np.linalg.det(self.B))

    def determine_chamber(self, vector: np.ndarray) -> Tuple[str, np.ndarray]:
        """Determine which Weyl chamber contains the vector."""
        if len(vector) != 8:
            raise ValueError('Vector must be 8-dimensional')
        inner_products = np.dot(self.simple_roots, vector)
        signs = np.sign(inner_products)
        is_fundamental = np.all(signs >= 0)
        chamber_sig = ''.join(['1' if s >= 0 else '0' for s in signs])
        return (chamber_sig, inner_products)

    def distance(self, coord1: np.ndarray, coord2: np.ndarray) -> float:
        """Calculate E₈ distance between two coordinates."""
        return np.linalg.norm(coord1 - coord2)

    @staticmethod
    def distance_in_e8(v1: np.ndarray, v2: np.ndarray) -> float:
        """
        Calculate distance between two points in E8 space.

        Args:
            v1: First 8D vector
            v2: Second 8D vector

        Returns:
            float: Euclidean distance
        """
        return np.linalg.norm(v1 - v2)

    def distance_to_lattice(self, vector: np.ndarray) -> float:
        """
        Compute distance from vector to nearest E8 lattice point.

        Args:
            vector: 8D input vector

        Returns:
            Euclidean distance to nearest lattice point
        """
        projected = self.project(vector)
        return np.linalg.norm(vector - projected)

    def dot(self, v1: E8Vector, v2: E8Vector) -> float:
        """Dot product."""
        return v1.dot(v2)

    def dot_product(self, v1: np.ndarray, v2: np.ndarray) -> float:
        """Compute standard dot product"""
        return float(np.dot(v1, v2))

    @staticmethod
    def dot_product_e8(v1: np.ndarray, v2: np.ndarray) -> float:
        """
        Calculate dot product in E8 space.

        Args:
            v1: First 8D vector
            v2: Second 8D vector

        Returns:
            float: Dot product
        """
        return np.dot(v1, v2)

    def dynkin_diagram(self) -> str:
        """Return ASCII Dynkin diagram."""
        return '\n        O---O---O---O---O---O---O\n                            |\n                            O\n        '

    def embed_data(self, data: Any) -> np.ndarray:
        """
        Embed arbitrary data into E₈ lattice space.

        Args:
            data: Any data type to embed

        Returns:
            8D numpy array representing E₈ coordinates
        """
        data_hash = hashlib.sha256(str(data).encode()).digest()
        coords = []
        for i in range(8):
            byte_slice = data_hash[i * 4:(i + 1) * 4]
            if len(byte_slice) == 4:
                int_value = struct.unpack('I', byte_slice)[0]
                coord_value = (int_value % 2000000 - 1000000) / 1000000.0
            else:
                coord_value = 0.0
            coords.append(coord_value)
        coords = np.array(coords)
        norm = np.linalg.norm(coords)
        if norm > 0:
            coords = coords / norm
        else:
            coords = np.array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        return coords

    @staticmethod
    def embed_to_e8(data: np.ndarray) -> np.ndarray:
        """
        Embed arbitrary data into E8 lattice space.

        Args:
            data: Input data (any shape)

        Returns:
            np.ndarray: 8D E8 embedding
        """
        flat = data.flatten()
        if len(flat) < 8:
            embedded = np.pad(flat, (0, 8 - len(flat)), 'constant')
        elif len(flat) > 8:
            embedded = np.zeros(8)
            for i, val in enumerate(flat):
                embedded[i % 8] += val
        else:
            embedded = flat
        projected = E8Lattice.project_to_e8(embedded)
        normalized = E8Lattice.normalize_to_e8_norm(projected)
        return normalized

    def embed_vector(self, vector: List[float]) -> np.ndarray:
        """Embed vector into E8 lattice."""
        v = np.array(vector[:8])
        norm = np.linalg.norm(v)
        if norm > 0:
            v = v / norm
        return v

    def face_rotation(self, vector: np.ndarray, angle: float) -> np.ndarray:
        """Rotate E8 face - generates different solution paths (P vs NP)."""
        result = vector.copy()
        result = self.rotate_e8(result, 0, 1, angle)
        result = self.rotate_e8(result, 2, 3, angle * PHI)
        result = self.rotate_e8(result, 4, 5, angle * PHI ** 2)
        result = self.rotate_e8(result, 6, 7, angle * PHI ** 3)
        return self.project_to_manifold(result)

    def find_nearest_root(self, vector: np.ndarray) -> Tuple[int, np.ndarray]:
        """
        Find the nearest root to a given vector.

        Args:
            vector: 8D input vector

        Returns:
            Tuple of (root_index, root_vector)
        """
        if len(vector) != 8:
            raise ValueError(f'Expected 8D vector, got {len(vector)}D')
        distances = np.linalg.norm(self.roots - vector, axis=1)
        nearest_idx = np.argmin(distances)
        return (nearest_idx, self.roots[nearest_idx])

    def find_weyl_chamber(self, vector: np.ndarray) -> int:
        """Find which Weyl chamber contains the vector."""
        dots = [np.dot(vector, chamber) for chamber in self.weyl_chambers]
        return np.argmax(dots)

    def fingerprint(self, v: E8Vector) -> str:
        """Generate fingerprint."""
        return v.fingerprint()

    def from_leech_projection(self, leech_coords: List[float]) -> E8Vector:
        """
        Reconstruct E8 vector from Leech projection.

        Averages the 3 copies.
        """
        if len(leech_coords) < 24:
            leech_coords = leech_coords + [0.0] * (24 - len(leech_coords))
        e8_coords = []
        for i in range(8):
            avg = (leech_coords[i] + leech_coords[i + 8] + leech_coords[i + 16]) / 3
            e8_coords.append(avg)
        return E8Vector(tuple(e8_coords))

    def generate_chamber_samples(self, chamber_sig: str, count: int=10) -> np.ndarray:
        """Generate random samples from specified Weyl chamber."""
        samples = []
        for _ in range(count * 3):
            vec = np.random.randn(8)
            projected = self.project_to_chamber(vec, chamber_sig)
            actual_chamber, _ = self.determine_chamber(projected)
            if actual_chamber == chamber_sig:
                samples.append(projected)
                if len(samples) >= count:
                    break
        return np.array(samples[:count])

    @staticmethod
    def get_nearest_root(vector: np.ndarray) -> np.ndarray:
        """
        Find the nearest E8 root vector to the given vector.

        Args:
            vector: Input 8D vector

        Returns:
            np.ndarray: Nearest root vector from the 240 roots
        """
        roots = E8Lattice.get_roots()
        distances = np.linalg.norm(roots - vector, axis=1)
        nearest_idx = np.argmin(distances)
        return roots[nearest_idx]

    def get_root(self, index: int) -> np.ndarray:
        """
        Get a specific E8 root by index.

        Args:
            index: Root index (0-239)

        Returns:
            8D root vector
        """
        if not 0 <= index < 240:
            raise ValueError(f'Root index must be 0-239, got {index}')
        return self.roots[index]

    def get_root_vectors(self):
        """Return numpy array of shape (240, 8)."""
        return self._root_vecs

    @staticmethod
    def get_roots():
        """
        Generate the 240 root vectors of E₈.
        Simplified representation for computational efficiency.
        """
        roots = []
        base = [1, 1, 0, 0, 0, 0, 0, 0]
        for i in range(8):
            for j in range(i + 1, 8):
                for s1 in [1, -1]:
                    for s2 in [1, -1]:
                        root = [0] * 8
                        root[i] = s1
                        root[j] = s2
                        roots.append(root)
        for signs in range(256):
            root = []
            num_minus = 0
            for bit in range(8):
                if signs & 1 << bit:
                    root.append(0.5)
                else:
                    root.append(-0.5)
                    num_minus += 1
            if num_minus % 2 == 0:
                roots.append(root)
        return np.array(roots[:240])

    def get_simple_root(self, index: int) -> np.ndarray:
        """Get simple root by index (0-7)"""
        if not 0 <= index < 8:
            raise ValueError(f'Root index must be in [0, 7], got {index}')
        return self.B[index]

    def get_simple_roots(self) -> np.ndarray:
        """Get the 8 simple roots of E8."""
        return self.basis

    @staticmethod
    def get_weyl_chambers() -> int:
        """
        Get the number of Weyl chambers in E8.

        Returns:
            int: 48 Weyl chambers
        """
        return 48

    @staticmethod
    def get_weyl_group_order() -> int:
        """
        Get the order of the Weyl group.

        Returns:
            int: 696,729,600 = 2¹⁴ × 3⁵ × 5² × 7
        """
        return 696729600

    def gram(self):
        return self.B @ self.B.T

    def info(self) -> dict:
        """Return lattice information"""
        return {'dimension': self.dimension, 'num_roots': self.num_roots, 'num_cartan': self.num_cartan, 'total_slots': self.total_slots, 'condition_number': self.condition_number}

    def interpolate_geodesic(self, start: np.ndarray, end: np.ndarray, t: float) -> np.ndarray:
        """Interpolate along geodesic on E8 manifold."""
        dot = np.dot(start, end) / (np.linalg.norm(start) * np.linalg.norm(end))
        dot = np.clip(dot, -1.0, 1.0)
        theta = np.arccos(dot)
        if abs(theta) < 1e-06:
            return (1 - t) * start + t * end
        sin_theta = np.sin(theta)
        a = np.sin((1 - t) * theta) / sin_theta
        b = np.sin(t * theta) / sin_theta
        result = a * start + b * end
        return self.project_to_manifold(result)

    def is_in_weyl_chamber(self, vector: np.ndarray, tolerance: float=1e-06) -> bool:
        """
        Check if vector is in dominant Weyl chamber.

        Args:
            vector: Point to check
            tolerance: Numerical tolerance

        Returns:
            True if in dominant chamber
        """
        for i in range(8):
            alpha = self.get_simple_root(i)
            if np.dot(vector, alpha) < -tolerance:
                return False
        return True

    def is_lattice_point(self, v: np.ndarray, tol: float=1e-09) -> bool:
        """Check if a vector is a valid E8 lattice point."""
        is_integer = all((abs(c - round(c)) < tol for c in v))
        is_half_integer = all((abs(c - round(c) - 0.5) < tol or abs(c - round(c) + 0.5) < tol for c in v))
        if not (is_integer or is_half_integer):
            return False
        coord_sum = sum(v)
        return abs(coord_sum - round(coord_sum)) < tol

    def is_member(self, vec8d: np.ndarray, tol: float=1e-09) -> bool:
        """
        Check if vector is a valid E8 lattice point.

        A vector is in the E8 lattice if:
        1. All coordinates are either all integers OR all halves (x.5)
        2. The sum of coordinates is even
        """
        v = np.array(vec8d, dtype=np.float64)
        ints = all((abs(c - round(c)) < tol for c in v))
        halves = all((abs(c - 0.5 - round(c - 0.5)) < tol for c in v))
        if not (ints or halves):
            return False
        return int(round(sum(v))) % 2 == 0

    def is_on_lattice(self, vector: np.ndarray, tolerance: float=1e-06) -> bool:
        """
        Check if vector is on the E8 lattice.

        Args:
            vector: 8D vector to check
            tolerance: Numerical tolerance for floating point comparison

        Returns:
            True if vector is on lattice (within tolerance)
        """
        return self.distance_to_lattice(vector) < tolerance

    @staticmethod
    def is_valid_e8_point(v: np.ndarray, epsilon: float=1e-10) -> bool:
        """Check if point lies on E8 lattice."""
        all_int = all((abs(x - round(x)) < epsilon for x in v))
        all_half = all((abs(x - 0.5 - round(x - 0.5)) < epsilon for x in v))
        if not (all_int or all_half):
            return False
        total = sum(v)
        return abs(total - round(total)) < epsilon and int(round(total)) % 2 == 0

    def kissing_number(self) -> int:
        """Return the kissing number (240 for E8)."""
        return len(self.roots)

    def legal_delta(self, delta: np.ndarray) -> np.ndarray:
        """
        Snap/clip a proposed step `delta` to a legal small move.

        We constrain the norm of delta to COUPLING. This enforces Law 4
        (Optimized Efficiency) by preventing reckless high-strain jumps.

        In full CQE, we'd also check that this delta keeps us in a valid
        Weyl chamber and doesn't create illegal shear.
        """
        mag = np.linalg.norm(delta)
        if mag > COUPLING:
            delta = delta * (COUPLING / (mag + 1e-12))
        return delta

    @property
    def n(self):
        return self._n

    def nearest_root(self, vector: np.ndarray) -> Tuple[int, np.ndarray, float]:
        """Find the nearest E? root to the given vector."""
        if len(vector) != 8:
            raise ValueError('Vector must be 8-dimensional')
        distances = np.linalg.norm(self.roots - vector, axis=1)
        nearest_idx = np.argmin(distances)
        nearest_root = self.roots[nearest_idx]
        min_distance = distances[nearest_idx]
        return (nearest_idx, nearest_root, min_distance)

    def norm(self, v: E8Vector) -> float:
        """Norm."""
        return v.norm()

    def norm_squared(self, v: E8Vector) -> float:
        """Squared norm."""
        return v.norm_squared

    @staticmethod
    def normalize_to_e8_norm(vector: np.ndarray) -> np.ndarray:
        """
        Normalize vector to E8 standard norm (√2).

        Args:
            vector: Input 8D vector

        Returns:
            np.ndarray: Normalized vector with norm √2
        """
        current_norm = np.linalg.norm(vector)
        if current_norm == 0:
            return vector
        return vector * (E8_NORM / current_norm)

    def orbit(self, v: E8Vector, max_steps: int=10000) -> List[E8Vector]:
        """Generate Weyl orbit of a vector via BFS."""
        visited = {v.coords: v}
        queue = [v]
        while queue and len(visited) < max_steps:
            current = queue.pop(0)
            for alpha in self.simple_roots:
                reflected = self.weyl_reflect(current, alpha)
                if reflected.coords not in visited:
                    visited[reflected.coords] = reflected
                    queue.append(reflected)
        return list(visited.values())

    def packing_density(self) -> float:
        """
        Return sphere packing density.

        E8 achieves density π^4 / 384 ≈ 0.2537
        """
        return math.pi ** 4 / 384

    def project(self, vector: np.ndarray) -> np.ndarray:
        """
        Project arbitrary 8D vector to nearest E8 lattice point.

        Uses Babai nearest-plane algorithm for efficient projection.

        Args:
            vector: 8D input vector

        Returns:
            8D vector on E8 lattice (nearest lattice point)
        """
        if len(vector) != 8:
            raise ValueError(f'Expected 8D vector, got {len(vector)}D')
        rounded = np.round(vector)
        if np.allclose(vector, rounded, atol=1e-05):
            return rounded
        half_rounded = np.round(vector * 2) / 2
        if np.allclose(vector, half_rounded, atol=1e-05):
            doubled = (half_rounded * 2).astype(int)
            if np.sum(doubled) % 2 == 0:
                return half_rounded
        return rounded

    @staticmethod
    def project_to_2d_for_visualization(vector: np.ndarray) -> Tuple[float, float]:
        """
        Project 8D E8 vector to 2D for visualization.
        Uses first two principal components.

        Args:
            vector: 8D E8 vector

        Returns:
            Tuple[float, float]: (x, y) coordinates for 2D plot
        """
        return (float(vector[0]), float(vector[1]))

    def project_to_chamber(self, vector: np.ndarray, target_chamber: str='11111111') -> np.ndarray:
        """Project vector to specified Weyl chamber (default: fundamental)."""
        if len(vector) != 8:
            raise ValueError('Vector must be 8-dimensional')
        current_chamber, inner_prods = self.determine_chamber(vector)
        if current_chamber == target_chamber:
            return vector.copy()
        projected = vector.copy()
        for i, (current_bit, target_bit) in enumerate(zip(current_chamber, target_chamber)):
            if current_bit != target_bit:
                simple_root = self.simple_roots[i]
                inner_prod = np.dot(projected, simple_root)
                root_norm_sq = np.dot(simple_root, simple_root)
                if root_norm_sq > 1e-10:
                    projected = projected - 2 * inner_prod / root_norm_sq * simple_root
        return projected

    @staticmethod
    def project_to_e8(vector: np.ndarray) -> np.ndarray:
        """
        Project a vector onto the nearest E₈ lattice point.
        This enforces geometric constraints.

        Args:
            vector: Input vector (any dimension, will be padded/truncated to 8D)

        Returns:
            np.ndarray: Projected vector on E8 lattice
        """
        if len(vector) < 8:
            vector = np.pad(vector, (0, 8 - len(vector)), 'constant')
        elif len(vector) > 8:
            vector = vector[:8]
        return np.round(vector * 2) / 2

    def project_to_lattice(self, vector: np.ndarray) -> Tuple[np.ndarray, float]:
        """
        Project vector to E8 lattice using Babai nearest-plane algorithm.

        Args:
            vector: 8-dimensional input vector

        Returns:
            (lattice_point, error): Nearest lattice point and projection error
        """
        y = self.B @ vector
        z = np.linalg.solve(self.R, self.Q.T @ y)
        z_rounded = np.round(z)
        y_snapped = self.Q @ (self.R @ z_rounded)
        offset = y - y_snapped
        error = np.linalg.norm(offset)
        return (y_snapped, error)

    def project_to_manifold(self, vector: np.ndarray) -> np.ndarray:
        """Project to continuous E8 manifold (unit sphere)."""
        norm = np.linalg.norm(vector)
        if norm > 0:
            return vector / norm * E8_NORM
        return vector

    def projection_to_leech(self, v: E8Vector) -> List[float]:
        """
        Project E8 vector to Leech lattice (24D).

        Uses the fact that Leech contains 3 copies of E8.
        """
        leech_coords = list(v.coords) * 3
        return leech_coords[:24]

    def reflect(self, vec8d: np.ndarray, root_idx: int) -> np.ndarray:
        """
        Reflect vector across the hyperplane orthogonal to root[root_idx].

        Args:
            vec8d: 8D vector to reflect
            root_idx: Index of reflection root

        Returns:
            Reflected vector
        """
        v = np.array(vec8d, dtype=np.float64)
        r = self._root_vecs[root_idx]
        dot = np.dot(v, r)
        return v - dot * r

    @property
    def root_count(self) -> int:
        return 240

    def root_embedding_quality(self, vector: np.ndarray) -> Dict[str, float]:
        """Assess the quality of a vector's embedding in E₈ space."""
        nearest_idx, nearest_root, min_dist = self.nearest_root(vector)
        chamber_sig, inner_prods = self.determine_chamber(vector)
        metrics = {'nearest_root_distance': float(min_dist), 'nearest_root_index': int(nearest_idx), 'chamber_signature': chamber_sig, 'fundamental_chamber': chamber_sig == '11111111', 'vector_norm': float(np.linalg.norm(vector)), 'chamber_depth': float(np.min(np.abs(inner_prods))), 'symmetry_score': float(np.std(inner_prods))}
        return metrics

    @property
    def root_vecs(self):
        return self._root_vecs

    @property
    def roots(self):
        return self._roots

    def rotate_e8(self, vector: np.ndarray, axis1: int, axis2: int, angle: float) -> np.ndarray:
        """Rotate vector in E8 space around plane defined by axis1, axis2."""
        result = vector.copy()
        cos_a = np.cos(angle)
        sin_a = np.sin(angle)
        x = result[axis1]
        y = result[axis2]
        result[axis1] = cos_a * x - sin_a * y
        result[axis2] = sin_a * x + cos_a * y
        return result

    def scale(self, v: E8Vector, scalar: float) -> E8Vector:
        """Scale a vector."""
        return v * scalar

    def snap(self, vec8d: np.ndarray) -> Tuple[int, float]:
        """
        Snap an 8D vector to the nearest E8 root.

        Args:
            vec8d: 8-dimensional vector

        Returns:
            Tuple of (root_index, distance)
        """
        v = np.array(vec8d, dtype=np.float64)
        dists = np.linalg.norm(self._root_vecs - v, axis=1)
        idx = int(np.argmin(dists))
        return (idx, float(dists[idx]))

    @staticmethod
    def snap_to_lattice(v: np.ndarray) -> np.ndarray:
        """Snap a point to nearest E8 lattice point."""
        int_point = np.round(v)
        if E8Lattice.is_valid_e8_point(int_point):
            return int_point
        half_point = np.round(v - 0.5) + 0.5
        if E8Lattice.is_valid_e8_point(half_point):
            return half_point
        int_point = np.round(v)
        if int(sum(int_point)) % 2 != 0:
            fracs = np.abs(v - int_point)
            idx = np.argmax(fracs)
            int_point[idx] += 1 if v[idx] > int_point[idx] else -1
        return int_point

    def stats(self) -> Dict[str, Any]:
        """Get lattice statistics."""
        return {'dimension': E8_DIM, 'minimal_norm': E8_MIN_NORM, 'root_count': E8_ROOT_COUNT, 'weyl_group_order': self.root_system.weyl_group_order(), 'coxeter_number': self.root_system.coxeter_number(), 'packing_density': self.packing_density()}

    def subtract(self, v1: E8Vector, v2: E8Vector) -> E8Vector:
        """Subtract two vectors."""
        return v1 - v2

    def theta_coefficient(self, n: int) -> int:
        """
        Number of E8 vectors with norm² = 2n.
        Formula: r_E8(2n) = 240 * σ₃(n)
        where σ₃(n) = sum of cubes of divisors of n.
        """

        def sigma3(n: int) -> int:
            return sum((d ** 3 for d in range(1, n + 1) if n % d == 0))
        return 240 * sigma3(n)

    def to_mdhg_address(self, v: E8Vector) -> Dict[str, Any]:
        """
        Convert E8 vector to MDHG address.

        MDHG address format:
        - room, floor, building from first 6 coords
        - city, planet from remaining 2 + hash
        """
        coords = v.coords

        def hash_segment(segment: Tuple[float, ...]) -> str:
            return hashlib.sha256(json.dumps([round(c, 6) for c in segment]).encode()).hexdigest()[:8]
        return {'room': f'room_{hash_segment(coords[0:2])}', 'floor': f'floor_{hash_segment(coords[2:4])}', 'building': f'building_{hash_segment(coords[4:6])}', 'city': f'city_{hash_segment(coords[6:8])}', 'planet': f'planet_e8_{v.fingerprint()[:6]}', 'norm': round(v.norm(), 6)}

    @staticmethod
    def validate_e8_vector(vector: np.ndarray) -> bool:
        """
        Validate if a vector is properly formatted for E8 operations.

        Args:
            vector: Vector to validate

        Returns:
            bool: True if valid, False otherwise
        """
        if not isinstance(vector, np.ndarray):
            return False
        if vector.shape != (8,):
            return False
        if not np.isfinite(vector).all():
            return False
        return True

    def voronoi_cell_volume(self) -> float:
        """Compute volume of Voronoi cell."""
        return 1.0

    def weyl_group_action(self, vector: np.ndarray) -> np.ndarray:
        """Apply Weyl group action."""
        return vector

    def weyl_reflect(self, vector: np.ndarray, root_index: int) -> np.ndarray:
        """
        Apply Weyl reflection across simple root hyperplane.

        Args:
            vector: Point to reflect
            root_index: Index of simple root (0-7)

        Returns:
            Reflected vector
        """
        alpha = self.get_simple_root(root_index)
        alpha_norm_sq = np.dot(alpha, alpha)
        reflection = vector - 2 * np.dot(vector, alpha) / alpha_norm_sq * alpha
        return reflection

    def weyl_reflection(self, v: E8Vector, root: E8Vector) -> E8Vector:
        """
        Apply Weyl reflection across root.

        s_α(v) = v - 2(v·α)/(α·α) * α
        """
        root_norm_sq = root.dot(root)
        if root_norm_sq == 0:
            return v
        factor = 2 * v.dot(root) / root_norm_sq
        return v - root * factor

    def zero(self) -> E8Vector:
        """Return zero vector."""
        return E8Vector.zero()

    def _babai_closest_vector(self, target: np.ndarray) -> np.ndarray:
        """Babai's algorithm for closest vector in E8 lattice"""
        projection = np.dot(target.reshape(1, -1), self.fundamental_weights.T)
        rounded = np.round(projection)
        closest = np.dot(rounded, self.fundamental_weights).flatten()
        return closest

    def _build_roots(self):
        """Build the complete E8 root system."""
        roots = []
        root_vecs = []

        def add_root(vec, idx):
            vec = np.array(vec, dtype=np.float64)
            roots.append(E8Root(coords=vec, index=idx, norm_squared=2.0, parity=int(sum(vec) >= 0)))
            root_vecs.append(vec)
        idx = 0
        from itertools import combinations
        for i, j in combinations(range(8), 2):
            for s1 in (+1.0, -1.0):
                for s2 in (+1.0, -1.0):
                    vec = [0.0] * 8
                    vec[i] = s1
                    vec[j] = s2
                    add_root(vec, idx)
                    idx += 1
        n_type2 = 128
        for mask in range(1 << 8):
            bits = [mask >> k & 1 for k in range(8)]
            if sum(bits) % 2 == 0:
                vec = [-0.5 if b else 0.5 for b in bits]
                add_root(vec, idx)
                idx += 1
        assert len(roots) == 240, f'Expected 240 roots, got {len(roots)}'
        self._roots = roots
        self._root_vecs = np.array(root_vecs, dtype=np.float64)

    def _compute_cartan_matrix(self) -> np.ndarray:
        """Compute Cartan matrix from simple roots."""
        cartan = np.zeros((8, 8))
        for i in range(8):
            for j in range(8):
                cartan[i, j] = 2 * np.dot(self.simple_roots[i], self.simple_roots[j]) / np.dot(self.simple_roots[j], self.simple_roots[j])
        return cartan

    def _compute_gram_matrix(self) -> np.ndarray:
        """Compute Gram matrix of root inner products."""
        return self.roots @ self.roots.T

    def _compute_minimal_vectors(self) -> List[np.ndarray]:
        """Compute all 240 minimal vectors of E8."""
        return [root.to_array() for root in self.weyl.root_system]

    def _construct_e8_basis(self) -> np.ndarray:
        """
        Construct E8 simple root basis matrix.
        Uses standard E8 root system construction.
        """
        B = np.array([[1, -1, 0, 0, 0, 0, 0, 0], [0, 1, -1, 0, 0, 0, 0, 0], [0, 0, 1, -1, 0, 0, 0, 0], [0, 0, 0, 1, -1, 0, 0, 0], [0, 0, 0, 0, 1, -1, 0, 0], [0, 0, 0, 0, 0, 1, -1, 0], [0, 0, 0, 0, 0, 0, 1, -1], [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]], dtype=float)
        return B

    def _construct_e8_roots(self) -> np.ndarray:
        """
        Construct an approximate E8 root system.

        Classical description (schematic):
        - 112 roots with two ±1 entries, others 0
        - 128 roots with ±1/2 entries (even number of minus signs)
        Each such root is normalized to length sqrt(2).

        Real production code would implement the full 240 E8 roots
        explicitly and store them in canonical orientation.
        """
        roots = []
        basis = np.eye(8)
        for i in range(8):
            for j in range(i + 1, 8):
                for signs in [(1, 1), (1, -1), (-1, 1), (-1, -1)]:
                    v = np.zeros(8)
                    v[i] = signs[0]
                    v[j] = signs[1]
                    roots.append(v)
        import itertools
        for signs in itertools.product([+0.5, -0.5], repeat=8):
            if sum((1 for s in signs if s < 0)) % 2 == 0:
                roots.append(np.array(signs))
        roots_arr = np.array(roots, dtype=float)
        norms = np.sqrt(np.sum(roots_arr ** 2, axis=1, keepdims=True))
        roots_arr = roots_arr * (np.sqrt(2.0) / norms)
        return roots_arr

    def _even_sign_patterns(self) -> List[List[int]]:
        """Generate sign patterns with even number of -1s."""
        patterns = []
        for bits in range(256):
            signs = []
            count_neg = 0
            for i in range(8):
                sign = -1 if bits >> i & 1 else 1
                signs.append(sign)
                if sign == -1:
                    count_neg += 1
            if count_neg % 2 == 0:
                patterns.append(signs)
        return patterns

    def _generate_cartan_matrix(self) -> np.ndarray:
        """Generate Cartan matrix for E8"""
        cartan = np.array([[2, -1, 0, 0, 0, 0, 0, 0], [-1, 2, -1, 0, 0, 0, 0, 0], [0, -1, 2, -1, 0, 0, 0, 0], [0, 0, -1, 2, -1, 0, 0, 0], [0, 0, 0, -1, 2, -1, 0, -1], [0, 0, 0, 0, -1, 2, -1, 0], [0, 0, 0, 0, 0, -1, 2, 0], [0, 0, 0, 0, -1, 0, 0, 2]])
        return cartan

    def _generate_e8_roots(self) -> np.ndarray:
        """Generate 240 E8 root vectors"""
        roots = []
        for i in range(8):
            for j in range(i + 1, 8):
                for s1 in [-1, 1]:
                    for s2 in [-1, 1]:
                        root = np.zeros(8)
                        root[i] = s1
                        root[j] = s2
                        roots.append(root)
        for pattern in range(256):
            root = np.array([1 / 2 if pattern >> i & 1 else -1 / 2 for i in range(8)])
            if np.sum(root < 0) % 2 == 0:
                roots.append(root)
        return np.array(roots[:240])

    def _generate_fundamental_weights(self) -> np.ndarray:
        """Generate 8 fundamental weights for E8"""
        weights = np.zeros((8, 8))
        for i in range(8):
            weights[i] = np.array([1 if j <= i else 0 for j in range(8)])
        return weights

    def _generate_roots(self) -> List[E8Root]:
        """Generate all 240 E8 root vectors."""
        roots = []
        for i in range(8):
            for j in range(i + 1, 8):
                for s1 in [-1, 1]:
                    for s2 in [-1, 1]:
                        coords = np.zeros(8)
                        coords[i] = s1
                        coords[j] = s2
                        roots.append(E8Root(coords, len(roots), E8_NORM))
        for signs in range(256):
            coords = np.array([(1 if signs >> i & 1 else -1) / 2 for i in range(8)])
            if np.sum(coords < 0) % 2 == 0:
                roots.append(E8Root(coords, len(roots), E8_NORM))
        return roots[:240]

    def _generate_simple_roots(self) -> np.ndarray:
        """Generate E8 simple root vectors"""
        roots = []
        for i in range(7):
            root = np.zeros(8)
            root[i] = 1
            root[i + 1] = -1
            roots.append(root)
        root = np.zeros(8)
        root[6] = 1
        root[7] = 1
        roots.append(root)
        return np.array(roots)

    def _generate_weyl_chambers(self) -> List[np.ndarray]:
        """Generate 48 Weyl chambers (fundamental domains)."""
        chambers = []
        for i in range(48):
            angle = 2 * np.pi * i / 48
            normal = np.array([np.cos(angle), np.sin(angle), np.cos(2 * angle), np.sin(2 * angle), np.cos(3 * angle), np.sin(3 * angle), np.cos(4 * angle), np.sin(4 * angle)])
            chambers.append(normal / np.linalg.norm(normal))
        return chambers

    def _initialize_root_vectors(self):
        """Initialize the 240 root vectors of E₈."""
        roots = []
        for i in range(8):
            for j in range(i + 1, 8):
                for s1 in [-1, 1]:
                    for s2 in [-1, 1]:
                        root = np.zeros(8)
                        root[i] = s1
                        root[j] = s2
                        roots.append(root)
        for signs in range(256):
            root = np.array([(1 if signs >> i & 1 else -1) * 0.5 for i in range(8)])
            if np.sum(root < 0) % 2 == 0:
                roots.append(root)
        self.root_vectors = np.array(roots[:240])

    def _load_embedding(self):
        """Load the cached E? embedding."""
        if not Path(self.embedding_path).exists():
            raise FileNotFoundError(f'E? embedding not found at {self.embedding_path}')
        with open(self.embedding_path, 'r') as f:
            data = json.load(f)
        self.roots = np.array(data['roots_8d'])
        self.cartan_matrix = np.array(data['cartan_8x8'])
        print(f'Loaded E? embedding: {len(self.roots)} roots, {self.cartan_matrix.shape} Cartan matrix')

    def _setup_chambers(self):
        """Setup simple roots for Weyl chamber calculations."""
        self.simple_roots = self.roots[:8]
        if self.simple_roots.shape != (8, 8):
            raise ValueError('Invalid simple root system shape')

    def _simple_roots(self) -> List[np.ndarray]:
        """Simple roots in Bourbaki ordering."""
        return [np.array([1, -1, 0, 0, 0, 0, 0, 0], dtype=float), np.array([0, 1, -1, 0, 0, 0, 0, 0], dtype=float), np.array([0, 0, 1, -1, 0, 0, 0, 0], dtype=float), np.array([0, 0, 0, 1, -1, 0, 0, 0], dtype=float), np.array([0, 0, 0, 0, 1, -1, 0, 0], dtype=float), np.array([0, 0, 0, 0, 0, 1, -1, 0], dtype=float), np.array([0, 0, 0, 0, 0, 1, 1, 0], dtype=float), np.array([-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5], dtype=float)]

    def _string_to_features(self, s: str) -> np.ndarray:
        """Convert string to 8D feature vector"""
        features = np.zeros(8)
        for i in range(8):
            hash_input = s + str(i)
            features[i] = hash(hash_input) % 1000
        return features / 1000.0
