"""
Composed canonical: E8Root

Family: e8root
Decision: batch=8 id=678
Composition: method-union of 10 variants → 12 methods (11 conflicts resolved), 10 attrs

Auto-generated by place_canonicals.py from the atomic decision queue.
Do not edit by hand — re-run the merger to refresh.
"""
from __future__ import annotations

class E8Root:
    """E8 root vector."""
    coords: np.ndarray
    index: int
    norm: float
    vector: np.ndarray
    norm_squared: float
    parity: int
    root_type: str
    root_vector: np.ndarray
    capability_id: str
    description: str

    def __init__(self, coords: np.ndarray, index: int):
        self.coords = coords
        self.index = index
        self.norm_squared = np.dot(self.coords, self.coords)
        coord_sum = np.sum(self.coords)
        self.parity = 'even' if coord_sum % 2 == 0 else 'odd'

    def __post_init__(self):
        """Compute derived properties"""
        self.norm_squared = float(np.dot(self.vector, self.vector))
        self.parity = int(np.sum(self.vector)) % 2

    def __repr__(self):
        return f'E8Root({self.index}, type={self.root_type})'

    def __str__(self) -> str:
        return f'α{self.index}({self.root_type.value})={self.coords}'

    def commute_with(self, other: E8Root) -> bool:
        """Check if this root commutes with another (Cartan matrix check)"""
        return np.abs(np.dot(self.root_vector, other.root_vector)) < 1e-10

    def hash(self) -> str:
        """Generate deterministic hash for this root."""
        data = json.dumps({'coords': self.coords, 'type': self.root_type.value, 'index': self.index}, sort_keys=True)
        return hashlib.sha256(data.encode()).hexdigest()[:16]

    def inner_product(self, other: 'E8Root') -> int:
        """Compute inner product with another root."""
        return sum((a * b for a, b in zip(self.coords, other.coords)))

    def norm(self) -> float:
        """Compute norm (length) of the root."""
        return np.sqrt(self.norm_squared())

    def norm_squared(self) -> int:
        """Compute squared norm of the root."""
        return sum((c * c for c in self.coords))

    def to_array(self) -> np.ndarray:
        """Convert to numpy array."""
        return np.array(self.coords, dtype=np.float64)

    def to_dict(self) -> dict:
        """Convert to dictionary for receipts"""
        return {'vector': self.vector.tolist(), 'norm_squared': self.norm_squared, 'parity': self.parity, 'root_type': self.root_type}

    def weyl_reflection(self, hyperplane: np.ndarray) -> E8Root:
        """Apply Weyl reflection through hyperplane"""
        h_norm_sq = np.dot(hyperplane, hyperplane)
        reflection = self.root_vector - 2 * np.dot(self.root_vector, hyperplane) * hyperplane / h_norm_sq
        return E8Root(root_vector=reflection, root_type=self.root_type, capability_id=self.capability_id, description=self.description)
