"""
Composed canonical: MMDB  [PENDING REVIEW]

Family:           mmdb
Original family:  mmdb
Replicas:         3  (below hardening threshold of 10)
Witness:          <composed from 3 variants, 37 methods, 7 conflicts>

⚠️  PENDING REVIEW — set aside in the first hardening pass.

Low-replica items often live here for one of four reasons:

  1. Novel adaptation that had not yet propagated to other files
     (the system was being extended; this is the new edge).
  2. Recently-added upgrade that exists only in one or two places
     (newer than the hardened version, may supersede it).
  3. Specific-purpose fix or adaptation layer — addresses one
     particular need that the broader hardened set does not.
  4. Genuine noise the first-pass noise filter missed (test,
     demo, scratch experiment).

Review criteria for second pass — for each pending file:

  (a) Is its functionality already covered by the hardened set?
      → If YES: is there novel material here worth merging in?
      → If NO:  should this be promoted to hardened?
  (b) Does it superesede something in hardened (it might be the
      newer / better version that has not yet replicated)?
  (c) Is it noise after second look? → drop with rationale.

Composition: method-union of 3 variants → 37 methods (7 conflicts resolved), 0 attrs

Auto-generated by partition_canonicals.py. Do not edit by hand;
re-run the merger if the source pool changes.
"""
from __future__ import annotations

class MMDB:
    """
    Monster Moonshine Database.

    Thread-safety: the controller's RLock serializes all writes.
    Reads are safe for concurrent access (SQLite WAL mode).
    """

    def __init__(self, db_path: str=':memory:'):
        self.db_path = db_path
        self._conn = sqlite3.connect(db_path, check_same_thread=False)
        self._conn.execute('PRAGMA journal_mode=WAL')
        self._conn.execute('PRAGMA foreign_keys=ON')
        self._conn.executescript(_SCHEMA)
        self._conn.commit()
        self.e8 = E8Lattice()
        self.leech = LeechLattice()
        self.receipt_chain = ReceiptChain()

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()

    def add_bond(self, source_id: str, target_id: str, bond_type: str, weight: float=1.0) -> str:
        """Create a directed bond between two atoms."""
        import uuid
        bond_id = uuid.uuid4().hex[:16]
        self._conn.execute('INSERT INTO bonds (bond_id, source_id, target_id, bond_type, weight, created_at) VALUES (?, ?, ?, ?, ?, ?)', (bond_id, source_id, target_id, bond_type, weight, time.time()))
        self._conn.commit()
        return bond_id

    def applied_migrations(self) -> List[str]:
        assert self.conn is not None
        try:
            rows = self.conn.execute('SELECT name FROM mmdb_migration ORDER BY applied_at').fetchall()
            return [r['name'] for r in rows]
        except sqlite3.OperationalError:
            return []

    def apply_migration(self, name: str, sql: str) -> bool:
        assert self.conn is not None
        if name in self.applied_migrations():
            return False
        self.conn.executescript(sql)
        self.conn.execute('INSERT INTO mmdb_migration (name) VALUES (?)', (name,))
        self.conn.commit()
        return True

    def close(self):
        self._atoms.close()
        self._vectors.close()

    def composition_pool(self, limit: int=20) -> List[MMDBResult]:
        """High-floor, high-quality atoms ready for composition."""
        atoms = self._atoms.composition_candidates(limit=limit)
        return [MMDBResult(atom=a, score=1.0, rank=i + 1, search_type='property') for i, a in enumerate(atoms)]

    def connect(self) -> sqlite3.Connection:
        self.conn = sqlite3.connect(self.db_path)
        self.conn.row_factory = sqlite3.Row
        self.conn.execute('PRAGMA journal_mode=WAL')
        self.conn.execute('PRAGMA foreign_keys=ON')
        return self.conn

    def corpus_stats(self) -> Dict[str, Any]:
        """Full corpus overview (floor counts, DR distribution, quality)."""
        return self._atoms.stats()

    def count(self, phase: Optional[str]=None) -> int:
        """Count atoms, optionally filtered by phase."""
        if phase:
            return self._conn.execute('SELECT COUNT(*) FROM atoms WHERE phase = ?', (phase,)).fetchone()[0]
        return self._conn.execute('SELECT COUNT(*) FROM atoms').fetchone()[0]

    def create_corpus(self, label: str, metadata: Optional[Dict]=None) -> str:
        assert self.conn is not None
        cid = uuid.uuid4().hex[:12]
        self.conn.execute('INSERT INTO corpus_instance (id, label, metadata) VALUES (?, ?, ?)', (cid, label, json.dumps(metadata or {})))
        self.conn.commit()
        return cid

    def create_orbit(self, label: str, members: List[str], orbit_type: str='moonshine') -> str:
        assert self.conn is not None
        oid = uuid.uuid4().hex[:12]
        self.conn.execute('INSERT INTO orbit (id, label, members, orbit_type) VALUES (?, ?, ?, ?)', (oid, label, json.dumps(members), orbit_type))
        self.conn.commit()
        return oid

    def dr_neighborhood(self, atom: CmplxAtom, limit: int=10) -> List[MMDBResult]:
        """Find atoms with complementary digital roots (DR + complement_DR = 9)."""
        atoms = self._atoms.dr_complements(atom, limit=limit)
        return [MMDBResult(atom=a, score=1.0, rank=i + 1, search_type='property') for i, a in enumerate(atoms)]

    def get(self, atom_id: str) -> Optional[Atom]:
        """Retrieve an atom by ID."""
        row = self._conn.execute("SELECT data_json FROM atoms WHERE atom_id = ? AND phase != 'tombstoned'", (atom_id,)).fetchone()
        if row is None:
            return None
        return Atom.from_dict(json.loads(row[0]))

    def get_bonds(self, atom_id: str, bond_type: Optional[str]=None) -> List[Dict]:
        """Get all bonds for an atom (as source or target)."""
        if bond_type:
            rows = self._conn.execute('SELECT bond_id, source_id, target_id, bond_type, weight FROM bonds WHERE (source_id = ? OR target_id = ?) AND bond_type = ?', (atom_id, atom_id, bond_type)).fetchall()
        else:
            rows = self._conn.execute('SELECT bond_id, source_id, target_id, bond_type, weight FROM bonds WHERE source_id = ? OR target_id = ?', (atom_id, atom_id)).fetchall()
        return [{'bond_id': r[0], 'source_id': r[1], 'target_id': r[2], 'bond_type': r[3], 'weight': r[4]} for r in rows]

    def import_chunks(self, source_id: str, chunks: List[Dict[str, Any]]) -> int:
        """Import chunk records. Each dict: {content, offset, length}."""
        assert self.conn is not None
        count = 0
        for c in chunks:
            cid = uuid.uuid4().hex[:12]
            self.conn.execute('INSERT INTO chunk (id, source_id, offset, length, content) VALUES (?, ?, ?, ?, ?)', (cid, source_id, c.get('offset', 0), c.get('length', len(c['content'])), c['content']))
            count += 1
        self.conn.commit()
        return count

    def import_sources(self, corpus_id: str, sources: List[Dict[str, Any]]) -> int:
        """Import source records. Each dict: {path, sha256, byte_size, mime_type}."""
        assert self.conn is not None
        count = 0
        for s in sources:
            sid = uuid.uuid4().hex[:12]
            self.conn.execute('INSERT OR IGNORE INTO source (id, corpus_id, path, sha256, byte_size, mime_type) VALUES (?, ?, ?, ?, ?, ?)', (sid, corpus_id, s['path'], s['sha256'], s.get('byte_size', 0), s.get('mime_type', 'text/plain')))
            count += 1
        self.conn.commit()
        return count

    def import_term_to_chunks(self, mappings: List[Dict[str, str]]) -> int:
        """Import term↔chunk links. Each dict: {term_value, chunk_id, position}."""
        assert self.conn is not None
        count = 0
        for m in mappings:
            tid = hashlib.sha256(m['term_value'].encode()).hexdigest()[:12]
            self.conn.execute('INSERT OR IGNORE INTO term (id, value, frequency) VALUES (?, ?, 0)', (tid, m['term_value']))
            self.conn.execute('UPDATE term SET frequency = frequency + 1 WHERE id = ?', (tid,))
            self.conn.execute('INSERT OR IGNORE INTO term_chunk (term_id, chunk_id, position) VALUES (?, ?, ?)', (tid, m['chunk_id'], m.get('position', 0)))
            count += 1
        self.conn.commit()
        return count

    def ingest_receipts_from_jsonl(self, path: str) -> int:
        """Bulk-ingest receipts from a JSONL file."""
        count = 0
        if not os.path.exists(path):
            return 0
        with open(path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                r = json.loads(line)
                self.insert_receipt(action=r.get('action', ''), inputs_hash=r.get('inputs_hash', ''), outputs_hash=r.get('outputs_hash', ''), prev_hash=r.get('prev_hash', ''), controller=r.get('controller', ''))
                count += 1
        return count

    def init_db(self) -> None:
        """Initialize all tables from schema."""
        if self.conn is None:
            self.connect()
        assert self.conn is not None
        self.conn.executescript(SCHEMA_V0_1)
        self.conn.commit()

    def insert_receipt(self, action: str, inputs_hash: str, outputs_hash: str, prev_hash: str='', controller: str='') -> str:
        assert self.conn is not None
        rid = uuid.uuid4().hex[:12]
        self.conn.execute('INSERT INTO receipt (id, action, inputs_hash, outputs_hash, prev_hash, controller) VALUES (?, ?, ?, ?, ?, ?)', (rid, action, inputs_hash, outputs_hash, prev_hash, controller))
        self.conn.commit()
        return rid

    def is_loaded(self) -> bool:
        return self._loaded

    def list_orbits(self) -> List[Dict[str, Any]]:
        assert self.conn is not None
        rows = self.conn.execute('SELECT id, label, orbit_type, members FROM orbit').fetchall()
        return [dict(r) for r in rows]

    def list_sources(self, corpus_id: str) -> List[Dict[str, Any]]:
        assert self.conn is not None
        rows = self.conn.execute('SELECT id, path, sha256, byte_size, mime_type FROM source WHERE corpus_id = ?', (corpus_id,)).fetchall()
        return [dict(r) for r in rows]

    def load(self, floor_filter: str='', limit: int=0) -> int:
        """Build in-memory E8 index. Returns number of atoms indexed.

        Call once at startup. Subsequent calls rebuild the index.
        For 157k atoms: ~2 seconds, ~12.5MB RAM.
        """
        t0 = time.time()
        count = self._vectors.build_index(floor_filter=floor_filter, limit=limit)
        self._load_time_ms = (time.time() - t0) * 1000
        self._loaded = count > 0
        return count

    def near_vector(self, query_vec: List[float], limit: int=10, floor: str='', dr: int=0, certainty: float=0.0) -> List[MMDBResult]:
        """Find atoms near a vector in E8 space (Weaviate nearVector).

        Args:
            query_vec: 8D E8 query vector
            limit: max results
            floor: optional property filter (e.g. "f07")
            dr: optional digital root filter (1-9)
            certainty: minimum cosine similarity threshold (0-1)

        Returns:
            MMDBResult list ordered by descending cosine similarity.
        """
        self._stats['vector_queries'] += 1
        search_type = 'vector'
        if floor or dr:
            search_type = 'hybrid'
            self._stats['hybrid_queries'] += 1
            self._stats['vector_queries'] -= 1
        vec_results: List[SearchResult] = self._vectors.search(query_vec, k=limit, floor_filter=floor, dr_filter=dr)
        if certainty > 0:
            vec_results = [r for r in vec_results if r.score >= certainty]
        atom_ids = [r.atom_id for r in vec_results]
        atoms_by_id = {a.atom_id: a for a in self._atoms.get_many(atom_ids)}
        results = []
        for vr in vec_results:
            atom = atoms_by_id.get(vr.atom_id)
            if atom is None:
                continue
            results.append(MMDBResult(atom=atom, score=vr.score, rank=vr.rank, search_type=search_type))
        return results

    def neighbors(self, atom_id: str, limit: int=10) -> List[MMDBResult]:
        """Find geometrically similar atoms (Weaviate nearObject).

        Uses E8 cosine similarity. The atom itself is excluded from results.
        """
        vec_results = self._vectors.similar_to_atom(atom_id, k=limit)
        if not vec_results:
            return []
        atom_ids = [r.atom_id for r in vec_results]
        atoms_by_id = {a.atom_id: a for a in self._atoms.get_many(atom_ids)}
        results = []
        for vr in vec_results:
            atom = atoms_by_id.get(vr.atom_id)
            if atom is None:
                continue
            results.append(MMDBResult(atom=atom, score=vr.score, rank=vr.rank, search_type='vector'))
        return results

    def place(self, atom: Atom) -> Atom:
        """
        Place an atom in MMDB.
        - Compute E8 projection if not already set
        - Compute Leech embedding
        - Store in SQLite
        - Update phase to PLACED
        - Emit receipt
        """
        now = time.time()
        if np.allclose(atom.e8_coords, 0) and atom.content:
            atom.set_e8(self.e8.embed_content(atom.content))
        if np.allclose(atom.leech_coords, 0):
            atom.set_leech(self.leech.embed_e8(atom.e8_coords, block=0))
        atom.phase = AtomPhase.PLACED
        data = json.dumps(atom.to_dict())
        self._conn.execute('INSERT INTO atoms\n               (atom_id, kind, phase, content_hash, label, dr, mass, charge,\n                e8_coords, leech_coords, mdhg_room, mdhg_floor, mdhg_building,\n                mdhg_city, data_json, created_at, updated_at)\n               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\n               ON CONFLICT(atom_id) DO UPDATE SET\n                 phase=excluded.phase, label=excluded.label, dr=excluded.dr,\n                 mass=excluded.mass, charge=excluded.charge,\n                 e8_coords=excluded.e8_coords, leech_coords=excluded.leech_coords,\n                 mdhg_room=excluded.mdhg_room, mdhg_floor=excluded.mdhg_floor,\n                 mdhg_building=excluded.mdhg_building, mdhg_city=excluded.mdhg_city,\n                 data_json=excluded.data_json, updated_at=excluded.updated_at', (atom.atom_id, atom.kind.value, atom.phase.value, atom.content_hash, atom.label, atom.dr, atom.mass, atom.charge, json.dumps(atom.e8_coords.tolist()), json.dumps(atom.leech_coords.tolist()), atom.mdhg_room, atom.mdhg_floor, atom.mdhg_building, atom.mdhg_city, data, atom.created_at, now))
        self._conn.commit()
        r = self.receipt_chain.emit(domain='mmdb', command='place', atoms_created=1, invariants_checked=1, invariants_passed=1)
        atom.receipt_ids.append(r.receipt_id)
        self._store_receipt(r)
        return atom

    def query_by_dr(self, dr: int) -> List[Atom]:
        """Find all atoms with a given digital root."""
        rows = self._conn.execute("SELECT data_json FROM atoms WHERE dr = ? AND phase != 'tombstoned'", (dr,)).fetchall()
        return [Atom.from_dict(json.loads(r[0])) for r in rows]

    def query_nearest_e8(self, coords: np.ndarray, limit: int=10) -> List[Tuple[Atom, float]]:
        """
        Find atoms nearest to given E8 coordinates.
        Uses cosine similarity for efficiency (exact lattice distance
        requires loading all atoms).
        """
        target = np.asarray(coords, dtype=np.float64)[:8]
        target_norm = np.linalg.norm(target)
        if target_norm < 1e-10:
            return []
        rows = self._conn.execute("SELECT atom_id, e8_coords, data_json FROM atoms WHERE phase != 'tombstoned'").fetchall()
        scored = []
        for row in rows:
            e8 = np.array(json.loads(row[1]), dtype=np.float64)
            e8_norm = np.linalg.norm(e8)
            if e8_norm < 1e-10:
                continue
            similarity = float(np.dot(target, e8) / (target_norm * e8_norm))
            scored.append((similarity, row[2]))
        scored.sort(key=lambda x: -x[0])
        return [(Atom.from_dict(json.loads(data)), sim) for sim, data in scored[:limit]]

    def search_chunks(self, term_value: str, limit: int=20) -> List[Dict[str, Any]]:
        assert self.conn is not None
        rows = self.conn.execute('\n            SELECT c.id, c.content, c.offset, c.length, s.path\n            FROM chunk c\n            JOIN source s ON c.source_id = s.id\n            JOIN term_chunk tc ON tc.chunk_id = c.id\n            JOIN term t ON t.id = tc.term_id\n            WHERE t.value = ?\n            LIMIT ?\n            ', (term_value, limit)).fetchall()
        return [dict(r) for r in rows]

    def stats(self) -> Dict[str, Any]:
        total = self.count()
        placed = self.count('placed')
        closed = self.count('closed')
        composed = self.count('composed')
        tombs = self.count('tombstoned')
        bonds = self._conn.execute('SELECT COUNT(*) FROM bonds').fetchone()[0]
        receipts = self._conn.execute('SELECT COUNT(*) FROM receipts').fetchone()[0]
        return {'total_atoms': total, 'placed': placed, 'closed': closed, 'composed': composed, 'tombstoned': tombs, 'bonds': bonds, 'receipts': receipts, 'chain_valid': self.receipt_chain.verify()}

    def store_invariant(self, atom_id: str, check_name: str, passed: bool, cost: float=0.0, detail: str=''):
        """Record an invariant check result for an atom."""
        self._conn.execute('INSERT OR REPLACE INTO invariants (atom_id, check_name, passed, cost, detail, checked_at) VALUES (?, ?, ?, ?, ?, ?)', (atom_id, check_name, int(passed), cost, detail, time.time()))
        self._conn.commit()

    def tombstone(self, atom_id: str) -> bool:
        """Mark an atom as tombstoned (superseded). Never deletes."""
        self._conn.execute("UPDATE atoms SET phase = 'tombstoned', updated_at = ? WHERE atom_id = ?", (time.time(), atom_id))
        self._conn.commit()
        self.receipt_chain.emit(domain='mmdb', command='tombstone', atoms_modified=1)
        return True

    def where(self, floor: str='', dr: int=0, label: str='', crt_channel: int=-1, min_quality: float=0.0, limit: int=100, offset: int=0) -> List[MMDBResult]:
        """Property-based query (Weaviate where filter).

        All filters are AND-combined. Returns results with score=1.0
        (no geometric ranking for pure property queries).
        """
        self._stats['property_queries'] += 1
        if label:
            atoms = self._atoms.by_label(label, limit=limit)
        elif crt_channel >= 0:
            atoms = self._atoms.by_crt_channel(crt_channel, limit=limit)
        elif floor:
            atoms = self._atoms.by_floor(floor, limit=limit, offset=offset)
        elif dr:
            atoms = self._atoms.by_dr(dr, limit=limit)
        else:
            atoms = self._atoms.sample(n=limit, min_quality=min_quality)
        if floor and (not label) and (not crt_channel >= 0):
            pass
        if dr and floor:
            atoms = [a for a in atoms if a.digital_root == dr]
        if min_quality > 0:
            atoms = [a for a in atoms if a.quality_overall >= min_quality]
        return [MMDBResult(atom=a, score=1.0, rank=i + 1, search_type='property') for i, a in enumerate(atoms)]

    def _store_receipt(self, r: Receipt):
        self._conn.execute('INSERT OR REPLACE INTO receipts (receipt_id, domain, command, delta_phi, prev_hash, receipt_hash, data_json, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', (r.receipt_id, r.domain, r.command, r.delta_phi, r.prev_hash, r.receipt_hash, json.dumps(r.to_dict()), r.timestamp))
        self._conn.commit()
